# Get daily average values for air pollution in Romania from 2016-2026 using openAQ API

In [1]:
import requests
import pandas as pd 
import time

### List possible parameters (e.g. PM10, PM2.5, NO2)

In [ ]:
api_url = "https://api.openaq.org/v3/parameters"

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, headers=headers)
response = response.json()

response

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 46},
 'results': [{'id': 1,
   'name': 'pm10',
   'units': 'µg/m³',
   'displayName': 'PM10',
   'description': 'Particulate matter less than 10 micrometers in diameter mass concentration'},
  {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': 'PM2.5',
   'description': 'Particulate matter less than 2.5 micrometers in diameter mass concentration'},
  {'id': 3,
   'name': 'o3',
   'units': 'µg/m³',
   'displayName': 'O₃ mass',
   'description': 'Ozone mass concentration'},
  {'id': 4,
   'name': 'co',
   'units': 'µg/m³',
   'displayName': 'CO mass',
   'description': 'Carbon Monoxide mass concentration'},
  {'id': 5,
   'name': 'no2',
   'units': 'µg/m³',
   'displayName': 'NO₂ mass',
   'description': 'Nitrogen Dioxide mass concentration'},
  {'id': 6,
   'name': 'so2',
   'units': 'µg/m³',
   'displayName': 'SO₂ mass',
   'description': 'Sulfur Dioxide mass concentration'},
  {'id': 7,
   'name': 'no2',
   'units': 'ppm',
   'displayName': 'NO₂',
   'description': 'Nitrogen Dioxide concentration'},
  {'id': 8,
   'name': 'co',
   'units': 'ppm',
   'displayName': 'CO',
   'description': 'Carbon Monoxide concentration'},
  {'id': 9,
   'name': 'so2',
   'units': 'ppm',
   'displayName': 'SO₂',
   'description': 'Sulfur Dioxide concentration'},
  {'id': 10,
   'name': 'o3',
   'units': 'ppm',
   'displayName': 'O₃',
   'description': 'Ozone concentration'},
  {'id': 11,
   'name': 'bc',
   'units': 'µg/m³',
   'displayName': 'BC',
   'description': 'Black Carbon mass concentration'},
  {'id': 15,
   'name': 'no2',
   'units': 'ppb',
   'displayName': 'NO₂',
   'description': None},
  {'id': 19,
   'name': 'pm1',
   'units': 'µg/m³',
   'displayName': 'PM1',
   'description': 'Particulate matter less than 1 micrometer in diameter mass concentration'},
  {'id': 21,
   'name': 'co2',
   'units': 'ppm',
   'displayName': 'CO₂',
   'description': 'Carbon Dioxide concentration'},
  {'id': 22,
   'name': 'wind_direction',
   'units': 'deg',
   'displayName': 'Wind direction',
   'description': 'Direction that the wind originates from'},
  {'id': 23,
   'name': 'nox',
   'units': 'ppb',
   'displayName': 'NOX',
   'description': None},
  {'id': 24,
   'name': 'no',
   'units': 'ppb',
   'displayName': 'NO',
   'description': None},
  {'id': 27,
   'name': 'nox',
   'units': 'µg/m³',
   'displayName': 'NOx mass',
   'description': 'Nitrogen Oxides mass concentration'},
  {'id': 28,
   'name': 'ch4',
   'units': 'ppm',
   'displayName': 'CH₄',
   'description': 'Methane concentration'},
  {'id': 32,
   'name': 'o3',
   'units': 'ppb',
   'displayName': 'O₃',
   'description': None},
  {'id': 33,
   'name': 'ufp',
   'units': 'particles/cm³',
   'displayName': 'UFP count',
   'description': 'Ultrafine Particles count concentration'},
  {'id': 34,
   'name': 'wind_speed',
   'units': 'm/s',
   'displayName': 'Wind speed',
   'description': 'Average wind speed in meters per second'},
  {'id': 35,
   'name': 'no',
   'units': 'ppm',
   'displayName': 'NO',
   'description': 'Nitrogen Monoxide concentration'},
  {'id': 95,
   'name': 'pressure',
   'units': 'hpa',
   'displayName': 'Atmospheric pressure',
   'description': 'Atmospheric or barometric pressure'},
  {'id': 97,
   'name': 'pm25-old',
   'units': 'ugm3',
   'displayName': None,
   'description': None},
  {'id': 98,
   'name': 'relativehumidity',
   'units': '%',
   'displayName': 'RH',
   'description': None},
  {'id': 100,
   'name': 'temperature',
   'units': 'c',
   'displayName': 'Temperature (C)',
   'description': None},
  {'id': 101,
   'name': 'so2',
   'units': 'ppb',
   'displayName': 'SO₂',
   'description': None},
  {'id': 102,
   'name': 'co',
   'units': 'ppb',
   'displayName': 'CO',
   'description': None},
  {'id': 125,
   'name': 'um003',
   'units': 'particles/cm³',
   'displayName': 'PM0.3 count',
   'description': None},
  {'id': 126,
   'name': 'um010',
   'units': 'particles/cm³',
   'displayName': 'PM1 count',
   'description': 'PM1 count'},
  {'id': 128,
   'name': 'temperature',
   'units': 'f',
   'displayName': 'Temperature (F)',
   'description': None},
  {'id': 130,
   'name': 'um025',
   'units': 'particles/cm³',
   'displayName': 'PM2.5 count',
   'description': 'PM2.5 count'},
  {'id': 132,
   'name': 'pressure',
   'units': 'mb',
   'displayName': 'Pressure',
   'description': None},
  {'id': 134,
   'name': 'humidity',
   'units': '%',
   'displayName': 'H',
   'description': None},
  {'id': 135,
   'name': 'um100',
   'units': 'particles/cm³',
   'displayName': 'PM10 count',
   'description': 'PM10 count'},
  {'id': 19840,
   'name': 'nox',
   'units': 'ppm',
   'displayName': 'NOx',
   'description': 'Nitrogen Oxides concentration'},
  {'id': 19843,
   'name': 'no',
   'units': 'µg/m³',
   'displayName': 'NO mass',
   'description': 'Nitrogen Monoxide mass concentration'},
  {'id': 19844,
   'name': 'pm4',
   'units': 'µg/m³',
   'displayName': 'PM4.0',
   'description': 'Particulate matter less than 4 micrometers in diameter mass concentration'},
  {'id': 19860,
   'name': 'pm25',
   'units': 'ppm',
   'displayName': None,
   'description': None},
  {'id': 19861,
   'name': 'bc_375',
   'units': 'ng/m³',
   'displayName': 'BC 375nm',
   'description': 'Black Carbon mass concentration 375nm '},
  {'id': 19862,
   'name': 'bc_470',
   'units': 'ng/m³',
   'displayName': 'BC 470nm',
   'description': 'Black Carbon mass concentration 470nm '},
  {'id': 19863,
   'name': 'bc_528',
   'units': 'ng/m³',
   'displayName': 'BC 528nm',
   'description': 'Black Carbon mass concentration 528nm '},
  {'id': 19864,
   'name': 'bc_625',
   'units': 'ng/m³',
   'displayName': 'BC 625nm',
   'description': 'Black Carbon mass concentration 625nm '},
  {'id': 19865,
   'name': 'bc_880',
   'units': 'ng/m³',
   'displayName': 'BC 880nm',
   'description': 'Black Carbon mass concentration 880nm '},
  {'id': 19866,
   'name': 'bc_370',
   'units': 'ng/m³',
   'displayName': 'BC 370nm',
   'description': 'Black Carbon mass concentration 375nm '}]}

# PM10

### Get all stations located in Poland that measure PM10
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "RO",   # only consider stations located in Romania
    "parameters_id": 1,   # PM10 
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm10 = df_sorted

df_top_pm10

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
50,10687,RO0175A,Prahova,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 193, 'name': 'EEA Romania'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 6311538, 'name': 'co µg/m³', 'paramete...","{'latitude': 44.9410132188863, 'longitude': 25...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.9985019638167, 44.9410132188863, 25.998501...",None,2020-04-19 21:00:00+00:00,2024-01-29 20:00:00+00:00
4,8761,BV-4,SANPETRU,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 6311503, 'name': 'co µg/m³', 'paramete...","{'latitude': 45.71807500023249, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.624194000286955, 45.71807500023249, 25.624...",None,2020-04-20 18:00:00+00:00,2026-03-16 14:00:00+00:00
20,9386,BT-1,BOTOSANI,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 6310365, 'name': 'co µg/m³', 'paramete...","{'latitude': 47.739918999753456, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.658519000154435, 47.739918999753456, 26.65...",None,2020-04-20 18:00:00+00:00,2026-03-16 14:00:00+00:00
22,9391,BV-1,BRASOV,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11438895, 'name': 'co µg/m³', 'paramet...","{'latitude': 45.637667000204765, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.630747000078838, 45.637667000204765, 25.63...",None,2020-04-20 18:00:00+00:00,2026-03-16 14:00:00+00:00
23,9393,BV-5,BRASOV,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11438896, 'name': 'co µg/m³', 'paramet...","{'latitude': 45.65159700027666, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.625652999953974, 45.65159700027666, 25.625...",None,2020-04-20 18:00:00+00:00,2026-03-16 14:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,6169175,BH-4,TETCHEA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923200, 'name': 'no2 µg/m³', 'parame...","{'latitude': 47.0437920001766, 'longitude': 22...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[22.33190600033012, 47.0437920001766, 22.33190...",None,2025-12-16 23:00:00+00:00,2026-03-16 14:00:00+00:00
295,6169176,CS-3,MOLDOVA NOUA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923206, 'name': 'pm10 µg/m³', 'param...","{'latitude': 44.72331400009336, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[21.633480999946475, 44.72331400009336, 21.633...",None,2025-12-16 23:00:00+00:00,2026-03-16 14:00:00+00:00
296,6169177,IL-2,URZICENI,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923207, 'name': 'no2 µg/m³', 'parame...","{'latitude': 44.723038999830635, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.651464000222223, 44.723038999830635, 26.65...",None,2025-12-16 23:00:00+00:00,2026-03-16 14:00:00+00:00
297,6169178,SV-2,SUCEAVA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923198, 'name': 'no2 µg/m³', 'parame...","{'latitude': 47.66882500020218, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.281403000064568, 47.66882500020218, 26.281...",None,2025-12-16 23:00:00+00:00,2026-03-16 14:00:00+00:00
298,6170672,CS-5,MOLDOVA NOUA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14934137, 'name': 'pm10 µg/m³', 'param...","{'latitude': 44.71669400027979, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[21.621639000036065, 44.71669400027979, 21.621...",None,2025-12-19 15:00:00+00:00,2026-03-16 14:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [5]:
rows = []

for _, station in df_top_pm10.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM10 behalten
        if sensor["parameter"]["id"] == 1:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm10_sensors = pd.DataFrame(rows)

df_pm10_sensors

     station_id station_name  sensor_id sensor_name
0         10687      RO0175A    6311494  pm10 µg/m³
1          8761         BV-4    8613093  pm10 µg/m³
2          9386         BT-1    6626838  pm10 µg/m³
3          9391         BV-1   10419357  pm10 µg/m³
4          9393         BV-5    8613098  pm10 µg/m³
..          ...          ...        ...         ...
294     6169175         BH-4   14923202  pm10 µg/m³
295     6169176         CS-3   14923206  pm10 µg/m³
296     6169177         IL-2   14923203  pm10 µg/m³
297     6169178         SV-2   14923201  pm10 µg/m³
298     6170672         CS-5   14934137  pm10 µg/m³

[299 rows x 4 columns]

In [6]:
sensor_ids = df_pm10_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

299

[6311494,
 8613093,
 6626838,
 10419357,
 8613098,
 6612931,
 10670605,
 8613137,
 8622671,
 8622664,
 6312569,
 1865607,
 8613106,
 6311543,
 1320338,
 1320335,
 1320341,
 1853206,
 1853209,
 6310348,
 6310360,
 6311533,
 6311523,
 6311527,
 6312581,
 6311535,
 6311509,
 1320336,
 1320334,
 1320339,
 1320337,
 1320342,
 6311521,
 6310366,
 6311529,
 8613215,
 6311505,
 8613031,
 6894327,
 6312573,
 8613165,
 8613115,
 6311504,
 6311531,
 6312561,
 6312585,
 15337886,
 8613313,
 6312566,
 10460724,
 7737912,
 10976099,
 8613045,
 6347588,
 6311510,
 6311497,
 6312570,
 6312565,
 6310374,
 6563083,
 6311532,
 1853205,
 1853201,
 15337887,
 1853204,
 6311522,
 5078790,
 6310376,
 6310352,
 5078392,
 6311539,
 6311520,
 7773636,
 7773471,
 7775905,
 7775680,
 7773771,
 7775543,
 7774635,
 7774338,
 7774742,
 7774317,
 8613069,
 8613113,
 8622692,
 7773205,
 7775928,
 7773473,
 7775536,
 8622300,
 7774758,
 7774765,
 7773649,
 8613335,
 7774304,
 7775497,
 7775246,
 8613065,
 8613154,
 8613568,
 8622716,
 8625966,
 8613336,
 7773384,
 7852817,
 8613216,
 8613339,
 8613228,
 7774297,
 8613344,
 7772841,
 8622682,
 8622680,
 8613229,
 7775626,
 8613251,
 8622247,
 7775207,
 8613484,
 8613311,
 7773677,
 7775909,
 7775093,
 7775035,
 7775737,
 7772867,
 7774254,
 7774450,
 7774053,
 7774411,
 7773391,
 7775329,
 7775918,
 7774986,
 7774564,
 7773072,
 7776028,
 7774523,
 7773107,
 7773176,
 7773871,
 7774547,
 7774918,
 10489110,
 7776508,
 7776471,
 7776614,
 10491958,
 7776604,
 7776566,
 7776577,
 8613342,
 8613341,
 8613169,
 7776516,
 8613079,
 7776603,
 8613333,
 7776472,
 7776553,
 7776525,
 7776581,
 7776495,
 7776568,
 7776546,
 7793983,
 8613043,
 10970499,
 10962243,
 8613298,
 7857706,
 7891328,
 8613080,
 7902708,
 7902709,
 7905928,
 7906254,
 8613670,
 8613583,
 8613665,
 8613372,
 8613368,
 8613379,
 8613405,
 8613378,
 8613366,
 8613394,
 8622665,
 8622229,
 8622218,
 8613588,
 8613565,
 8613360,
 8622262,
 8613111,
 8613258,
 8613119,
 8613249,
 8613241,
 8613307,
 8622668,
 8622670,
 8613618,
 8622688,
 8613516,
 8622622,
 8613672,
 8613439,
 8613632,
 8613666,
 8622712,
 8622238,
 8613541,
 8622617,
 8623580,
 8622302,
 8613446,
 8613612,
 8622648,
 8613431,
 8613626,
 8624480,
 8613698,
 8622270,
 8613451,
 8613657,
 8613420,
 8622219,
 8627102,
 8632842,
 8622223,
 8613691,
 8613681,
 8627965,
 8644665,
 8692367,
 8740162,
 8793318,
 9021123,
 9021935,
 10124835,
 10124846,
 10124809,
 10124820,
 10124815,
 10124840,
 10124859,
 10124834,
 10124822,
 10124831,
 10124810,
 10124842,
 10124862,
 10124851,
 10124816,
 10124829,
 10124839,
 10124830,
 10124832,
 10124857,
 10124838,
 10418726,
 10419359,
 10425458,
 10419659,
 10579598,
 10633435,
 10714172,
 10714171,
 10725455,
 10725452,
 10793551,
 10793873,
 10975760,
 10983945,
 10984450,
 10985449,
 10986420,
 10996699,
 11437228,
 12334932,
 12334919,
 12334929,
 12334926,
 14684263,
 14684285,
 14684287,
 14684296,
 14684278,
 14684291,
 14685852,
 14685853,
 14778665,
 15150074,
 14923202,
 14923206,
 14923203,
 14923201,
 14934137]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 6311494: Seite 1, 226 Ergebnisse
Sensor 8613093: Seite 1, 682 Ergebnisse
Sensor 6626838: Seite 1, 916 Ergebnisse
Sensor 10419357: Seite 1, 492 Ergebnisse
Sensor 8613098: Seite 1, 592 Ergebnisse
Sensor 6612931: Seite 1, 615 Ergebnisse
Sensor 10670605: Seite 1, 527 Ergebnisse
Sensor 8613137: Seite 1, 704 Ergebnisse
Sensor 8622671: Seite 1, 685 Ergebnisse
Sensor 8622664: Seite 1, 550 Ergebnisse
Sensor 6312569: Seite 1, 965 Ergebnisse
Sensor 1865607: Seite 1, 1000 Ergebnisse
Sensor 1865607: Seite 2, 295 Ergebnisse
Sensor 8613106: Seite 1, 687 Ergebnisse
Sensor 6311543: Seite 1, 200 Ergebnisse
Sensor 1320338: Seite 1, 854 Ergebnisse
Sensor 1320335: Seite 1, 843 Ergebnisse
Sensor 1320341: Seite 1, 852 Ergebnisse
Sensor 1853206: Seite 1, 189 Ergebnisse
Sensor 1853209: Seite 1, 570 Ergebnisse
Sensor 6310348: Seite 1, 222 Ergebnisse
Sensor 6310360: Seite 1, 223 Ergebnisse
Sensor 6311533: Seite 1, 224 Ergebnisse
Sensor 6311523: Seite 1, 70 Ergebnisse
Sensor 6311527: Seite 1, 118 Ergebnisse
Sensor 6312581: Seite 1, 216 Ergebnisse
Sensor 6311535: Seite 1, 29 Ergebnisse
Sensor 6311509: Seite 1, 84 Ergebnisse
Sensor 1320336: Seite 1, 850 Ergebnisse
Sensor 1320334: Seite 1, 848 Ergebnisse
Sensor 1320339: Seite 1, 830 Ergebnisse
Sensor 1320337: Seite 1, 536 Ergebnisse
Sensor 1320342: Seite 1, 825 Ergebnisse
Sensor 6311521: Seite 1, 192 Ergebnisse
Sensor 6310366: Seite 1, 80 Ergebnisse
Sensor 6311529: Seite 1, 65 Ergebnisse
Sensor 8613215: Seite 1, 705 Ergebnisse
Sensor 6311505: Seite 1, 650 Ergebnisse
Sensor 8613031: Seite 1, 705 Ergebnisse
Sensor 6894327: Seite 1, 557 Ergebnisse
Sensor 6312573: Seite 1, 777 Ergebnisse
Sensor 8613165: Seite 1, 592 Ergebnisse
Sensor 8613115: Seite 1, 705 Ergebnisse
Sensor 6311504: Seite 1, 840 Ergebnisse
Sensor 6312561: Seite 1, 532 Ergebnisse
Sensor 6312585: Seite 1, 915 Ergebnisse
Sensor 15337886: Seite 1, 30 Ergebnisse
Sensor 8613313: Seite 1, 688 Ergebnisse
Sensor 6312566: Seite 1, 928 Ergebnisse
Sensor 10460724: Seite 1, 537 Ergebnisse
Sensor 7737912: Seite 1, 703 Ergebnisse
Sensor 10976099: Seite 1, 501 Ergebnisse
Sensor 8613045: Seite 1, 705 Ergebnisse
Sensor 6347588: Seite 1, 127 Ergebnisse
Sensor 6311510: Seite 1, 226 Ergebnisse
Sensor 6311497: Seite 1, 226 Ergebnisse
Sensor 6312570: Seite 1, 225 Ergebnisse
Sensor 6312565: Seite 1, 72 Ergebnisse
Sensor 6310374: Seite 1, 219 Ergebnisse
Sensor 6563083: Seite 1, 3 Ergebnisse
Sensor 6311532: Seite 1, 14 Ergebnisse
Sensor 1853205: Seite 1, 1000 Ergebnisse
Sensor 1853205: Seite 2, 290 Ergebnisse
Sensor 1853201: Seite 1, 815 Ergebnisse
Sensor 15337887: Seite 1, 30 Ergebnisse
Sensor 1853204: Seite 1, 571 Ergebnisse
Sensor 6311522: Seite 1, 846 Ergebnisse
Sensor 5078790: Seite 1, 249 Ergebnisse
Sensor 6310376: Seite 1, 217 Ergebnisse
Sensor 6310352: Seite 1, 226 Ergebnisse
Sensor 5078392: Seite 1, 25 Ergebnisse
Sensor 6311539: Seite 1, 841 Ergebnisse
Sensor 6311520: Seite 1, 115 Ergebnisse
Sensor 7773636: Seite 1, 673 Ergebnisse
Sensor 7773471: Seite 1, 720 Ergebnisse
Sensor 7775905: Seite 1, 673 Ergebnisse
Sensor 7775680: Seite 1, 735 Ergebnisse
Sensor 7773771: Seite 1, 740 Ergebnisse
Sensor 7775543: Seite 1, 718 Ergebnisse
Sensor 7774635: Seite 1, 719 Ergebnisse
Sensor 7774338: Seite 1, 729 Ergebnisse
Sensor 7774742: Seite 1, 743 Ergebnisse
Sensor 7774317: Seite 1, 692 Ergebnisse
Sensor 8613069: Seite 1, 516 Ergebnisse
Sensor 8613113: Seite 1, 695 Ergebnisse
Sensor 8622692: Seite 1, 476 Ergebnisse
Sensor 7773205: Seite 1, 744 Ergebnisse
Sensor 7775928: Seite 1, 736 Ergebnisse
Sensor 7773473: Seite 1, 691 Ergebnisse
Sensor 7775536: Seite 1, 695 Ergebnisse
Sensor 8622300: Seite 1, 625 Ergebnisse
Sensor 7774758: Seite 1, 706 Ergebnisse
Sensor 7774765: Seite 1, 708 Ergebnisse
Sensor 7773649: Seite 1, 667 Ergebnisse
Sensor 8613335: Seite 1, 679 Ergebnisse
Sensor 7774304: Seite 1, 737 Ergebnisse
Sensor 7775497: Seite 1, 637 Ergebnisse
Sensor 7775246: Seite 1, 554 Ergebnisse
Sensor 8613065: Seite 1, 633 Ergebnisse
Sensor 8613154: Seite 1, 695 Ergebnisse
Sensor 8613568: Seite 1, 695 Ergebnisse
Sensor 8622716: Seite 1, 513 Ergebnisse
Sensor 8625966: Seite 1, 561 Ergebnisse
Sensor 8613336: Seite 1, 673 Ergebnisse
Sensor 7773384: Seite 1, 746 Ergebnisse
Sensor 7852817: Seite 1, 670 Ergebnisse
Sensor 8613216: Seite 1, 701 Ergebnisse
Sensor 8613339: Seite 1, 698 Ergebnisse
Sensor 8613228: Seite 1, 619 Ergebnisse
Sensor 7774297: Seite 1, 650 Ergebnisse
Sensor 8613344: Seite 1, 551 Ergebnisse
Sensor 7772841: Seite 1, 634 Ergebnisse
Sensor 8622682: Seite 1, 622 Ergebnisse
Sensor 8622680: Seite 1, 560 Ergebnisse
Sensor 8613229: Seite 1, 675 Ergebnisse
Sensor 7775626: Seite 1, 739 Ergebnisse
Sensor 8613251: Seite 1, 589 Ergebnisse
Sensor 8622247: Seite 1, 687 Ergebnisse
Sensor 7775207: Seite 1, 740 Ergebnisse
Sensor 8613484: Seite 1, 682 Ergebnisse
Sensor 8613311: Seite 1, 674 Ergebnisse
Sensor 7773677: Seite 1, 605 Ergebnisse
Sensor 7775909: Seite 1, 399 Ergebnisse
Sensor 7775093: Seite 1, 167 Ergebnisse
Sensor 7775035: Seite 1, 174 Ergebnisse
Sensor 7775737: Seite 1, 129 Ergebnisse
Sensor 7772867: Seite 1, 129 Ergebnisse
Sensor 7774254: Seite 1, 130 Ergebnisse
Sensor 7774450: Seite 1, 172 Ergebnisse
Sensor 7774053: Seite 1, 167 Ergebnisse
Sensor 7774411: Seite 1, 129 Ergebnisse
Sensor 7773391: Seite 1, 174 Ergebnisse
Sensor 7775329: Seite 1, 174 Ergebnisse
Sensor 7775918: Seite 1, 173 Ergebnisse
Sensor 7774986: Seite 1, 126 Ergebnisse
Sensor 7774564: Seite 1, 131 Ergebnisse
Sensor 7773072: Seite 1, 173 Ergebnisse
Sensor 7776028: Seite 1, 171 Ergebnisse
Sensor 7774523: Seite 1, 170 Ergebnisse
Sensor 7773107: Seite 1, 174 Ergebnisse
Sensor 7773176: Seite 1, 171 Ergebnisse
Sensor 7773871: Seite 1, 158 Ergebnisse
Sensor 7774547: Seite 1, 174 Ergebnisse
Sensor 7774918: Seite 1, 170 Ergebnisse
Sensor 10489110: Seite 1, 477 Ergebnisse
Sensor 7776508: Seite 1, 717 Ergebnisse
Sensor 7776471: Seite 1, 711 Ergebnisse
Sensor 7776614: Seite 1, 728 Ergebnisse
Sensor 10491958: Seite 1, 476 Ergebnisse
Sensor 7776604: Seite 1, 711 Ergebnisse
Sensor 7776566: Seite 1, 570 Ergebnisse
Sensor 7776577: Seite 1, 648 Ergebnisse
Sensor 8613342: Seite 1, 688 Ergebnisse
Sensor 8613341: Seite 1, 513 Ergebnisse
Sensor 8613169: Seite 1, 561 Ergebnisse
Sensor 7776516: Seite 1, 683 Ergebnisse
Sensor 8613079: Seite 1, 692 Ergebnisse
Sensor 7776603: Seite 1, 719 Ergebnisse
Sensor 8613333: Seite 1, 630 Ergebnisse
Sensor 7776472: Seite 1, 174 Ergebnisse
Sensor 7776553: Seite 1, 172 Ergebnisse
Sensor 7776525: Seite 1, 127 Ergebnisse
Sensor 7776581: Seite 1, 170 Ergebnisse
Sensor 7776495: Seite 1, 174 Ergebnisse
Sensor 7776568: Seite 1, 173 Ergebnisse
Sensor 7776546: Seite 1, 157 Ergebnisse
Sensor 7793983: Seite 1, 727 Ergebnisse
Sensor 8613043: Seite 1, 690 Ergebnisse
Sensor 10970499: Seite 1, 499 Ergebnisse
Sensor 10962243: Seite 1, 500 Ergebnisse
Sensor 8613298: Seite 1, 705 Ergebnisse
Sensor 7857706: Seite 1, 717 Ergebnisse
Sensor 7891328: Seite 1, 389 Ergebnisse
Sensor 8613080: Seite 1, 566 Ergebnisse
Sensor 7902708: Seite 1, 373 Ergebnisse
Sensor 7902709: Seite 1, 615 Ergebnisse
Sensor 7905928: Seite 1, 613 Ergebnisse
Sensor 7906254: Seite 1, 619 Ergebnisse
Sensor 8613670: Seite 1, 678 Ergebnisse
Sensor 8613583: Seite 1, 682 Ergebnisse
Sensor 8613665: Seite 1, 697 Ergebnisse
Sensor 8613372: Seite 1, 678 Ergebnisse
Sensor 8613368: Seite 1, 697 Ergebnisse
Sensor 8613379: Seite 1, 693 Ergebnisse
Sensor 8613405: Seite 1, 699 Ergebnisse
Sensor 8613378: Seite 1, 695 Ergebnisse
Sensor 8613366: Seite 1, 691 Ergebnisse
Sensor 8613394: Seite 1, 698 Ergebnisse
Sensor 8622665: Seite 1, 578 Ergebnisse
Sensor 8622229: Seite 1, 693 Ergebnisse
Sensor 8622218: Seite 1, 696 Ergebnisse
Sensor 8613588: Seite 1, 670 Ergebnisse
Sensor 8613565: Seite 1, 694 Ergebnisse
Sensor 8613360: Seite 1, 693 Ergebnisse
Sensor 8622262: Seite 1, 688 Ergebnisse
Sensor 8613111: Seite 1, 568 Ergebnisse
Sensor 8613258: Seite 1, 675 Ergebnisse
Sensor 8613119: Seite 1, 660 Ergebnisse
Sensor 8613249: Seite 1, 495 Ergebnisse
Sensor 8613241: Seite 1, 613 Ergebnisse
Sensor 8613307: Seite 1, 643 Ergebnisse
Sensor 8622668: Seite 1, 683 Ergebnisse
Sensor 8622670: Seite 1, 677 Ergebnisse
Sensor 8613618: Seite 1, 588 Ergebnisse
Sensor 8622688: Seite 1, 357 Ergebnisse
Sensor 8613516: Seite 1, 127 Ergebnisse
Sensor 8622622: Seite 1, 131 Ergebnisse
Sensor 8613672: Seite 1, 125 Ergebnisse
Sensor 8613439: Seite 1, 517 Ergebnisse
Sensor 8613632: Seite 1, 619 Ergebnisse
Sensor 8613666: Seite 1, 699 Ergebnisse
Sensor 8622712: Seite 1, 686 Ergebnisse
Sensor 8622238: Seite 1, 687 Ergebnisse
Sensor 8613541: Seite 1, 697 Ergebnisse
Sensor 8622617: Seite 1, 128 Ergebnisse
Sensor 8623580: Seite 1, 128 Ergebnisse
Sensor 8622302: Seite 1, 129 Ergebnisse
Sensor 8613446: Seite 1, 128 Ergebnisse
Sensor 8613612: Seite 1, 129 Ergebnisse
Sensor 8622648: Seite 1, 129 Ergebnisse
Sensor 8613431: Seite 1, 693 Ergebnisse
Sensor 8613626: Seite 1, 618 Ergebnisse
Sensor 8624480: Seite 1, 549 Ergebnisse
Sensor 8613698: Seite 1, 593 Ergebnisse
Sensor 8622270: Seite 1, 129 Ergebnisse
Sensor 8613451: Seite 1, 122 Ergebnisse
Sensor 8613657: Seite 1, 681 Ergebnisse
Sensor 8613420: Seite 1, 667 Ergebnisse
Sensor 8622219: Seite 1, 677 Ergebnisse
Sensor 8627102: Seite 1, 694 Ergebnisse
Sensor 8632842: Seite 1, 634 Ergebnisse
Sensor 8622223: Seite 1, 127 Ergebnisse
Sensor 8613691: Seite 1, 127 Ergebnisse
Sensor 8613681: Seite 1, 128 Ergebnisse
Sensor 8627965: Seite 1, 560 Ergebnisse
Sensor 8644665: Seite 1, 562 Ergebnisse
Sensor 8692367: Seite 1, 560 Ergebnisse
Sensor 8740162: Seite 1, 694 Ergebnisse
Sensor 8793318: Seite 1, 11 Ergebnisse
Sensor 9021123: Seite 1, 657 Ergebnisse
Sensor 9021935: Seite 1, 664 Ergebnisse
Sensor 10124835: Seite 1, 553 Ergebnisse
Sensor 10124846: Seite 1, 553 Ergebnisse
Sensor 10124809: Seite 1, 575 Ergebnisse
Sensor 10124820: Seite 1, 575 Ergebnisse
Sensor 10124815: Seite 1, 574 Ergebnisse
Sensor 10124840: Seite 1, 575 Ergebnisse
Sensor 10124859: Seite 1, 575 Ergebnisse
Sensor 10124834: Seite 1, 575 Ergebnisse
Sensor 10124822: Seite 1, 575 Ergebnisse
Sensor 10124831: Seite 1, 575 Ergebnisse
Sensor 10124810: Seite 1, 575 Ergebnisse
Sensor 10124842: Seite 1, 575 Ergebnisse
Sensor 10124862: Seite 1, 575 Ergebnisse
Sensor 10124851: Seite 1, 575 Ergebnisse
Sensor 10124816: Seite 1, 575 Ergebnisse
Sensor 10124829: Seite 1, 575 Ergebnisse
Sensor 10124839: Seite 1, 575 Ergebnisse
Sensor 10124830: Seite 1, 575 Ergebnisse
Sensor 10124832: Seite 1, 575 Ergebnisse
Sensor 10124857: Seite 1, 574 Ergebnisse
Sensor 10124838: Seite 1, 554 Ergebnisse
Sensor 10418726: Seite 1, 547 Ergebnisse
Sensor 10419359: Seite 1, 546 Ergebnisse
Sensor 10425458: Seite 1, 550 Ergebnisse
Sensor 10419659: Seite 1, 549 Ergebnisse
Sensor 10579598: Seite 1, 482 Ergebnisse
Sensor 10633435: Seite 1, 475 Ergebnisse
Sensor 10714172: Seite 1, 522 Ergebnisse
Sensor 10714171: Seite 1, 404 Ergebnisse
Sensor 10725455: Seite 1, 522 Ergebnisse
Sensor 10725452: Seite 1, 521 Ergebnisse
Sensor 10793551: Seite 1, 517 Ergebnisse
Sensor 10793873: Seite 1, 508 Ergebnisse
Sensor 10975760: Seite 1, 501 Ergebnisse
Sensor 10983945: Seite 1, 501 Ergebnisse
Sensor 10984450: Seite 1, 499 Ergebnisse
Sensor 10985449: Seite 1, 489 Ergebnisse
Sensor 10986420: Seite 1, 481 Ergebnisse
Sensor 10996699: Seite 1, 495 Ergebnisse
Sensor 11437228: Seite 1, 438 Ergebnisse
Sensor 12334932: Seite 1, 350 Ergebnisse
Sensor 12334919: Seite 1, 366 Ergebnisse
Sensor 12334929: Seite 1, 367 Ergebnisse
Sensor 12334926: Seite 1, 350 Ergebnisse
Sensor 14684263: Seite 1, 104 Ergebnisse
Sensor 14684285: Seite 1, 93 Ergebnisse
Sensor 14684287: Seite 1, 102 Ergebnisse
Sensor 14684296: Seite 1, 60 Ergebnisse
Sensor 14684278: Seite 1, 104 Ergebnisse
Sensor 14684291: Seite 1, 103 Ergebnisse
Sensor 14685852: Seite 1, 104 Ergebnisse
Sensor 14685853: Seite 1, 104 Ergebnisse
Sensor 14778665: Seite 1, 89 Ergebnisse
Sensor 15150074: Seite 1, 50 Ergebnisse
Sensor 14923202: Seite 1, 74 Ergebnisse
Sensor 14923206: Seite 1, 74 Ergebnisse
Sensor 14923203: Seite 1, 74 Ergebnisse
Sensor 14923201: Seite 1, 74 Ergebnisse
Sensor 14934137: Seite 1, 72 Ergebnisse
146356

[{'date': '2023-06-14', 'value': 21.2542730525},
 {'date': '2023-06-15', 'value': 15.392550999166668},
 {'date': '2023-06-16', 'value': 14.453805899166667},
 {'date': '2023-06-17', 'value': 19.728129509583336},
 {'date': '2023-06-18', 'value': 12.424985166249996},
 {'date': '2023-06-19', 'value': 13.362872602083334},
 {'date': '2023-06-20', 'value': 14.05094199708333},
 {'date': '2023-06-21', 'value': 19.223677145833335},
 {'date': '2023-06-22', 'value': 24.445573445416667},
 {'date': '2023-06-23', 'value': 24.92656491375},
 {'date': '2023-06-24', 'value': 28.489642329166667},
 {'date': '2023-06-25', 'value': 15.932854891250003},
 {'date': '2023-06-26', 'value': 13.104422168333334},
 {'date': '2023-06-27', 'value': 14.450756985},
 {'date': '2023-06-28', 'value': 15.071464634166665},
 {'date': '2023-06-29', 'value': 11.748269687499999},
 {'date': '2023-06-30', 'value': 11.072481939166664},
 {'date': '2023-07-01', 'value': 15.167437514999998},
 {'date': '2023-07-02', 'value': 18.485005927916667},
 {'date': '2023-07-03', 'value': 25.76803201666667},
 {'date': '2023-07-04', 'value': 22.692793442916667},
 {'date': '2023-07-05', 'value': 15.583809188333332},
 {'date': '2023-07-06', 'value': 18.41758071708334},
 {'date': '2023-07-07', 'value': 14.522652296666669},
 {'date': '2023-07-08', 'value': 9.254055435833335},
 {'date': '2023-07-09', 'value': 12.551846838333333},
 {'date': '2023-07-10', 'value': 19.695624780416665},
 {'date': '2023-07-11', 'value': 25.452504427500003},
 {'date': '2023-07-12', 'value': 23.264165178749995},
 {'date': '2023-07-13', 'value': 25.88279299083334},
 {'date': '2023-07-14', 'value': 17.47235408928572},
 {'date': '2023-07-17', 'value': 23.45263216727273},
 {'date': '2023-07-18', 'value': 20.070684058333335},
 {'date': '2023-07-19', 'value': 3.2978776980952382},
 {'date': '2023-07-20', 'value': 21.272719677083334},
 {'date': '2023-07-21', 'value': 17.204226305416668},
 {'date': '2023-07-22', 'value': 7.274232287499999},
 {'date': '2023-07-23', 'value': 10.386058626086957},
 {'date': '2023-07-24', 'value': 14.423751005833333},
 {'date': '2023-07-25', 'value': 23.210169535454543},
 {'date': '2023-07-26', 'value': 23.128397859999996},
 {'date': '2023-07-27', 'value': 10.733780348181817},
 {'date': '2023-07-28', 'value': 9.137720515217392},
 {'date': '2023-07-29', 'value': 10.3847582375},
 {'date': '2023-07-30', 'value': 14.770227959565219},
 {'date': '2023-07-31', 'value': 19.992924979999998},
 {'date': '2023-08-01', 'value': 13.309355652916665},
 {'date': '2023-08-02', 'value': 13.672655520416669},
 {'date': '2023-08-03', 'value': 13.798802952352942},
 {'date': '2023-08-04', 'value': 24.716483282500008},
 {'date': '2023-08-05', 'value': 15.695618787727273},
 {'date': '2023-08-06', 'value': 22.239704491363632},
 {'date': '2023-08-07', 'value': 4.882693622500001},
 {'date': '2023-08-08', 'value': 5.215565298181819},
 {'date': '2023-08-09', 'value': 5.477176131666667},
 {'date': '2023-08-10', 'value': 7.359188005},
 {'date': '2023-08-11', 'value': 8.577237490869564},
 {'date': '2023-08-12', 'value': 15.219891753749996},
 {'date': '2023-08-13', 'value': 13.349843954583333},
 {'date': '2023-08-14', 'value': 14.611488375000002},
 {'date': '2023-08-15', 'value': 20.29998048260869},
 {'date': '2023-08-16', 'value': 23.949559600833336},
 {'date': '2023-08-17', 'value': 18.699434832916662},
 {'date': '2023-08-18', 'value': 20.309468988636365},
 {'date': '2023-08-19', 'value': 20.823586876315794},
 {'date': '2023-08-20', 'value': 16.348114145909086},
 {'date': '2023-08-21', 'value': 17.581950518571425},
 {'date': '2023-08-22', 'value': 23.51439217636364},
 {'date': '2023-08-23', 'value': 19.90089216782609},
 {'date': '2023-08-24', 'value': 7.928098799473684},
 {'date': '2023-08-25', 'value': 14.761024848571427},
 {'date': '2023-08-28', 'value': 15.631460794285712},
 {'date': '2023-08-29', 'value': 17.869933737826084},
 {'date': '2023-08-30', 'value': 18.642852860869567},
 {'date': '2023-08-31', 'value': 11.600291877499998},
 {'date': '2023-09-01', 'value': 8.392164893478263},
 {'date': '2023-09-02', 'value': 9.442002278749998},
 {'date': '2023-09-03', 'value': 5.990131727083334},
 {'date': '2023-09-04', 'value': 7.777307541363635},
 {'date': '2023-09-05', 'value': 8.62246857583333},
 {'date': '2023-09-06', 'value': 7.729806591249997},
 {'date': '2023-09-07', 'value': 4.537862234210525},
 {'date': '2023-09-08', 'value': 10.735605908750001},
 {'date': '2023-09-09', 'value': 13.65909741166667},
 {'date': '2023-09-10', 'value': 14.395268820909092},
 {'date': '2023-09-11', 'value': 16.25993081},
 {'date': '2023-09-12', 'value': 20.07883748},
 {'date': '2023-09-13', 'value': 22.505952853333326},
 {'date': '2023-09-14', 'value': 21.923911964583336},
 {'date': '2023-09-15', 'value': 22.935761967727274},
 {'date': '2023-09-16', 'value': 20.063155363333333},
 {'date': '2023-09-17', 'value': 18.778336342916663},
 {'date': '2023-09-18', 'value': 18.541119685},
 {'date': '2023-09-19', 'value': 21.194833612608697},
 {'date': '2023-09-20', 'value': 20.144625941739132},
 {'date': '2023-09-21', 'value': 18.43155691833333},
 {'date': '2023-09-22', 'value': 19.67413776291667},
 {'date': '2023-09-23', 'value': 21.473641705909092},
 {'date': '2023-09-24', 'value': 15.865752987500004},
 {'date': '2023-09-25', 'value': 17.169042145833334},
 {'date': '2023-09-26', 'value': 16.75336750826087},
 {'date': '2023-09-27', 'value': 18.21955007391304},
 {'date': '2023-09-28', 'value': 18.23419556},
 {'date': '2023-09-29', 'value': 18.021876349499998},
 {'date': '2023-09-30', 'value': 22.249569156363638},
 {'date': '2023-10-01', 'value': 23.671586684545456},
 {'date': '2023-10-02', 'value': 17.82411812045455},
 {'date': '2023-10-03', 'value': 21.70170023608696},
 {'date': '2023-10-04', 'value': 23.96283287695652},
 {'date': '2023-10-05', 'value': 18.547479858695652},
 {'date': '2023-10-06', 'value': 17.79680237173913},
 {'date': '2023-10-07', 'value': 17.402136992916667},
 {'date': '2023-10-08', 'value': 13.035086386521737},
 {'date': '2023-10-09', 'value': 12.835905637391305},
 {'date': '2023-10-10', 'value': 16.952523780000003},
 {'date': '2023-10-11', 'value': 20.05205681647059},
 {'date': '2023-10-12', 'value': 24.84420246636364},
 {'date': '2023-10-13', 'value': 26.751284883636366},
 {'date': '2023-10-14', 'value': 26.08531144782609},
 {'date': '2023-10-15', 'value': 23.97829161681818},
 {'date': '2023-10-16', 'value': 10.936101961363638},
 {'date': '2023-10-17', 'value': 20.571777309090905},
 {'date': '2023-10-18', 'value': 21.56460002136364},
 {'date': '2023-10-19', 'value': 27.92564210086956},
 {'date': '2023-10-20', 'value': 23.808212892173916},
 {'date': '2023-10-21', 'value': 29.621988746521737},
 {'date': '2023-10-22', 'value': 17.57295939454545},
 {'date': '2023-10-23', 'value': 18.72944908318182},
 {'date': '2023-10-24', 'value': 15.447670995333334},
 {'date': '2023-10-25', 'value': 20.12112278409091},
 {'date': '2023-10-26', 'value': 22.743452422916665},
 {'date': '2023-10-27', 'value': 20.879418776666665},
 {'date': '2023-10-28', 'value': 10.576201572083335},
 {'date': '2023-10-29', 'value': 13.405758017500006},
 {'date': '2023-10-30', 'value': 21.08942019541667},
 {'date': '2023-10-31', 'value': 26.416558658750002},
 {'date': '2023-11-01', 'value': 16.81203670958333},
 {'date': '2023-11-02', 'value': 68.320008635},
 {'date': '2023-11-03', 'value': 29.03579967083333},
 {'date': '2023-11-04', 'value': 32.30271264875001},
 {'date': '2023-11-05', 'value': 11.561466710416665},
 {'date': '2023-11-06', 'value': 10.180948258333332},
 {'date': '2023-11-07', 'value': 22.462773388749998},
 {'date': '2023-11-08', 'value': 21.76899121083333},
 {'date': '2023-11-09', 'value': 24.566554635652174},
 {'date': '2023-11-10', 'value': 34.90170805708334},
 {'date': '2023-11-11', 'value': 31.170241084166666},
 {'date': '2023-11-12', 'value': 10.626018449583333},
 {'date': '2023-11-13', 'value': 28.994122686666667},
 {'date': '2023-11-14', 'value': 36.00264688},
 {'date': '2023-11-15', 'value': 49.23304800666666},
 {'date': '2023-11-16', 'value': 23.948250666666667},
 {'date': '2023-11-17', 'value': 48.51098795000001},
 {'date': '2023-11-18', 'value': 29.997850891250007},
 {'date': '2023-11-19', 'value': 21.841564140416665},
 {'date': '2023-11-20', 'value': 60.69435284916668},
 {'date': '2023-11-21', 'value': 45.135604120833335},
 {'date': '2023-11-22', 'value': 24.41892989333334},
 {'date': '2023-11-23', 'value': 29.399247196666664},
 {'date': '2023-11-24', 'value': 28.463242154583345},
 {'date': '2023-11-25', 'value': 22.026558465416667},
 {'date': '2023-11-26', 'value': 11.66521974125},
 {'date': '2023-11-27', 'value': 17.70889752458333},
 {'date': '2023-11-28', 'value': 39.04071784625},
 {'date': '2023-11-29', 'value': 25.240693020833337},
 {'date': '2023-11-30', 'value': 47.35392744333333},
 {'date': '2023-12-01', 'value': 31.175225352083334},
 {'date': '2023-12-02', 'value': 36.416991317916676},
 {'date': '2023-12-03', 'value': 25.52347827833334},
 {'date': '2023-12-04', 'value': 27.812360396666666},
 {'date': '2023-12-05', 'value': 38.86935513625001},
 {'date': '2023-12-06', 'value': 22.19324125208334},
 {'date': '2023-12-07', 'value': 25.84411333708334},
 {'date': '2023-12-08', 'value': 38.662616058333334},
 {'date': '2023-12-09', 'value': 47.23671270041667},
 {'date': '2023-12-10', 'value': 45.06146284291666},
 {'date': '2023-12-11', 'value': 48.27740379333333},
 {'date': '2023-12-12', 'value': 49.93123625083334},
 {'date': '2023-12-13', 'value': 39.71267312291668},
 {'date': '2023-12-14', 'value': 40.59042039708333},
 {'date': '2023-12-15', 'value': 23.552464404583336},
 {'date': '2023-12-16', 'value': 25.737304945833326},
 {'date': '2023-12-17', 'value': 33.39486097708333},
 {'date': '2023-12-18', 'value': 51.14268479375},
 {'date': '2023-12-19', 'value': 39.488009631666664},
 {'date': '2023-12-20', 'value': 41.03775436625},
 {'date': '2023-12-21', 'value': 62.40530085749999},
 {'date': '2023-12-22', 'value': 34.879326249166674},
 {'date': '2023-12-23', 'value': 10.453450617083332},
 {'date': '2023-12-24', 'value': 27.19625147875},
 {'date': '2023-12-25', 'value': 20.238629030416664},
 {'date': '2023-12-26', 'value': 22.992916597916665},
 {'date': '2023-12-27', 'value': 18.667849539583333},
 {'date': '2023-12-28', 'value': 27.600159259583336},
 {'date': '2023-12-29', 'value': 34.59727090041667},
 {'date': '2023-12-30', 'value': 29.687664095833327},
 {'date': '2023-12-31', 'value': 31.31596544708333},
 {'date': '2024-01-01', 'value': 31.111830052916662},
 {'date': '2024-01-02', 'value': 35.48042723708334},
 {'date': '2024-01-03', 'value': 24.60732583625},
 {'date': '2024-01-04', 'value': 25.517879844583337},
 {'date': '2024-01-05', 'value': 16.7041717475},
 {'date': '2024-01-06', 'value': 36.19315388333333},
 {'date': '2024-01-07', 'value': 20.652458276666664},
 {'date': '2024-01-08', 'value': 13.396629005833333},
 {'date': '2024-01-09', 'value': 21.27082518041667},
 {'date': '2024-01-10', 'value': 42.9504755625},
 {'date': '2024-01-11', 'value': 35.80693380041667},
 {'date': '2024-01-12', 'value': 30.68919255166666},
 {'date': '2024-01-13', 'value': 25.504780184999998},
 {'date': '2024-01-14', 'value': 48.16301293},
 {'date': '2024-01-15', 'value': 39.70875502458333},
 {'date': '2024-01-16', 'value': 17.407321664999998},
 {'date': '2024-01-17', 'value': 21.308089918750003},
 {'date': '2024-01-18', 'value': 33.685691667916664},
 {'date': '2024-01-19', 'value': 25.71618242166667},
 {'date': '2024-01-20', 'value': 11.843110128333334},
 {'date': '2024-01-21', 'value': 32.69154189458333},
 {'date': '2024-01-22', 'value': 46.921758610000005},
 {'date': '2024-01-23', 'value': 62.42067728875},
 {'date': '2024-01-24', 'value': 55.79707810624999},
 {'date': '2024-01-25', 'value': 34.58606855041667},
 {'date': '2024-01-26', 'value': 10.197092936666666},
 {'date': '2024-01-27', 'value': 22.359278921249995},
 {'date': '2024-01-28', 'value': 14.980579730833334},
 {'date': '2024-01-29', 'value': 30.091603707272725},
 {'date': '2024-03-18', 'value': -1.0},
 {'date': '2024-03-23', 'value': -1.0},
 {'date': '2024-03-24', 'value': -1.0},
 {'date': '2024-03-25', 'value': -1.0},
 {'date': '2024-03-26', 'value': -1.0},
 {'date': '2024-03-27', 'value': -1.0},
 {'date': '2024-03-28', 'value': -1.0},
 {'date': '2024-03-29', 'value': -1.0},
 {'date': '2024-03-30', 'value': -1.0},
 {'date': '2024-03-31', 'value': -1.0},
 {'date': '2024-04-01', 'value': -1.0},
 {'date': '2024-04-02', 'value': -1.0},
 {'date': '2024-04-03', 'value': -1.0},
 {'date': '2024-04-04', 'value': -1.0},
 {'date': '2024-04-05', 'value': -1.0},
 {'date': '2024-04-06', 'value': -1.0},
 {'date': '2024-04-07', 'value': -1.0},
 {'date': '2024-04-08', 'value': -1.0},
 {'date': '2024-04-09', 'value': -1.0},
 {'date': '2024-04-10', 'value': -1.0},
 {'date': '2024-04-11', 'value': -1.0},
 {'date': '2024-04-12', 'value': -1.0},
 {'date': '2024-04-13', 'value': -1.0},
 {'date': '2024-04-14', 'value': -1.0},
 {'date': '2024-04-15', 'value': -1.0},
 {'date': '2024-04-16', 'value': -1.0},
 {'date': '2024-04-17', 'value': -1.0},
 {'date': '2024-04-18', 'value': -1.0},
 {'date': '2024-04-19', 'value': -1.0},
 {'date': '2024-04-20', 'value': -1.0},
 {'date': '2024-04-21', 'value': -1.0},
 {'date': '2024-04-22', 'value': -1.0},
 {'date': '2024-04-23', 'value': -1.0},
 {'date': '2024-04-24', 'value': -1.0},
 {'date': '2024-04-25', 'value': -1.0},
 {'date': '2024-04-26', 'value': -1.0},
 {'date': '2024-04-27', 'value': -1.0},
 {'date': '2024-04-28', 'value': -1.0},
 {'date': '2024-04-29', 'value': -1.0},
 {'date': '2024-04-30', 'value': -1.0},
 {'date': '2024-05-01', 'value': -1.0},
 {'date': '2024-05-02', 'value': -1.0},
 {'date': '2024-05-03', 'value': -1.0},
 {'date': '2024-05-04', 'value': -1.0},
 {'date': '2024-05-05', 'value': -1.0},
 {'date': '2024-05-06', 'value': -1.0},
 {'date': '2024-05-07', 'value': -1.0},
 {'date': '2024-05-08', 'value': -1.0},
 {'date': '2024-05-09', 'value': -1.0},
 {'date': '2024-05-10', 'value': -1.0},
 {'date': '2024-05-11', 'value': -1.0},
 {'date': '2024-05-12', 'value': -1.0},
 {'date': '2024-05-13', 'value': -1.0},
 {'date': '2024-05-14', 'value': -1.0},
 {'date': '2024-05-15', 'value': -1.0},
 {'date': '2024-05-16', 'value': -1.0},
 {'date': '2024-05-17', 'value': -1.0},
 {'date': '2024-05-18', 'value': -1.0},
 {'date': '2024-05-19', 'value': -1.0},
 {'date': '2024-05-20', 'value': -1.0},
 {'date': '2024-05-21', 'value': -1.0},
 {'date': '2024-05-22', 'value': -1.0},
 {'date': '2024-05-23', 'value': -1.0},
 {'date': '2024-05-24', 'value': -1.0},
 {'date': '2024-05-25', 'value': -1.0},
 {'date': '2024-05-26', 'value': -1.0},
 {'date': '2024-05-27', 'value': -1.0},
 {'date': '2024-05-28', 'value': -1.0},
 {'date': '2024-05-29', 'value': -1.0},
 {'date': '2024-05-30', 'value': -1.0},
 {'date': '2024-05-31', 'value': -1.0},
 {'date': '2024-06-01', 'value': -1.0},
 {'date': '2024-06-02', 'value': -1.0},
 {'date': '2024-06-03', 'value': -1.0},
 {'date': '2024-06-04', 'value': -1.0},
 {'date': '2024-06-05', 'value': -1.0},
 {'date': '2024-06-06', 'value': -1.0},
 {'date': '2024-06-07', 'value': -1.0},
 {'date': '2024-06-08', 'value': -1.0},
 {'date': '2024-06-09', 'value': -1.0},
 {'date': '2024-06-10', 'value': -1.0},
 {'date': '2024-06-11', 'value': -1.0},
 {'date': '2024-06-12', 'value': -1.0},
 {'date': '2024-06-13', 'value': -1.0},
 {'date': '2024-06-14', 'value': -1.0},
 {'date': '2024-06-15', 'value': -1.0},
 {'date': '2024-06-16', 'value': -1.0},
 {'date': '2024-06-17', 'value': -1.0},
 {'date': '2024-06-18', 'value': -1.0},
 {'date': '2024-06-19', 'value': -1.0},
 {'date': '2024-06-20', 'value': -1.0},
 {'date': '2024-06-21', 'value': -1.0},
 {'date': '2024-06-22', 'value': -1.0},
 {'date': '2024-06-23', 'value': -1.0},
 {'date': '2024-06-24', 'value': -1.0},
 {'date': '2024-06-25', 'value': -1.0},
 {'date': '2024-06-26', 'value': -1.0},
 {'date': '2024-06-27', 'value': -1.0},
 {'date': '2024-06-28', 'value': -1.0},
 {'date': '2024-06-29', 'value': -1.0},
 {'date': '2024-06-30', 'value': -1.0},
 {'date': '2024-07-01', 'value': -1.0},
 {'date': '2024-07-02', 'value': -1.0},
 {'date': '2024-07-03', 'value': -1.0},
 {'date': '2024-07-04', 'value': -1.0},
 {'date': '2024-07-05', 'value': -1.0},
 {'date': '2024-07-06', 'value': -1.0},
 {'date': '2024-07-07', 'value': -1.0},
 {'date': '2024-07-08', 'value': -1.0},
 {'date': '2024-07-09', 'value': -1.0},
 {'date': '2024-07-10', 'value': -1.0},
 {'date': '2024-07-11', 'value': -1.0},
 {'date': '2024-07-12', 'value': -1.0},
 {'date': '2024-07-13', 'value': -1.0},
 {'date': '2024-07-14', 'value': -1.0},
 {'date': '2024-07-15', 'value': -1.0},
 {'date': '2024-07-16', 'value': -1.0},
 {'date': '2024-07-17', 'value': -1.0},
 {'date': '2024-07-18', 'value': -1.0},
 {'date': '2024-07-19', 'value': -1.0},
 {'date': '2024-07-20', 'value': -1.0},
 {'date': '2024-07-21', 'value': -1.0},
 {'date': '2024-07-22', 'value': -1.0},
 {'date': '2024-07-23', 'value': -1.0},
 {'date': '2024-07-24', 'value': -1.0},
 {'date': '2024-07-25', 'value': -1.0},
 {'date': '2024-07-26', 'value': 1.3003320624999999},
 {'date': '2024-07-27', 'value': 6.1010873375},
 {'date': '2024-07-28', 'value': 6.317250724999998},
 {'date': '2024-07-29', 'value': 7.009975183333334},
 {'date': '2024-07-30', 'value': 2.298711041666667},
 {'date': '2024-07-31', 'value': 7.330636029166666},
 {'date': '2024-08-01', 'value': 12.133404004761905},
 {'date': '2024-08-02', 'value': 14.0047954875},
 {'date': '2024-08-03', 'value': 12.847266137500002},
 {'date': '2024-08-04', 'value': 3.784081250000001},
 {'date': '2024-08-05', 'value': 4.8754471125},
 {'date': '2024-08-06', 'value': 3.566645395833333},
 {'date': '2024-08-07', 'value': 4.071634425},
 {'date': '2024-08-08', 'value': 8.612811683333332},
 {'date': '2024-08-09', 'value': 15.067526345833334},
 {'date': '2024-08-10', 'value': 21.694458116666667},
 {'date': '2024-08-11', 'value': 12.913336537499996},
 {'date': '2024-08-12', 'value': 10.374821195833333},
 {'date': '2024-08-13', 'value': 13.165873374999997},
 {'date': '2024-08-14', 'value': 11.218242429166667},
 {'date': '2024-08-15', 'value': 26.5598888},
 {'date': '2024-08-19', 'value': 7.910674699999999},
 {'date': '2024-08-23', 'value': 8.288822683333333},
 {'date': '2024-08-24', 'value': 13.926539324999998},
 {'date': '2024-08-25', 'value': 10.588139120833334},
 {'date': '2024-08-26', 'value': 18.972511893333337},
 {'date': '2024-08-27', 'value': 17.2464962},
 {'date': '2024-08-28', 'value': 16.0835648},
 {'date': '2024-08-29', 'value': 27.8969345},
 {'date': '2024-08-30', 'value': 18.205486271428573},
 {'date': '2024-08-31', 'value': 22.566405057142855},
 {'date': '2024-09-01', 'value': 18.699018618181817},
 {'date': '2024-09-02', 'value': 17.042148579999996},
 {'date': '2024-09-03', 'value': 27.28923266},
 {'date': '2024-09-04', 'value': 29.2616468},
 {'date': '2024-09-05', 'value': 20.49208355},
 {'date': '2024-09-06', 'value': 19.010354525},
 {'date': '2024-09-07', 'value': 22.2680559},
 {'date': '2024-09-08', 'value': 20.406351733333334},
 {'date': '2024-09-09', 'value': 21.4161496},
 {'date': '2024-09-10', 'value': 19.720833300000002},
 {'date': '2024-09-11', 'value': 21.701388350000002},
 {'date': '2024-09-12', 'value': 18.3859796},
 {'date': '2024-09-13', 'value': 19.500891728571425},
 {'date': '2024-09-14', 'value': 13.419284033333334},
 {'date': '2024-09-15', 'value': 11.03749985},
 {'date': '2024-09-16', 'value': 14.45418767142857},
 {'date': '2024-09-17', 'value': 27.16449986666667},
 {'date': '2024-09-18', 'value': 36.941665650000004},
 {'date': '2024-09-19', 'value': 33.871750871428574},
 {'date': '2024-09-20', 'value': 30.00446414545454},
 {'date': '2024-09-21', 'value': 35.400596622222224},
 {'date': '2024-09-22', 'value': 39.14492190833334},
 {'date': '2024-09-23', 'value': 34.908262810000004},
 {'date': '2024-09-24', 'value': 25.16499948},
 {'date': '2024-09-25', 'value': 22.4139483},
 {'date': '2024-09-26', 'value': 22.50571233333333},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

romania_daily = (
    df_results.groupby("date")
              .agg(romania_pm10_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

romania_daily

           date  france_pm10_mean
0    2021-07-06         18.815586
1    2021-07-07         21.693373
2    2021-07-08         20.993357
3    2021-07-09         26.770336
4    2021-07-12         30.407933
...         ...               ...
1597 2026-02-24         23.438217
1598 2026-02-25         16.828325
1599 2026-02-26         17.731852
1600 2026-02-27         29.657553
1601 2026-02-28         29.439106

[1602 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
romania_daily[["date", "romania_pm10_mean"]].to_csv(
    "2daily_avg_romania_PM10.csv",
    index=False
)

# PM2.5

### Get 200 stations located in France that measure PM2.5
Stations are sorted descending by the duration of their measurements

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "RO",   # only consider stations located in romania
    "parameters_id": 2,   # PM2.5
    #"monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_pm25 = df_sorted

df_top_pm25

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
8,9391,BV-1,BRASOV,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11438895, 'name': 'co µg/m³', 'paramet...","{'latitude': 45.637667000204765, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.630747000078838, 45.637667000204765, 25.63...",None,2020-04-20 18:00:00+00:00,2026-03-06 13:00:00+00:00
13,10808,DJ-2,CRAIOVA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11438911, 'name': 'co µg/m³', 'paramet...","{'latitude': 44.319138999966434, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[23.7967079998543, 44.319138999966434, 23.7967...",None,2020-04-20 18:00:00+00:00,2026-03-06 13:00:00+00:00
1,9361,RO0071A,Ilfov,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 193, 'name': 'EEA Romania'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 28586, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 44.3488680301443, 'longitude': 26...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.0336260914258, 44.3488680301443, 26.033626...",None,2020-04-20 18:00:00+00:00,2024-01-29 20:00:00+00:00
4,9365,RO0077A,Cluj,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 193, 'name': 'EEA Romania'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 28597, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 47.1538886994648, 'longitude': 23...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[23.87750053, 47.1538886994648, 23.87750053, 4...",None,2020-04-20 18:00:00+00:00,2024-01-29 20:00:00+00:00
7,9372,RO0087A,Iaşi,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 193, 'name': 'EEA Romania'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 28605, 'name': 'no2 µg/m³', 'parameter...","{'latitude': 47.1371599994647, 'longitude': 27...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[27.693067, 47.1371599994647, 27.693067, 47.13...",None,2020-04-20 18:00:00+00:00,2024-01-29 20:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,6121119,Targu-Mures-VOC-3,NaN,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 23951, 'name': 'Strop de aer'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 14565682, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 46.52231524512759, 'longitude': 2...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[24.52535532343524, 46.52231524512759, 24.5253...",None,2025-11-06 09:00:00+00:00,2026-03-06 14:00:00+00:00
98,6122245,Targu-Mures-VOC-2,NaN,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 23951, 'name': 'Strop de aer'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 14574186, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 46.5224405252689, 'longitude': 24...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[24.525385669165566, 46.5224405252689, 24.5253...",None,2025-11-07 09:00:00+00:00,2026-01-30 05:00:00+00:00
99,6137205,MM-6,SIGHETUL MARMATIEI,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 15115782, 'name': 'co µg/m³', 'paramet...","{'latitude': 47.93055800019584, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[23.888894999874424, 47.93055800019584, 23.888...",None,2025-11-17 08:00:00+00:00,2026-03-06 13:00:00+00:00
100,6160765,GJ-1,TARGU JIU,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 15151403, 'name': 'co µg/m³', 'paramet...","{'latitude': 45.0501939998618, 'longitude': 23...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[23.27397800005523, 45.0501939998618, 23.27397...",None,2025-12-08 10:00:00+00:00,2026-03-06 13:00:00+00:00
101,6233613,Magura Vulturui,NaN,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 12, 'name': 'AirGradient'}","{'id': 66, 'name': 'AirGradient'}",False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15398001, 'name': 'pm1 µg/m³', 'parame...","{'latitude': 44.444659712008495, 'longitude': ...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[26.1363416508151, 44.444659712008495, 26.1363...",None,2026-02-08 21:00:00+00:00,2026-03-06 14:00:00+00:00

### Get sensor_ids from the stations
The daily measurements from a station can only be queried by the sensor_id.
A station usually only has one sensor for one parameter.

In [21]:
rows = []

for _, station in df_top_pm25.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur PM25 behalten
        if sensor["parameter"]["id"] == 2:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_pm25_sensors = pd.DataFrame(rows)

df_pm25_sensors

     station_id       station_name  sensor_id sensor_name
0          9391               BV-1   14927965  pm25 µg/m³
1         10808               DJ-2    1853210  pm25 µg/m³
2          9361            RO0071A    1320340  pm25 µg/m³
3          9365            RO0077A    1853213  pm25 µg/m³
4          9372            RO0087A    1853203  pm25 µg/m³
..          ...                ...        ...         ...
97      6121119  Targu-Mures-VOC-3   14565683  pm25 µg/m³
98      6122245  Targu-Mures-VOC-2   14574187  pm25 µg/m³
99      6137205               MM-6   14927974  pm25 µg/m³
100     6160765               GJ-1   14927970  pm25 µg/m³
101     6233613    Magura Vulturui   15398002  pm25 µg/m³

[102 rows x 4 columns]

In [22]:
sensor_ids = df_pm25_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

102

[14927965,
 1853210,
 1320340,
 1853213,
 1853203,
 1320332,
 1320333,
 14927976,
 14927966,
 1853211,
 1853199,
 1853208,
 5078432,
 5078651,
 7324345,
 7466345,
 7466375,
 7762161,
 7773247,
 7773066,
 7775496,
 7774040,
 7773481,
 8613259,
 14927963,
 7774480,
 7774869,
 14927972,
 14959785,
 14927979,
 14927964,
 14927971,
 7773747,
 7774996,
 7773262,
 7773405,
 7776557,
 7776582,
 7776522,
 14927978,
 14927977,
 7776547,
 8613441,
 14960017,
 14927973,
 14684265,
 8613671,
 8613448,
 8613703,
 8613687,
 8613641,
 14927975,
 8613563,
 14929419,
 8860182,
 9021124,
 9023327,
 9153298,
 10124813,
 10124858,
 14684294,
 14684275,
 14684284,
 14684272,
 14684292,
 14684280,
 14684269,
 14684286,
 14684264,
 14684267,
 14684289,
 14684262,
 14684276,
 14684282,
 14684260,
 14684297,
 14684281,
 14684273,
 10124852,
 14927968,
 10563620,
 10574666,
 14927980,
 14927967,
 11304723,
 14684274,
 11597840,
 11708376,
 11813986,
 12178412,
 12696783,
 13329635,
 13725141,
 13735422,
 14152405,
 14401915,
 14525935,
 14565683,
 14574187,
 14927974,
 14927970,
 15398002]

### Get daily, average values from each sensor/station for 2016-2026

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 14927965: Seite 1, 74 Ergebnisse
Sensor 1853210: Seite 1, 1000 Ergebnisse
Sensor 1853210: Seite 2, 296 Ergebnisse
Sensor 1320340: Seite 1, 846 Ergebnisse
Sensor 1853213: Seite 1, 189 Ergebnisse
Sensor 1853203: Seite 1, 569 Ergebnisse
Sensor 1320332: Seite 1, 848 Ergebnisse
Sensor 1320333: Seite 1, 825 Ergebnisse
Sensor 14927976: Seite 1, 74 Ergebnisse
Sensor 14927966: Seite 1, 74 Ergebnisse
Sensor 1853211: Seite 1, 1000 Ergebnisse
Sensor 1853211: Seite 2, 309 Ergebnisse
Sensor 1853199: Seite 1, 815 Ergebnisse
Sensor 1853208: Seite 1, 571 Ergebnisse
Sensor 5078432: Seite 1, 249 Ergebnisse
Sensor 5078651: Seite 1, 25 Ergebnisse
Sensor 7324345: Seite 1, 568 Ergebnisse
Sensor 7466345: Seite 1, 823 Ergebnisse
Sensor 7466375: Seite 1, 823 Ergebnisse
Sensor 7762161: Seite 1, 81 Ergebnisse
Sensor 7773247: Seite 1, 693 Ergebnisse
Sensor 7773066: Seite 1, 674 Ergebnisse
Sensor 7775496: Seite 1, 726 Ergebnisse
Sensor 7774040: Seite 1, 743 Ergebnisse
Sensor 7773481: Seite 1, 692 Ergebnisse
Sensor 8613259: Seite 1, 570 Ergebnisse
Sensor 14927963: Seite 1, 74 Ergebnisse
Sensor 7774480: Seite 1, 720 Ergebnisse
Sensor 7774869: Seite 1, 744 Ergebnisse
Sensor 14927972: Seite 1, 74 Ergebnisse
Sensor 14959785: Seite 1, 70 Ergebnisse
Sensor 14927979: Seite 1, 74 Ergebnisse
Sensor 14927964: Seite 1, 74 Ergebnisse
Sensor 14927971: Seite 1, 74 Ergebnisse
Sensor 7773747: Seite 1, 667 Ergebnisse
Sensor 7774996: Seite 1, 167 Ergebnisse
Sensor 7773262: Seite 1, 174 Ergebnisse
Sensor 7773405: Seite 1, 170 Ergebnisse
Sensor 7776557: Seite 1, 734 Ergebnisse
Sensor 7776582: Seite 1, 711 Ergebnisse
Sensor 7776522: Seite 1, 711 Ergebnisse
Sensor 14927978: Seite 1, 74 Ergebnisse
Sensor 14927977: Seite 1, 74 Ergebnisse
Sensor 7776547: Seite 1, 127 Ergebnisse
Sensor 8613441: Seite 1, 675 Ergebnisse
Sensor 14960017: Seite 1, 71 Ergebnisse
Sensor 14927973: Seite 1, 74 Ergebnisse
Sensor 14684265: Seite 1, 103 Ergebnisse
Sensor 8613671: Seite 1, 699 Ergebnisse
Sensor 8613448: Seite 1, 570 Ergebnisse
Sensor 8613703: Seite 1, 697 Ergebnisse
Sensor 8613687: Seite 1, 691 Ergebnisse
Sensor 8613641: Seite 1, 122 Ergebnisse
Sensor 14927975: Seite 1, 74 Ergebnisse
Sensor 8613563: Seite 1, 128 Ergebnisse
Sensor 9153298: Seite 1, 624 Ergebnisse
Sensor 10124813: Seite 1, 574 Ergebnisse
Sensor 10124858: Seite 1, 574 Ergebnisse
Sensor 14684294: Seite 1, 104 Ergebnisse
Sensor 14684275: Seite 1, 104 Ergebnisse
Sensor 14684284: Seite 1, 104 Ergebnisse
Sensor 14684272: Seite 1, 104 Ergebnisse
Sensor 14684292: Seite 1, 104 Ergebnisse
Sensor 14684280: Seite 1, 104 Ergebnisse
Sensor 14684269: Seite 1, 104 Ergebnisse
Sensor 14684286: Seite 1, 104 Ergebnisse
Sensor 14684264: Seite 1, 104 Ergebnisse
Sensor 14684267: Seite 1, 104 Ergebnisse
Sensor 14684289: Seite 1, 104 Ergebnisse
Sensor 14684262: Seite 1, 104 Ergebnisse
Sensor 14684276: Seite 1, 104 Ergebnisse
Sensor 14684282: Seite 1, 104 Ergebnisse
Sensor 14684260: Seite 1, 104 Ergebnisse
Sensor 14684297: Seite 1, 104 Ergebnisse
Sensor 14684281: Seite 1, 104 Ergebnisse
Sensor 14684273: Seite 1, 104 Ergebnisse
Sensor 10124852: Seite 1, 575 Ergebnisse
Sensor 14927968: Seite 1, 74 Ergebnisse
Sensor 10563620: Seite 1, 2 Ergebnisse
Sensor 10574666: Seite 1, 484 Ergebnisse
Sensor 14927980: Seite 1, 74 Ergebnisse
Sensor 14927967: Seite 1, 74 Ergebnisse
Sensor 11304723: Seite 1, 445 Ergebnisse
Sensor 14684274: Seite 1, 104 Ergebnisse
Sensor 11597840: Seite 1, 272 Ergebnisse
29322

[{'date': '2025-12-17', 'value': 44.87740999999999},
 {'date': '2025-12-18', 'value': 52.312021428571434},
 {'date': '2025-12-19', 'value': 34.31197944444445},
 {'date': '2025-12-20', 'value': 32.16963652173913},
 {'date': '2025-12-21', 'value': 26.210082916666664},
 {'date': '2025-12-22', 'value': 23.36113916666667},
 {'date': '2025-12-23', 'value': 29.752366666666664},
 {'date': '2025-12-24', 'value': 17.39817583333333},
 {'date': '2025-12-25', 'value': 10.54790304347826},
 {'date': '2025-12-26', 'value': 21.22220173913044},
 {'date': '2025-12-27', 'value': 9.592973749999999},
 {'date': '2025-12-28', 'value': 7.166155000000001},
 {'date': '2025-12-29', 'value': 8.073168749999999},
 {'date': '2025-12-30', 'value': 12.353709583333336},
 {'date': '2025-12-31', 'value': 6.310224999999999},
 {'date': '2026-01-01', 'value': 16.142657619047622},
 {'date': '2026-01-02', 'value': 17.62165695652174},
 {'date': '2026-01-03', 'value': 5.4950625},
 {'date': '2026-01-04', 'value': 11.471191250000002},
 {'date': '2026-01-05', 'value': 14.862246249999998},
 {'date': '2026-01-06', 'value': 22.28481041666667},
 {'date': '2026-01-07', 'value': 29.984210769230767},
 {'date': '2026-01-08', 'value': 14.03884},
 {'date': '2026-01-09', 'value': 18.204233333333335},
 {'date': '2026-01-10', 'value': 39.88537541666667},
 {'date': '2026-01-11', 'value': 12.316667391304348},
 {'date': '2026-01-12', 'value': 10.470044761904761},
 {'date': '2026-01-13', 'value': 28.836039090909086},
 {'date': '2026-01-14', 'value': 27.994038571428568},
 {'date': '2026-01-15', 'value': 21.81711318181818},
 {'date': '2026-01-16', 'value': 23.02853136363636},
 {'date': '2026-01-17', 'value': 24.626077894736845},
 {'date': '2026-01-18', 'value': 11.607664347826086},
 {'date': '2026-01-19', 'value': 15.935755789473683},
 {'date': '2026-01-20', 'value': 36.14469304347826},
 {'date': '2026-01-21', 'value': 54.22861583333332},
 {'date': '2026-01-22', 'value': 29.642077391304355},
 {'date': '2026-01-23', 'value': 35.69654583333334},
 {'date': '2026-01-24', 'value': 30.259527500000004},
 {'date': '2026-01-25', 'value': 32.82701958333333},
 {'date': '2026-01-26', 'value': 7.76890125},
 {'date': '2026-01-27', 'value': 9.20131875},
 {'date': '2026-01-28', 'value': 9.725645217391305},
 {'date': '2026-01-29', 'value': 21.802992916666664},
 {'date': '2026-01-30', 'value': 12.739417500000002},
 {'date': '2026-01-31', 'value': 12.478372499999999},
 {'date': '2026-02-01', 'value': 12.693228333333332},
 {'date': '2026-02-02', 'value': 13.419234999999999},
 {'date': '2026-02-03', 'value': 27.609754999999996},
 {'date': '2026-02-04', 'value': 27.596291249999997},
 {'date': '2026-02-05', 'value': 7.76014590909091},
 {'date': '2026-02-06', 'value': 8.988470454545455},
 {'date': '2026-02-07', 'value': 16.44159041666667},
 {'date': '2026-02-08', 'value': 9.647879583333333},
 {'date': '2026-02-09', 'value': 11.818264999999998},
 {'date': '2026-02-10', 'value': 11.795880416666668},
 {'date': '2026-02-11', 'value': 12.84462157894737},
 {'date': '2026-02-12', 'value': 20.107727499999992},
 {'date': '2026-02-13', 'value': 18.24326791666667},
 {'date': '2026-02-14', 'value': 9.759427916666665},
 {'date': '2026-02-15', 'value': 15.577928333333332},
 {'date': '2026-02-16', 'value': 8.499882173913043},
 {'date': '2026-02-17', 'value': 15.318942083333335},
 {'date': '2026-02-18', 'value': 9.471845},
 {'date': '2026-02-19', 'value': 15.698086315789475},
 {'date': '2026-02-20', 'value': 18.988163125},
 {'date': '2026-02-21', 'value': 14.544991739130435},
 {'date': '2026-02-22', 'value': 16.63016916666666},
 {'date': '2026-02-23', 'value': 27.216067083333332},
 {'date': '2026-02-24', 'value': 4.87422375},
 {'date': '2026-02-25', 'value': 5.973959166666667},
 {'date': '2026-02-26', 'value': 6.860663333333334},
 {'date': '2026-02-27', 'value': 16.50060791666667},
 {'date': '2026-02-28', 'value': 20.275835217391304},
 {'date': '2022-04-29', 'value': 8.028909601666667},
 {'date': '2022-04-30', 'value': 4.958874299583333},
 {'date': '2022-05-01', 'value': 6.5997770775},
 {'date': '2022-05-02', 'value': 6.371636800833335},
 {'date': '2022-05-03', 'value': 7.0427472175},
 {'date': '2022-05-04', 'value': 10.703552773333334},
 {'date': '2022-05-05', 'value': 9.392204740416666},
 {'date': '2022-05-06', 'value': 8.027914231666665},
 {'date': '2022-05-07', 'value': 8.730665388750001},
 {'date': '2022-05-08', 'value': 7.08085336642857},
 {'date': '2022-05-09', 'value': 7.263372895000001},
 {'date': '2022-05-10', 'value': 7.385251152083334},
 {'date': '2022-05-11', 'value': 7.77292210125},
 {'date': '2022-05-12', 'value': 8.6302370325},
 {'date': '2022-05-13', 'value': 9.9902166625},
 {'date': '2022-05-14', 'value': 9.111128235416666},
 {'date': '2022-05-15', 'value': 8.462407402916666},
 {'date': '2022-05-16', 'value': 11.232878814583332},
 {'date': '2022-05-17', 'value': 9.228060758333333},
 {'date': '2022-05-18', 'value': 5.098772216666668},
 {'date': '2022-05-19', 'value': 6.223490620833334},
 {'date': '2022-05-20', 'value': 4.891179757142857},
 {'date': '2022-05-21', 'value': 7.934751269166667},
 {'date': '2022-05-22', 'value': 4.413520702727274},
 {'date': '2022-05-23', 'value': 5.928732094444444},
 {'date': '2022-05-24', 'value': 7.14214949090909},
 {'date': '2022-05-25', 'value': 8.836268049583333},
 {'date': '2022-05-26', 'value': 6.49370497125},
 {'date': '2022-05-27', 'value': 4.2771074066666666},
 {'date': '2022-05-28', 'value': 7.56599391},
 {'date': '2022-05-29', 'value': 4.974579045833333},
 {'date': '2022-05-30', 'value': 6.271902797391305},
 {'date': '2022-05-31', 'value': 12.758046665000002},
 {'date': '2022-06-01', 'value': 15.256734716666665},
 {'date': '2022-06-02', 'value': 18.444777773333332},
 {'date': '2022-06-03', 'value': 16.106004151666664},
 {'date': '2022-06-04', 'value': 11.076793050416667},
 {'date': '2022-06-05', 'value': 12.606249185833335},
 {'date': '2022-06-06', 'value': 7.30076006375},
 {'date': '2022-06-07', 'value': 8.618024301666667},
 {'date': '2022-06-08', 'value': 8.343326267499998},
 {'date': '2022-06-09', 'value': 8.880886337916666},
 {'date': '2022-06-10', 'value': 8.208812610416667},
 {'date': '2022-06-11', 'value': 8.796649300416668},
 {'date': '2022-06-12', 'value': 9.336617355833333},
 {'date': '2022-06-13', 'value': 9.516211106249997},
 {'date': '2022-06-14', 'value': 9.359363652083333},
 {'date': '2022-06-15', 'value': 8.723679857083335},
 {'date': '2022-06-16', 'value': 11.3073512875},
 {'date': '2022-06-17', 'value': 13.802122911666665},
 {'date': '2022-06-18', 'value': 9.629403467083332},
 {'date': '2022-06-19', 'value': 9.475881245416664},
 {'date': '2022-06-20', 'value': 11.261126847083334},
 {'date': '2022-06-21', 'value': 11.160049068333334},
 {'date': '2022-06-22', 'value': 6.058162031666666},
 {'date': '2022-06-23', 'value': 9.207398217083332},
 {'date': '2022-06-24', 'value': 13.057608791250003},
 {'date': '2022-06-25', 'value': 16.28462076826087},
 {'date': '2022-06-26', 'value': 13.68896296},
 {'date': '2022-06-27', 'value': 15.517378302380953},
 {'date': '2022-06-28', 'value': 16.25099328125},
 {'date': '2022-06-29', 'value': 16.100828698333334},
 {'date': '2022-06-30', 'value': 16.712729638749998},
 {'date': '2022-07-01', 'value': 17.23420022625},
 {'date': '2022-07-02', 'value': 17.128301383333334},
 {'date': '2022-07-03', 'value': 19.06406943958333},
 {'date': '2022-07-04', 'value': 20.529062494375},
 {'date': '2022-07-05', 'value': 22.499111106666664},
 {'date': '2022-07-06', 'value': 12.57778090958333},
 {'date': '2022-07-07', 'value': 8.805957983333334},
 {'date': '2022-07-08', 'value': 6.62250508875},
 {'date': '2022-07-09', 'value': 8.331378699166669},
 {'date': '2022-07-10', 'value': 8.782761568750002},
 {'date': '2022-07-11', 'value': 5.21161967},
 {'date': '2022-07-12', 'value': 4.951697795416668},
 {'date': '2022-07-13', 'value': 5.787133096666667},
 {'date': '2022-07-14', 'value': 7.191027308333335},
 {'date': '2022-07-15', 'value': 9.815689684166667},
 {'date': '2022-07-16', 'value': 9.329797216666664},
 {'date': '2022-07-17', 'value': 7.359274185},
 {'date': '2022-07-18', 'value': 8.529684054347825},
 {'date': '2022-07-19', 'value': 10.829527202857143},
 {'date': '2022-07-20', 'value': 12.160278913157894},
 {'date': '2022-07-21', 'value': 10.755523605833332},
 {'date': '2022-07-22', 'value': 10.977793050833334},
 {'date': '2022-07-25', 'value': 15.151307686923076},
 {'date': '2022-07-27', 'value': 14.014644968095237},
 {'date': '2022-07-28', 'value': 12.1090606425},
 {'date': '2022-07-29', 'value': 11.710090272083335},
 {'date': '2022-07-30', 'value': 11.548238767500003},
 {'date': '2022-07-31', 'value': 4.978511106666667},
 {'date': '2022-08-01', 'value': 4.692470365416667},
 {'date': '2022-08-02', 'value': 6.030122333333334},
 {'date': '2022-08-03', 'value': 8.465140734583334},
 {'date': '2022-08-04', 'value': 9.914128814166668},
 {'date': '2022-08-05', 'value': 12.942738189166668},
 {'date': '2022-08-06', 'value': 12.119636105833331},
 {'date': '2022-08-07', 'value': 12.017999995416668},
 {'date': '2022-08-08', 'value': 12.162981939166668},
 {'date': '2022-08-09', 'value': 12.518137725416667},
 {'date': '2022-08-10', 'value': 12.716493745},
 {'date': '2022-08-11', 'value': 8.353096804583332},
 {'date': '2022-08-12', 'value': 9.869821985833335},
 {'date': '2022-08-13', 'value': 14.07046457833333},
 {'date': '2022-08-14', 'value': 13.413836105833333},
 {'date': '2022-08-15', 'value': 14.299061432941174},
 {'date': '2022-08-16', 'value': 12.695939808749998},
 {'date': '2022-08-17', 'value': 12.82353332791667},
 {'date': '2022-08-18', 'value': 12.552812495416667},
 {'date': '2022-08-19', 'value': 15.986333329999997},
 {'date': '2022-08-20', 'value': 11.22157221888889},
 {'date': '2022-08-21', 'value': 10.909093398333333},
 {'date': '2022-08-22', 'value': 9.9655708875},
 {'date': '2022-08-23', 'value': 7.954582982500003},
 {'date': '2022-08-24', 'value': 8.844027771666665},
 {'date': '2022-08-25', 'value': 10.098747216666666},
 {'date': '2022-08-26', 'value': 10.536799466190477},
 {'date': '2022-08-27', 'value': 14.049039810000002},
 {'date': '2022-08-28', 'value': 14.08992592125},
 {'date': '2022-08-29', 'value': 15.347268513333335},
 {'date': '2022-08-30', 'value': 14.256967587500002},
 {'date': '2022-08-31', 'value': 15.00081481041667},
 {'date': '2022-09-01', 'value': 11.992202310000001},
 {'date': '2022-09-02', 'value': 9.168725920833333},
 {'date': '2022-09-03', 'value': 7.78569004125},
 {'date': '2022-09-04', 'value': 9.712535065000003},
 {'date': '2022-09-05', 'value': 13.385845828333332},
 {'date': '2022-09-06', 'value': 17.796041662083336},
 {'date': '2022-09-07', 'value': 12.913708147499998},
 {'date': '2022-09-08', 'value': 14.764451384583333},
 {'date': '2022-09-09', 'value': 16.82279860541667},
 {'date': '2022-09-10', 'value': 17.263770481249995},
 {'date': '2022-09-11', 'value': 4.080760412083333},
 {'date': '2022-09-12', 'value': 4.304177410434782},
 {'date': '2022-09-13', 'value': 6.982150920000002},
 {'date': '2022-09-14', 'value': 10.377718050833332},
 {'date': '2022-09-15', 'value': 10.406061337083331},
 {'date': '2022-09-16', 'value': 6.0038499949999995},
 {'date': '2022-09-17', 'value': 6.914621291666667},
 {'date': '2022-09-18', 'value': 2.409794670833333},
 {'date': '2022-09-19', 'value': 3.725516013333332},
 {'date': '2022-09-20', 'value': 3.6035354112499998},
 {'date': '2022-09-21', 'value': 6.703932633749999},
 {'date': '2022-09-22', 'value': 7.401892934166668},
 {'date': '2022-09-23', 'value': 6.866875342916664},
 {'date': '2022-09-24', 'value': 8.796794436666667},
 {'date': '2022-09-25', 'value': 14.525823803809525},
 {'date': '2022-09-26', 'value': 17.359537032916666},
 {'date': '2022-09-27', 'value': 10.882817587916668},
 {'date': '2022-09-28', 'value': 9.364856939583335},
 {'date': '2022-09-29', 'value': 11.148549532083335},
 {'date': '2022-09-30', 'value': 10.4635074025},
 {'date': '2022-10-01', 'value': 16.99354143125},
 {'date': '2022-10-02', 'value': 4.218229508333333},
 {'date': '2022-10-03', 'value': 3.5828986062499997},
 {'date': '2022-10-04', 'value': 5.462252425833334},
 {'date': '2022-10-05', 'value': 16.932931244583337},
 {'date': '2022-10-06', 'value': 16.75886220333333},
 {'date': '2022-10-07', 'value': 18.208855732083332},
 {'date': '2022-10-08', 'value': 21.779073606249998},
 {'date': '2022-10-09', 'value': 30.47677777333333},
 {'date': '2022-10-10', 'value': 13.334263883333335},
 {'date': '2022-10-11', 'value': 15.510161337083334},
 {'date': '2022-10-12', 'value': 19.584295134166663},
 {'date': '2022-10-13', 'value': 18.278482568260873},
 {'date': '2022-10-14', 'value': 14.545862958750002},
 {'date': '2022-10-15', 'value': 14.0580113375},
 {'date': '2022-10-16', 'value': 31.74659143},
 {'date': '2022-10-17', 'value': 34.53036110666667},
 {'date': '2022-10-18', 'value': 32.989194440416675},
 {'date': '2022-10-19', 'value': 27.147447392916664},
 {'date': '2022-10-20', 'value': 19.761938967916674},
 {'date': '2022-10-21', 'value': 17.582138304999997},
 {'date': '2022-10-22', 'value': 38.37151041083333},
 {'date': '2022-10-23', 'value': 18.13534305},
 {'date': '2022-10-24', 'value': 23.664527770000003},
 {'date': '2022-10-25', 'value': 17.85208552263158},
 {'date': '2022-10-26', 'value': 13.310073667826087},
 {'date': '2022-10-27', 'value': 20.242669559999996},
 {'date': '2022-10-28', 'value': 25.323059923750005},
 {'date': '2022-10-29', 'value': 32.46877777},
 {'date': '2022-11-02', 'value': 25.099460312142856},
 {'date': '2022-11-03', 'value': 25.39190422809524},
 {'date': '2022-11-04', 'value': 41.79244443958333},
 {'date': '2022-11-05', 'value': 33.19548147708334},
 {'date': '2022-11-06', 'value': 22.38849999545455},
 {'date': '2022-11-07', 'value': 24.580856245000007},
 {'date': '2022-11-08', 'value': 37.335387494166675},
 {'date': '2022-11-09', 'value': 41.92952777208334},
 {'date': '2022-11-10', 'value': 49.08771450111111},
 {'date': '2022-11-11', 'value': 35.35631759173913},
 {'date': '2022-11-12', 'value': 30.5933229125},
 {'date': '2022-11-13', 'value': 44.12701041166667},
 {'date': '2022-11-14', 'value': 36.49774189291667},
 {'date': '2022-11-15', 'value': 30.531799764166674},
 {'date': '2022-11-16', 'value': 30.067345405652176},
 {'date': '2022-11-17', 'value': 24.586160642916667},
 {'date': '2022-11-18', 'value': 23.196122680833337},
 {'date': '2022-11-19', 'value': 24.511049995416666},
 {'date': '2022-11-20', 'value': 13.343023837499997},
 {'date': '2022-11-21', 'value': 8.018718282499998},
 {'date': '2022-11-22', 'value': 17.41455346791667},
 {'date': '2022-11-23', 'value': 16.489625},
 {'date': '2022-11-24', 'value': 9.271686737272729},
 {'date': '2022-11-25', 'value': 14.422124647083335},
 {'date': '2022-11-26', 'value': 51.3357291625},
 {'date': '2022-11-27', 'value': 69.62541319041667},
 {'date': '2022-11-28', 'value': 40.78841140625},
 {'date': '2022-11-29', 'value': 23.800326846249998},
 {'date': '2022-11-30', 'value': 8.240068514583333},
 {'date': '2022-12-01', 'value': 14.871608791666667},
 {'date': '2022-12-02', 'value': 12.214400476956524},
 {'date': '2022-12-03', 'value': 15.367858581363636},
 {'date': '2022-12-04', 'value': 10.112247910833334},
 {'date': '2022-12-05', 'value': 9.697130781666667},
 {'date': '2022-12-06', 'value': 13.163127957499997},
 {'date': '2022-12-07', 'value': 22.59397453166667},
 {'date': '2022-12-08', 'value': 26.88858494916667},
 {'date': '2022-12-09', 'value': 21.627454101304348},
 {'date': '2022-12-10', 'value': 49.952552078749996},
 {'date': '2022-12-11', 'value': 12.377331938333334},
 {'date': '2022-12-12', 'value': 11.110786260833335},
 {'date': '2022-12-13', 'value': 25.062236107083333},
 {'date': '2022-12-14', 'value': 29.136543474782606},
 {'date': '2022-12-15', 'value': 20.9053472175},
 {'date': '2022-12-16', 'value': 34.24226767136364},
 {'date': '2022-12-17', 'value': 26.410663279999994},
 {'date': '2022-12-18', 'value': 22.304870365833334},
 {'date': '2022-12-19', 'value': 20.74524274782609},
 {'date': '2022-12-20', 'value': 28.258989578750004},
 {'date': '2022-12-21', 'value': 33.58592146695651},
 {'date': '2022-12-22', 'value': 37.33189235541666},
 {'date': '2022-12-23', 'value': 45.07594444},
 {'date': '2022-12-24', 'value': 89.86952524818183},
 {'date': '2022-12-25', 'value': 50.524886106666656},
 {'date': '2022-12-26', 'value': 61.05982869874999},
 {'date': '2022-12-27', 'value': 45.08598055083332},
 {'date': '2022-12-28', 'value': 15.165210296250002},
 {'date': '2022-12-29', 'value': 60.077565968333325},
 {'date': '2022-12-30', 'value': 83.04415151090909},
 {'date': '2022-12-31', 'value': 102.81649305041668},
 {'date': '2023-01-01', 'value': 150.3953298575},
 {'date': '2023-01-02', 'value': 78.3980857447826},
 {'date': '2023-01-03', 'value': 42.869289624000004},
 {'date': '2023-01-04', 'value': 33.78391897625},
 {'date': '2023-01-05', 'value': 40.70949419458333},
 {'date': '2023-01-06', 'value': 8.27123767652174},
 {'date': '2023-01-07', 'value': 16.35491666125},
 {'date': '2023-01-08', 'value': 35.901728389999995},
 {'date': '2023-01-09', 'value': 23.765784717083335},
 {'date': '2023-01-10', 'value': 15.16047291208333},
 {'date': '2023-01-11', 'value': 7.101759351052633},
 {'date': '2023-01-16', 'value': 19.85766666},
 {'date': '2023-01-17', 'value': 15.368361801250003},
 {'date': '2023-01-18', 'value': 8.151324995416665},
 {'date': '2023-01-19', 'value': 9.079271615833333},
 {'date': '2023-01-20', 'value': 6.663743957826088},
 {'date': '2023-01-21', 'value': 16.242152079166665},
 {'date': '2023-01-22', 'value': 40.083138885},
 {'date': '2023-01-23', 'value': 6.9872412652380955},
 {'date': '2023-01-24', 'value': 7.0631352735},
 {'date': '2023-01-25', 'value': 9.380983211666667},
 {'date': '2023-01-26', 'value': 12.376729624166666},
 {'date': '2023-01-27', 'value': 14.910852752857144},
 {'date': '2023-01-28', 'value': 15.982971010434785},
 {'date': '2023-01-29', 'value': 19.567096291666665},
 {'date': '2023-01-30', 'value': 13.077095449545455},
 {'date': '2023-01-31', 'value': 12.656837341111109},
 {'date': '2023-02-01', 'value': 7.746162799545456},
 {'date': '2023-02-02', 'value': 6.710266665000001},
 {'date': '2023-02-14', 'value': 34.33618812636364},
 {'date': '2023-02-15', 'value': 26.90434953208334},
 {'date': '2023-02-16', 'value': 69.29656944},
 {'date': '2023-03-19', 'value': 21.056871207727276},
 {'date': '2023-03-20', 'value': 18.165452936470587},
 {'date': '2023-03-21', 'value': 22.035212115909093},
 {'date': '2023-03-22', 'value': 14.577976614999997},
 {'date': '2023-03-23', 'value': 12.681249995},
 {'date': '2023-03-24', 'value': 22.24598433818182},
 {'date': '2023-03-25', 'value': 15.852375573333335},
 {'date': '2023-03-26', 'value': 5.356984657826087},
 {'date': '2023-03-27', 'value': 8.601470712916667},
 {'date': '2023-03-28', 'value': 5.210854740833333},
 {'date': '2023-03-29', 'value': 7.774837147499999},
 {'date': '2023-03-30', 'value': 14.388636338750002},
 {'date': '2023-03-31', 'value': 14.287415735416666},
 {'date': '2023-04-01', 'value': 15.931029161666666},
 {'date': '2023-04-02', 'value': 4.9701296245833335},
 {'date': '2023-04-03', 'value': 8.771168513333333},
 {'date': '2023-04-04', 'value': 5.870731477083332},
 {'date': '2023-04-05', 'value': 6.213623952916667},
 {'date': '2023-04-06', 'value': 8.842982287083332},
 {'date': '2023-04-07', 'value': 13.776011800416667},
 {'date': '2023-04-08', 'value': 17.567760412499997},
 {'date': '2023-04-09', 'value': 17.73732221791666},
 {'date': '2023-04-10', 'value': 15.149302078333335},
 {'date': '2023-04-11', 'value': 13.280421868333333},
 {'date': '2023-04-12', 'value': 6.9141116841666665},
 {'date': '2023-04-13', 'value': 7.539301499166669},
 {'date': '2023-04-14', 'value': 11.300618050416666},
 {'date': '2023-04-15', 'value': 9.1248152725},
 {'date': '2023-04-16', 'value': 6.308258327499999},
 {'date': '2023-04-17', 'value': 7.690334717083335},
 {'date': '2023-04-18', 'value': 8.063381014583333},
 {'date': '2023-04-19', 'value': 10.461211337916664},

### Transform queried data into a dataframe
Data is grouped by date and values are aggregated by mean

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

romania_daily = (
    df_results.groupby("date")
              .agg(romania_pm25_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

romania_daily

           date  france_pm25_mean
0    2018-01-28         27.315789
1    2018-01-29         26.947368
2    2018-01-30         26.526316
3    2018-02-01        -42.210526
4    2018-02-03        -43.052632
...         ...               ...
2792 2026-02-24         26.024905
2793 2026-02-25         26.238816
2794 2026-02-26         26.178332
2795 2026-02-27         29.510096
2796 2026-02-28         26.152940

[2797 rows x 2 columns]

### Convert dataframe to csv

In [ ]:
romania_daily[["date", "romania_pm25_mean"]].to_csv(
    "daily_avg_romania_PM25.csv",
    index=False
)

# NO2

In [ ]:
api_url = "https://api.openaq.org/v3/locations"

params = {
    "iso": "RO",   # only consider stations located in romania
    "parameters_id": 5,   # NO2
    "monitor": True,   # only consider stations which only use devices that are used for official/governmental monitoring
    "limit": 1000        # results per page
}

headers = {
    "X-API-Key": "..."
}

response = requests.get(api_url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

results = data["results"]

df = pd.DataFrame(results)

df["datetimeFirst"] = pd.to_datetime(
    df["datetimeFirst"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df["datetimeLast"] = pd.to_datetime(
    df["datetimeLast"].apply(lambda x: x["utc"] if isinstance(x, dict) else None)
)

df_sorted = df.sort_values(
    by=["datetimeFirst", "datetimeLast"],
    ascending=[True, False]
)

df_top_no2 = df_sorted

df_top_no2

,id,name,locality,timezone,country,owner,provider,isMobile,isMonitor,instruments,sensors,coordinates,licenses,bounds,distance,datetimeFirst,datetimeLast
91,10687,RO0175A,Prahova,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 193, 'name': 'EEA Romania'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 6311538, 'name': 'co µg/m³', 'paramete...","{'latitude': 44.9410132188863, 'longitude': 25...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.9985019638167, 44.9410132188863, 25.998501...",None,2020-04-19 21:00:00+00:00,2024-01-29 20:00:00+00:00
9,8761,BV-4,SANPETRU,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 6311503, 'name': 'co µg/m³', 'paramete...","{'latitude': 45.71807500023249, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.624194000286955, 45.71807500023249, 25.624...",None,2020-04-20 18:00:00+00:00,2026-03-16 15:00:00+00:00
35,9386,BT-1,BOTOSANI,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 6310365, 'name': 'co µg/m³', 'paramete...","{'latitude': 47.739918999753456, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.658519000154435, 47.739918999753456, 26.65...",None,2020-04-20 18:00:00+00:00,2026-03-16 15:00:00+00:00
39,9391,BV-1,BRASOV,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11438895, 'name': 'co µg/m³', 'paramet...","{'latitude': 45.637667000204765, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.630747000078838, 45.637667000204765, 25.63...",None,2020-04-20 18:00:00+00:00,2026-03-16 15:00:00+00:00
40,9393,BV-5,BRASOV,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 11438896, 'name': 'co µg/m³', 'paramet...","{'latitude': 45.65159700027666, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[25.625652999953974, 45.65159700027666, 25.625...",None,2020-04-20 18:00:00+00:00,2026-03-16 15:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,2163221,TM-7,LUGOJ,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 15151410, 'name': 'no2 µg/m³', 'parame...","{'latitude': 45.69454700029775, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[21.893083000405372, 45.69454700029775, 21.893...",None,2025-12-08 10:00:00+00:00,2026-03-16 14:00:00+00:00
293,6169175,BH-4,TETCHEA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923200, 'name': 'no2 µg/m³', 'parame...","{'latitude': 47.0437920001766, 'longitude': 22...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[22.33190600033012, 47.0437920001766, 22.33190...",None,2025-12-16 23:00:00+00:00,2026-03-16 15:00:00+00:00
294,6169177,IL-2,URZICENI,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923207, 'name': 'no2 µg/m³', 'parame...","{'latitude': 44.723038999830635, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.651464000222223, 44.723038999830635, 26.65...",None,2025-12-16 23:00:00+00:00,2026-03-16 15:00:00+00:00
295,6169178,SV-2,SUCEAVA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14923198, 'name': 'no2 µg/m³', 'parame...","{'latitude': 47.66882500020218, 'longitude': 2...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[26.281403000064568, 47.66882500020218, 26.281...",None,2025-12-16 23:00:00+00:00,2026-03-16 15:00:00+00:00
296,6169830,HD-6,DEVA,Europe/Bucharest,"{'id': 74, 'code': 'RO', 'name': 'Romania'}","{'id': 4, 'name': 'Unknown Governmental Organi...","{'id': 70, 'name': 'EEA'}",False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 14927969, 'name': 'no2 µg/m³', 'parame...","{'latitude': 45.883299999934685, 'longitude': ...","[{'id': 10, 'name': 'ODC-BY', 'attribution': {...","[22.906825999909092, 45.883299999934685, 22.90...",None,2025-12-16 23:00:00+00:00,2026-03-16 15:00:00+00:00

In [11]:
rows = []

for _, station in df_top_no2.iterrows():
    
    for sensor in station["sensors"]:
        
        # Nur NO2 behalten
        if sensor["parameter"]["id"] == 5:
            
            rows.append({
                "station_id": station["id"],
                "station_name": station["name"],
                "sensor_id": sensor["id"],
                "sensor_name": sensor["name"]
            })

df_no2_sensors = pd.DataFrame(rows)

df_no2_sensors

     station_id station_name  sensor_id sensor_name
0         10687      RO0175A      35601   no2 µg/m³
1          8761         BV-4      25543   no2 µg/m³
2          9386         BT-1      28646   no2 µg/m³
3          9391         BV-1      28657   no2 µg/m³
4          9393         BV-5      28665   no2 µg/m³
..          ...          ...        ...         ...
292     2163221         TM-7   15151410   no2 µg/m³
293     6169175         BH-4   14923200   no2 µg/m³
294     6169177         IL-2   14923207   no2 µg/m³
295     6169178         SV-2   14923198   no2 µg/m³
296     6169830         HD-6   14927969   no2 µg/m³

[297 rows x 4 columns]

In [12]:
sensor_ids = df_no2_sensors["sensor_id"].tolist()
print(len(sensor_ids))
sensor_ids

297

[35601,
 25543,
 28646,
 28657,
 28665,
 28671,
 28678,
 28741,
 35075,
 35116,
 35941,
 36105,
 36350,
 24005,
 28581,
 28584,
 28586,
 28597,
 28605,
 28621,
 28623,
 28680,
 28687,
 28694,
 28709,
 28725,
 28733,
 28734,
 28743,
 35434,
 35150,
 35500,
 35770,
 35816,
 36014,
 36020,
 36036,
 36039,
 36042,
 36044,
 36242,
 28673,
 36041,
 28607,
 28746,
 28675,
 28684,
 28629,
 35685,
 36113,
 28736,
 28719,
 28650,
 28688,
 34878,
 28648,
 34855,
 28723,
 28610,
 23600,
 28705,
 23424,
 36241,
 28643,
 28729,
 28630,
 23021,
 23073,
 28644,
 28727,
 28744,
 28745,
 28748,
 35193,
 35511,
 35768,
 35840,
 35922,
 36038,
 36062,
 36070,
 36083,
 36096,
 36135,
 36015,
 28600,
 28652,
 28697,
 28700,
 28710,
 35195,
 35782,
 35904,
 35926,
 36119,
 36275,
 36384,
 35767,
 28631,
 28731,
 35686,
 28721,
 28604,
 28742,
 36469,
 28703,
 28707,
 28667,
 35025,
 28599,
 35575,
 35180,
 28594,
 36040,
 28747,
 28602,
 35086,
 28639,
 28603,
 5078858,
 5079508,
 5078326,
 5078733,
 5079509,
 5078840,
 8740157,
 5078530,
 7775432,
 8623290,
 7774357,
 9020849,
 7772771,
 8613197,
 7774080,
 8613149,
 8613220,
 7774133,
 7774576,
 8740159,
 7775196,
 8622708,
 7775598,
 8613248,
 7772957,
 8613278,
 7775163,
 7773251,
 15152083,
 7775691,
 8613233,
 11382585,
 7774877,
 7774981,
 7774145,
 7774212,
 7974424,
 8613243,
 8622667,
 7773181,
 7774503,
 8622234,
 7773217,
 7772716,
 8613521,
 7772851,
 7775596,
 7773100,
 8613193,
 8613256,
 7773235,
 8613024,
 8613330,
 8613267,
 8622319,
 7775617,
 8613616,
 7775244,
 8613297,
 10489109,
 11382584,
 7776591,
 10491957,
 8613230,
 8613337,
 7776501,
 7776978,
 7776559,
 8613351,
 8613102,
 8750172,
 8613199,
 7776621,
 7776565,
 14850748,
 8613253,
 10962240,
 10970498,
 8613294,
 8613179,
 12334931,
 8613338,
 7902554,
 7970414,
 7974590,
 8613432,
 8613466,
 8613434,
 8613353,
 8613570,
 8613422,
 8613615,
 8622686,
 8622279,
 8613608,
 8613628,
 8613649,
 8613076,
 8613218,
 8613129,
 11042698,
 8613343,
 8622687,
 8622685,
 8613414,
 8613364,
 8613696,
 8613630,
 8622215,
 8613437,
 8622246,
 8613121,
 8622661,
 8613427,
 8622714,
 8613603,
 8613697,
 8613444,
 14850756,
 8613564,
 8613471,
 8613586,
 8624481,
 8613598,
 8613428,
 8622321,
 8627099,
 8632843,
 8627967,
 8644664,
 8692366,
 8740158,
 9021933,
 9021127,
 14684288,
 14684268,
 14684277,
 10418727,
 10419362,
 10425457,
 10419661,
 10579599,
 10633436,
 10714173,
 10714170,
 10725457,
 10725453,
 10793553,
 10793874,
 12660435,
 10983944,
 10984424,
 10985447,
 10986422,
 10996698,
 12334924,
 12334921,
 12334930,
 12334923,
 14684290,
 14860316,
 14684266,
 15151412,
 14840190,
 14851298,
 15151409,
 15151407,
 15151399,
 15151408,
 14860319,
 15151395,
 14860315,
 14860314,
 15151410,
 14923200,
 14923207,
 14923198,
 14927969]

In [ ]:
headers = {
    "X-API-Key": "..."
}

all_daily_values = []

for sensor_id in sensor_ids:

    api_url = f'https://api.openaq.org/v3/sensors/{sensor_id}/measurements/daily'

    page = 1
    
    while True:
        params = {
            'datetime_to': '2026-03-01',
            'datetime_from': '2016-01-01',
            'limit': 1000,
            'page': page
        }
    
        response = requests.get(api_url, params=params, headers=headers)
    
        if response.status_code != 200:
            break
            
        data = response.json()
        results = data['results']
    
        if not results:
            break

        print(f"Sensor {sensor_id}: Seite {page}, {len(results)} Ergebnisse")
    
        for r in results:
            #sensor_results.append(r)

        # Datum (nur YYYY-MM-DD)
            date = r["period"]["datetimeFrom"]["local"][:10]

            # Daily Average
            value = r["summary"]["avg"]

            if value is not None:
                all_daily_values.append({
                    "date": date,
                    "value": value
                })
        
        page += 1

        time.sleep(0.2)

print(len(all_daily_values))
all_daily_values

Sensor 35601: Seite 1, 1000 Ergebnisse
Sensor 35601: Seite 2, 276 Ergebnisse
Sensor 25543: Seite 1, 1000 Ergebnisse
Sensor 25543: Seite 2, 525 Ergebnisse
Sensor 28646: Seite 1, 1000 Ergebnisse
Sensor 28646: Seite 2, 881 Ergebnisse
Sensor 28657: Seite 1, 1000 Ergebnisse
Sensor 28657: Seite 2, 238 Ergebnisse
Sensor 28665: Seite 1, 1000 Ergebnisse
Sensor 28665: Seite 2, 364 Ergebnisse
Sensor 28671: Seite 1, 1000 Ergebnisse
Sensor 28671: Seite 2, 58 Ergebnisse
Sensor 28678: Seite 1, 1000 Ergebnisse
Sensor 28678: Seite 2, 261 Ergebnisse
Sensor 28741: Seite 1, 1000 Ergebnisse
Sensor 28741: Seite 2, 826 Ergebnisse
Sensor 35075: Seite 1, 1000 Ergebnisse
Sensor 35075: Seite 2, 351 Ergebnisse
Sensor 35116: Seite 1, 1000 Ergebnisse
Sensor 35116: Seite 2, 454 Ergebnisse
Sensor 35941: Seite 1, 1000 Ergebnisse
Sensor 35941: Seite 2, 1000 Ergebnisse
Sensor 35941: Seite 3, 6 Ergebnisse
Sensor 36105: Seite 1, 1000 Ergebnisse
Sensor 36105: Seite 2, 418 Ergebnisse
Sensor 36350: Seite 1, 1000 Ergebnisse
Sensor 36350: Seite 2, 670 Ergebnisse
Sensor 24005: Seite 1, 1000 Ergebnisse
Sensor 24005: Seite 2, 229 Ergebnisse
Sensor 28581: Seite 1, 1000 Ergebnisse
Sensor 28581: Seite 2, 276 Ergebnisse
Sensor 28584: Seite 1, 1000 Ergebnisse
Sensor 28584: Seite 2, 253 Ergebnisse
Sensor 28586: Seite 1, 1000 Ergebnisse
Sensor 28586: Seite 2, 273 Ergebnisse
Sensor 28597: Seite 1, 818 Ergebnisse
Sensor 28605: Seite 1, 694 Ergebnisse
Sensor 28621: Seite 1, 1000 Ergebnisse
Sensor 28621: Seite 2, 265 Ergebnisse
Sensor 28623: Seite 1, 1000 Ergebnisse
Sensor 28623: Seite 2, 144 Ergebnisse
Sensor 28680: Seite 1, 901 Ergebnisse
Sensor 28687: Seite 1, 1000 Ergebnisse
Sensor 28687: Seite 2, 104 Ergebnisse
Sensor 28694: Seite 1, 868 Ergebnisse
Sensor 28709: Seite 1, 1000 Ergebnisse
Sensor 28709: Seite 2, 274 Ergebnisse
Sensor 28725: Seite 1, 684 Ergebnisse
Sensor 28733: Seite 1, 1000 Ergebnisse
Sensor 28733: Seite 2, 230 Ergebnisse
Sensor 28734: Seite 1, 1000 Ergebnisse
Sensor 28734: Seite 2, 211 Ergebnisse
Sensor 28743: Seite 1, 1000 Ergebnisse
Sensor 28743: Seite 2, 184 Ergebnisse
Sensor 35434: Seite 1, 1000 Ergebnisse
Sensor 35434: Seite 2, 22 Ergebnisse
Sensor 35150: Seite 1, 997 Ergebnisse
Sensor 35500: Seite 1, 934 Ergebnisse
Sensor 35770: Seite 1, 935 Ergebnisse
Sensor 35816: Seite 1, 739 Ergebnisse
Sensor 36014: Seite 1, 1000 Ergebnisse
Sensor 36014: Seite 2, 99 Ergebnisse
Sensor 36020: Seite 1, 1000 Ergebnisse
Sensor 36020: Seite 2, 270 Ergebnisse
Sensor 36036: Seite 1, 1000 Ergebnisse
Sensor 36036: Seite 2, 247 Ergebnisse
Sensor 36039: Seite 1, 815 Ergebnisse
Sensor 36042: Seite 1, 974 Ergebnisse
Sensor 36044: Seite 1, 1000 Ergebnisse
Sensor 36044: Seite 2, 97 Ergebnisse
Sensor 36242: Seite 1, 776 Ergebnisse
Sensor 28673: Seite 1, 420 Ergebnisse
Sensor 36041: Seite 1, 790 Ergebnisse
Sensor 28607: Seite 1, 611 Ergebnisse
Sensor 28746: Seite 1, 1000 Ergebnisse
Sensor 28746: Seite 2, 162 Ergebnisse
Sensor 28675: Seite 1, 878 Ergebnisse
Sensor 28684: Seite 1, 1000 Ergebnisse
Sensor 28684: Seite 2, 72 Ergebnisse
Sensor 28629: Seite 1, 739 Ergebnisse
Sensor 35685: Seite 1, 768 Ergebnisse
Sensor 36113: Seite 1, 838 Ergebnisse
Sensor 28736: Seite 1, 1000 Ergebnisse
Sensor 28736: Seite 2, 50 Ergebnisse
Sensor 28719: Seite 1, 693 Ergebnisse
Sensor 28650: Seite 1, 897 Ergebnisse
Sensor 28688: Seite 1, 974 Ergebnisse
Sensor 34878: Seite 1, 588 Ergebnisse
Sensor 28648: Seite 1, 890 Ergebnisse
Sensor 34855: Seite 1, 860 Ergebnisse
Sensor 28723: Seite 1, 860 Ergebnisse
Sensor 28610: Seite 1, 871 Ergebnisse
Sensor 23600: Seite 1, 837 Ergebnisse
Sensor 28705: Seite 1, 655 Ergebnisse
Sensor 23424: Seite 1, 693 Ergebnisse
Sensor 36241: Seite 1, 751 Ergebnisse
Sensor 28643: Seite 1, 676 Ergebnisse
Sensor 28729: Seite 1, 684 Ergebnisse
Sensor 28630: Seite 1, 705 Ergebnisse
Sensor 23021: Seite 1, 1000 Ergebnisse
Sensor 23021: Seite 2, 638 Ergebnisse
Sensor 23073: Seite 1, 1000 Ergebnisse
Sensor 23073: Seite 2, 645 Ergebnisse
Sensor 28644: Seite 1, 1000 Ergebnisse
Sensor 28644: Seite 2, 974 Ergebnisse
Sensor 28727: Seite 1, 1000 Ergebnisse
Sensor 28727: Seite 2, 541 Ergebnisse
Sensor 28744: Seite 1, 1000 Ergebnisse
Sensor 28744: Seite 2, 692 Ergebnisse
Sensor 28745: Seite 1, 1000 Ergebnisse
Sensor 28745: Seite 2, 780 Ergebnisse
Sensor 28748: Seite 1, 1000 Ergebnisse
Sensor 28748: Seite 2, 568 Ergebnisse
Sensor 35193: Seite 1, 1000 Ergebnisse
Sensor 35193: Seite 2, 545 Ergebnisse
Sensor 35511: Seite 1, 1000 Ergebnisse
Sensor 35511: Seite 2, 193 Ergebnisse
Sensor 35768: Seite 1, 1000 Ergebnisse
Sensor 35768: Seite 2, 412 Ergebnisse
Sensor 35840: Seite 1, 1000 Ergebnisse
Sensor 35840: Seite 2, 571 Ergebnisse
Sensor 35922: Seite 1, 804 Ergebnisse
Sensor 36062: Seite 1, 1000 Ergebnisse
Sensor 36062: Seite 2, 778 Ergebnisse
Sensor 36070: Seite 1, 1000 Ergebnisse
Sensor 36070: Seite 2, 430 Ergebnisse
Sensor 36083: Seite 1, 1000 Ergebnisse
Sensor 36083: Seite 2, 483 Ergebnisse
Sensor 36096: Seite 1, 1000 Ergebnisse
Sensor 36096: Seite 2, 116 Ergebnisse
Sensor 36135: Seite 1, 1000 Ergebnisse
Sensor 36135: Seite 2, 385 Ergebnisse
Sensor 36015: Seite 1, 1000 Ergebnisse
Sensor 36015: Seite 2, 221 Ergebnisse
Sensor 28600: Seite 1, 1000 Ergebnisse
Sensor 28600: Seite 2, 58 Ergebnisse
Sensor 28652: Seite 1, 1000 Ergebnisse
Sensor 28652: Seite 2, 18 Ergebnisse
Sensor 28697: Seite 1, 726 Ergebnisse
Sensor 28700: Seite 1, 688 Ergebnisse
Sensor 28710: Seite 1, 1000 Ergebnisse
Sensor 28710: Seite 2, 258 Ergebnisse
Sensor 35195: Seite 1, 1000 Ergebnisse
Sensor 35195: Seite 2, 250 Ergebnisse
Sensor 35782: Seite 1, 572 Ergebnisse
Sensor 35904: Seite 1, 673 Ergebnisse
Sensor 35926: Seite 1, 1000 Ergebnisse
Sensor 35926: Seite 2, 258 Ergebnisse
Sensor 36119: Seite 1, 1000 Ergebnisse
Sensor 36119: Seite 2, 210 Ergebnisse
Sensor 36275: Seite 1, 981 Ergebnisse
Sensor 36384: Seite 1, 801 Ergebnisse
Sensor 35767: Seite 1, 1000 Ergebnisse
Sensor 35767: Seite 2, 4 Ergebnisse
Sensor 28631: Seite 1, 789 Ergebnisse
Sensor 28731: Seite 1, 1000 Ergebnisse
Sensor 28731: Seite 2, 112 Ergebnisse
Sensor 35686: Seite 1, 664 Ergebnisse
Sensor 28721: Seite 1, 651 Ergebnisse
Sensor 28604: Seite 1, 809 Ergebnisse
Sensor 28742: Seite 1, 766 Ergebnisse
Sensor 36469: Seite 1, 679 Ergebnisse
Sensor 28703: Seite 1, 698 Ergebnisse
Sensor 28707: Seite 1, 578 Ergebnisse
Sensor 28667: Seite 1, 665 Ergebnisse
Sensor 35025: Seite 1, 1000 Ergebnisse
Sensor 35025: Seite 2, 229 Ergebnisse
Sensor 28599: Seite 1, 671 Ergebnisse
Sensor 35575: Seite 1, 610 Ergebnisse
Sensor 35180: Seite 1, 659 Ergebnisse
Sensor 28594: Seite 1, 1000 Ergebnisse
Sensor 28594: Seite 2, 791 Ergebnisse
Sensor 36040: Seite 1, 970 Ergebnisse
Sensor 28747: Seite 1, 861 Ergebnisse
Sensor 28602: Seite 1, 1000 Ergebnisse
Sensor 28602: Seite 2, 363 Ergebnisse
Sensor 35086: Seite 1, 794 Ergebnisse
Sensor 28639: Seite 1, 819 Ergebnisse
Sensor 28603: Seite 1, 1000 Ergebnisse
Sensor 28603: Seite 2, 73 Ergebnisse
Sensor 5078858: Seite 1, 870 Ergebnisse
Sensor 5079508: Seite 1, 1 Ergebnisse
Sensor 5078326: Seite 1, 16 Ergebnisse
Sensor 5078733: Seite 1, 238 Ergebnisse
Sensor 5079509: Seite 1, 1 Ergebnisse
Sensor 5078840: Seite 1, 25 Ergebnisse
Sensor 8740157: Seite 1, 670 Ergebnisse
Sensor 5078530: Seite 1, 232 Ergebnisse
Sensor 11382585: Seite 1, 438 Ergebnisse
Sensor 7775432: Seite 1, 739 Ergebnisse
Sensor 8623290: Seite 1, 674 Ergebnisse
Sensor 7774877: Seite 1, 736 Ergebnisse
Sensor 7774981: Seite 1, 741 Ergebnisse
Sensor 7774145: Seite 1, 739 Ergebnisse
Sensor 7774357: Seite 1, 738 Ergebnisse
Sensor 7774212: Seite 1, 733 Ergebnisse
Sensor 7974424: Seite 1, 682 Ergebnisse
Sensor 7772771: Seite 1, 743 Ergebnisse
Sensor 8613243: Seite 1, 676 Ergebnisse
Sensor 8622667: Seite 1, 512 Ergebnisse
Sensor 8613197: Seite 1, 682 Ergebnisse
Sensor 7773181: Seite 1, 736 Ergebnisse
Sensor 7774503: Seite 1, 676 Ergebnisse
Sensor 8622234: Seite 1, 648 Ergebnisse
Sensor 8613267: Seite 1, 673 Ergebnisse
Sensor 7774133: Seite 1, 723 Ergebnisse
Sensor 7772716: Seite 1, 739 Ergebnisse
Sensor 8613521: Seite 1, 570 Ergebnisse
Sensor 8622319: Seite 1, 667 Ergebnisse
Sensor 7775196: Seite 1, 696 Ergebnisse
Sensor 7772851: Seite 1, 696 Ergebnisse
Sensor 7775596: Seite 1, 419 Ergebnisse
Sensor 7773100: Seite 1, 692 Ergebnisse
Sensor 8613248: Seite 1, 682 Ergebnisse
Sensor 8613193: Seite 1, 679 Ergebnisse
Sensor 8613256: Seite 1, 678 Ergebnisse
Sensor 8613278: Seite 1, 599 Ergebnisse
Sensor 7775163: Seite 1, 573 Ergebnisse
Sensor 8613616: Seite 1, 662 Ergebnisse
Sensor 7773251: Seite 1, 698 Ergebnisse
Sensor 15152083: Seite 1, 50 Ergebnisse
Sensor 7775691: Seite 1, 627 Ergebnisse
Sensor 8613330: Seite 1, 677 Ergebnisse
Sensor 7774080: Seite 1, 685 Ergebnisse
Sensor 8613149: Seite 1, 675 Ergebnisse
Sensor 8613220: Seite 1, 680 Ergebnisse
Sensor 7774576: Seite 1, 737 Ergebnisse
Sensor 8740159: Seite 1, 586 Ergebnisse
Sensor 8622708: Seite 1, 495 Ergebnisse
Sensor 7775598: Seite 1, 611 Ergebnisse
Sensor 7772957: Seite 1, 724 Ergebnisse
Sensor 7773235: Seite 1, 650 Ergebnisse
Sensor 8613024: Seite 1, 585 Ergebnisse
Sensor 8613233: Seite 1, 667 Ergebnisse
Sensor 7775617: Seite 1, 738 Ergebnisse
Sensor 7775244: Seite 1, 730 Ergebnisse
Sensor 9020849: Seite 1, 645 Ergebnisse
Sensor 7773217: Seite 1, 737 Ergebnisse
Sensor 8613297: Seite 1, 361 Ergebnisse
Sensor 10489109: Seite 1, 519 Ergebnisse
Sensor 11382584: Seite 1, 441 Ergebnisse
Sensor 8613102: Seite 1, 669 Ergebnisse
Sensor 7776565: Seite 1, 708 Ergebnisse
Sensor 8613337: Seite 1, 569 Ergebnisse
Sensor 8750172: Seite 1, 586 Ergebnisse
Sensor 7776501: Seite 1, 731 Ergebnisse
Sensor 7776978: Seite 1, 432 Ergebnisse
Sensor 8613199: Seite 1, 493 Ergebnisse
Sensor 7776621: Seite 1, 651 Ergebnisse
Sensor 7776559: Seite 1, 683 Ergebnisse
Sensor 7776591: Seite 1, 713 Ergebnisse
Sensor 10491957: Seite 1, 518 Ergebnisse
Sensor 8613351: Seite 1, 674 Ergebnisse
Sensor 8613230: Seite 1, 653 Ergebnisse
Sensor 14850748: Seite 1, 83 Ergebnisse
Sensor 8613253: Seite 1, 670 Ergebnisse
Sensor 10970498: Seite 1, 480 Ergebnisse
Sensor 10962240: Seite 1, 481 Ergebnisse
Sensor 8613294: Seite 1, 685 Ergebnisse
Sensor 8613179: Seite 1, 673 Ergebnisse
Sensor 12334931: Seite 1, 347 Ergebnisse
Sensor 8613338: Seite 1, 542 Ergebnisse
Sensor 7902554: Seite 1, 365 Ergebnisse
Sensor 7970414: Seite 1, 581 Ergebnisse
Sensor 8613432: Seite 1, 596 Ergebnisse
Sensor 7974590: Seite 1, 602 Ergebnisse
Sensor 8613414: Seite 1, 697 Ergebnisse
Sensor 8613466: Seite 1, 683 Ergebnisse
Sensor 8613434: Seite 1, 698 Ergebnisse
Sensor 8613353: Seite 1, 696 Ergebnisse
Sensor 8613422: Seite 1, 675 Ergebnisse
Sensor 8613696: Seite 1, 673 Ergebnisse
Sensor 8613630: Seite 1, 680 Ergebnisse
Sensor 8622686: Seite 1, 662 Ergebnisse
Sensor 8613608: Seite 1, 691 Ergebnisse
Sensor 8613628: Seite 1, 680 Ergebnisse
Sensor 8613437: Seite 1, 676 Ergebnisse
Sensor 8613649: Seite 1, 675 Ergebnisse
Sensor 8622246: Seite 1, 680 Ergebnisse
Sensor 8613076: Seite 1, 548 Ergebnisse
Sensor 8613218: Seite 1, 636 Ergebnisse
Sensor 8613129: Seite 1, 685 Ergebnisse
Sensor 11042698: Seite 1, 403 Ergebnisse
Sensor 8613343: Seite 1, 596 Ergebnisse
Sensor 8613121: Seite 1, 589 Ergebnisse
Sensor 8622687: Seite 1, 645 Ergebnisse
Sensor 8622685: Seite 1, 653 Ergebnisse
Sensor 8613570: Seite 1, 677 Ergebnisse
Sensor 8613364: Seite 1, 679 Ergebnisse
Sensor 8613615: Seite 1, 695 Ergebnisse
Sensor 8622215: Seite 1, 692 Ergebnisse
Sensor 8622279: Seite 1, 696 Ergebnisse
Sensor 8622661: Seite 1, 357 Ergebnisse
Sensor 8613603: Seite 1, 699 Ergebnisse
Sensor 8613697: Seite 1, 680 Ergebnisse
Sensor 8613444: Seite 1, 681 Ergebnisse
Sensor 8622714: Seite 1, 684 Ergebnisse
Sensor 14850756: Seite 1, 83 Ergebnisse
Sensor 8613427: Seite 1, 680 Ergebnisse
Sensor 8613564: Seite 1, 696 Ergebnisse
Sensor 8613586: Seite 1, 599 Ergebnisse
Sensor 8624481: Seite 1, 529 Ergebnisse
Sensor 8613471: Seite 1, 588 Ergebnisse
Sensor 8613598: Seite 1, 658 Ergebnisse
Sensor 8613428: Seite 1, 681 Ergebnisse
Sensor 8622321: Seite 1, 698 Ergebnisse
Sensor 8627099: Seite 1, 674 Ergebnisse
Sensor 8632843: Seite 1, 668 Ergebnisse
Sensor 8627967: Seite 1, 538 Ergebnisse
Sensor 8644664: Seite 1, 596 Ergebnisse
Sensor 8692366: Seite 1, 540 Ergebnisse
Sensor 8740158: Seite 1, 674 Ergebnisse
Sensor 9021127: Seite 1, 643 Ergebnisse
Sensor 9021933: Seite 1, 644 Ergebnisse
Sensor 14684288: Seite 1, 104 Ergebnisse
Sensor 14684268: Seite 1, 104 Ergebnisse
Sensor 14684277: Seite 1, 104 Ergebnisse
Sensor 10418727: Seite 1, 531 Ergebnisse
Sensor 10419362: Seite 1, 531 Ergebnisse
Sensor 10425457: Seite 1, 530 Ergebnisse
Sensor 10419661: Seite 1, 529 Ergebnisse
Sensor 10579599: Seite 1, 517 Ergebnisse
Sensor 10633436: Seite 1, 509 Ergebnisse
Sensor 10714173: Seite 1, 502 Ergebnisse
Sensor 10714170: Seite 1, 403 Ergebnisse
Sensor 10725457: Seite 1, 502 Ergebnisse
Sensor 10725453: Seite 1, 501 Ergebnisse
Sensor 10793553: Seite 1, 497 Ergebnisse
Sensor 10793874: Seite 1, 371 Ergebnisse
Sensor 12660435: Seite 1, 313 Ergebnisse
Sensor 10983944: Seite 1, 481 Ergebnisse
Sensor 10984424: Seite 1, 479 Ergebnisse
Sensor 10985447: Seite 1, 478 Ergebnisse
Sensor 10986422: Seite 1, 460 Ergebnisse
Sensor 10996698: Seite 1, 475 Ergebnisse
Sensor 12334924: Seite 1, 343 Ergebnisse
Sensor 12334921: Seite 1, 346 Ergebnisse
Sensor 12334930: Seite 1, 345 Ergebnisse
Sensor 12334923: Seite 1, 344 Ergebnisse
Sensor 14684290: Seite 1, 104 Ergebnisse
Sensor 14860316: Seite 1, 83 Ergebnisse
Sensor 14684266: Seite 1, 104 Ergebnisse
Sensor 15151412: Seite 1, 50 Ergebnisse
Sensor 14840190: Seite 1, 85 Ergebnisse
Sensor 14851298: Seite 1, 82 Ergebnisse
Sensor 15151409: Seite 1, 50 Ergebnisse
Sensor 15151407: Seite 1, 49 Ergebnisse
Sensor 15151399: Seite 1, 50 Ergebnisse
Sensor 15151408: Seite 1, 50 Ergebnisse
Sensor 14860319: Seite 1, 83 Ergebnisse
Sensor 15151395: Seite 1, 50 Ergebnisse
Sensor 14860315: Seite 1, 83 Ergebnisse
Sensor 14860314: Seite 1, 83 Ergebnisse
Sensor 15151410: Seite 1, 50 Ergebnisse
Sensor 14923200: Seite 1, 74 Ergebnisse
Sensor 14923207: Seite 1, 74 Ergebnisse
Sensor 14923198: Seite 1, 74 Ergebnisse
Sensor 14927969: Seite 1, 74 Ergebnisse
218325

[{'date': '2020-04-19', 'value': 15.47079155},
 {'date': '2020-04-20', 'value': 18.283595555217396},
 {'date': '2020-04-21', 'value': 21.383079124782608},
 {'date': '2020-04-22', 'value': 25.39541200235294},
 {'date': '2020-04-23', 'value': 33.468364075500006},
 {'date': '2020-04-24', 'value': 38.92472432076923},
 {'date': '2020-04-25', 'value': 19.31229564},
 {'date': '2020-04-26', 'value': 13.113599422631578},
 {'date': '2020-04-27', 'value': 27.080648819473684},
 {'date': '2020-04-28', 'value': 30.36928313047619},
 {'date': '2020-04-29', 'value': 31.275470932000005},
 {'date': '2020-04-30', 'value': 39.26145308136363},
 {'date': '2020-05-01', 'value': 23.237876226956523},
 {'date': '2020-05-02', 'value': 22.421473903636365},
 {'date': '2020-05-03', 'value': 21.686804228},
 {'date': '2020-05-04', 'value': 23.83276675294118},
 {'date': '2020-05-05', 'value': 37.05104049285714},
 {'date': '2020-05-06', 'value': 37.071689254999995},
 {'date': '2020-05-07', 'value': 34.058707964999996},
 {'date': '2020-05-08', 'value': 29.886340671999996},
 {'date': '2020-05-09', 'value': 25.363298676250004},
 {'date': '2020-05-10', 'value': 21.33445074952381},
 {'date': '2020-05-11', 'value': 30.887106842},
 {'date': '2020-05-12', 'value': 40.685954979},
 {'date': '2020-05-13', 'value': 42.7325299},
 {'date': '2020-05-14', 'value': 32.90755437333333},
 {'date': '2020-05-15', 'value': 47.49275862333334},
 {'date': '2020-05-16', 'value': 29.050099238461538},
 {'date': '2020-05-17', 'value': 24.218883271764707},
 {'date': '2020-05-18', 'value': 35.396522496470595},
 {'date': '2020-05-19', 'value': 45.024391876875},
 {'date': '2020-05-20', 'value': 35.48750281368421},
 {'date': '2020-05-21', 'value': 26.232046977499998},
 {'date': '2020-05-22', 'value': 28.38430066470588},
 {'date': '2020-05-23', 'value': 29.01676118473685},
 {'date': '2020-05-24', 'value': 25.052245755999998},
 {'date': '2020-05-25', 'value': 28.940924373181815},
 {'date': '2020-05-26', 'value': 31.31527818263158},
 {'date': '2020-05-27', 'value': 26.422831425833337},
 {'date': '2020-05-28', 'value': 33.57548640461538},
 {'date': '2020-05-29', 'value': 37.68964503666666},
 {'date': '2020-05-30', 'value': 23.321097105},
 {'date': '2020-06-04', 'value': 38.21733902714286},
 {'date': '2020-06-05', 'value': 38.415981355454555},
 {'date': '2020-06-06', 'value': 34.451056566666665},
 {'date': '2020-06-07', 'value': 18.368019338},
 {'date': '2020-06-08', 'value': 28.277190577},
 {'date': '2020-06-09', 'value': 33.652379741304344},
 {'date': '2020-06-10', 'value': 31.088755773181823},
 {'date': '2020-06-11', 'value': 32.711149261875},
 {'date': '2020-06-12', 'value': 30.18245123071429},
 {'date': '2020-06-13', 'value': 32.85923072117647},
 {'date': '2020-06-14', 'value': 28.622913501250004},
 {'date': '2020-06-15', 'value': 27.432601751333333},
 {'date': '2020-06-16', 'value': 25.76286840272727},
 {'date': '2020-06-17', 'value': 31.957174337222227},
 {'date': '2020-06-18', 'value': 30.468597735333333},
 {'date': '2020-06-19', 'value': 33.74659526666666},
 {'date': '2020-06-20', 'value': 28.121176914375003},
 {'date': '2020-06-21', 'value': 25.96333338777778},
 {'date': '2020-06-22', 'value': 29.334342382727275},
 {'date': '2020-06-23', 'value': 34.518486774},
 {'date': '2020-06-24', 'value': 33.89057210789473},
 {'date': '2020-06-25', 'value': 26.408100679374996},
 {'date': '2020-06-26', 'value': 27.61131563071428},
 {'date': '2020-06-27', 'value': 27.688076648124998},
 {'date': '2020-06-28', 'value': 22.1016130425},
 {'date': '2020-06-29', 'value': 40.71079807190477},
 {'date': '2020-06-30', 'value': 26.044438944},
 {'date': '2020-07-01', 'value': 40.34813122210526},
 {'date': '2020-07-02', 'value': 31.665583835},
 {'date': '2020-07-03', 'value': 17.942944553333334},
 {'date': '2020-07-04', 'value': 19.194233383684214},
 {'date': '2020-07-05', 'value': 21.98150049615385},
 {'date': '2020-07-06', 'value': 14.314138525},
 {'date': '2020-07-07', 'value': 27.057469799285712},
 {'date': '2020-07-08', 'value': 21.629459811818183},
 {'date': '2020-07-09', 'value': 35.99640003142857},
 {'date': '2020-07-10', 'value': 36.15281801090909},
 {'date': '2020-07-11', 'value': 22.918166106},
 {'date': '2020-07-12', 'value': 19.93866008705882},
 {'date': '2020-07-13', 'value': 29.496546843809526},
 {'date': '2020-07-14', 'value': 31.47923774142857},
 {'date': '2020-07-15', 'value': 32.72184649399999},
 {'date': '2020-07-16', 'value': 29.618070286999995},
 {'date': '2020-07-17', 'value': 26.583063255263156},
 {'date': '2020-07-18', 'value': 23.645018613636363},
 {'date': '2020-07-19', 'value': 19.747182777391306},
 {'date': '2020-07-20', 'value': 25.867305394},
 {'date': '2020-07-21', 'value': 34.46284747722223},
 {'date': '2020-07-22', 'value': 31.803624612222222},
 {'date': '2020-07-23', 'value': 27.004024115238092},
 {'date': '2020-07-24', 'value': 30.825511496521738},
 {'date': '2020-07-25', 'value': 27.276550998181822},
 {'date': '2020-07-26', 'value': 23.83988267222222},
 {'date': '2020-07-27', 'value': 29.096053179130436},
 {'date': '2020-07-28', 'value': 26.085795423684207},
 {'date': '2020-07-29', 'value': 31.161624424285712},
 {'date': '2020-07-30', 'value': 21.883306397499997},
 {'date': '2020-08-04', 'value': 16.870347103333334},
 {'date': '2020-08-06', 'value': 38.352423304999995},
 {'date': '2020-08-07', 'value': 32.34909982136364},
 {'date': '2020-08-08', 'value': 18.44044107130435},
 {'date': '2020-08-09', 'value': 14.8104512},
 {'date': '2020-08-10', 'value': 22.466511205217394},
 {'date': '2020-08-11', 'value': 34.48212409913043},
 {'date': '2020-08-12', 'value': 30.570982394999998},
 {'date': '2020-08-13', 'value': 36.71238572652173},
 {'date': '2020-08-14', 'value': 31.29707148347827},
 {'date': '2020-08-15', 'value': 23.44888049272727},
 {'date': '2020-08-16', 'value': 24.48977115235294},
 {'date': '2020-08-17', 'value': 31.900691784782616},
 {'date': '2020-08-18', 'value': 33.113984637391304},
 {'date': '2020-08-19', 'value': 33.406921901304344},
 {'date': '2020-08-20', 'value': 29.564165911818183},
 {'date': '2020-08-21', 'value': 34.36877803652173},
 {'date': '2020-08-22', 'value': 24.937391382272732},
 {'date': '2020-08-23', 'value': 28.315072904285714},
 {'date': '2020-08-24', 'value': 31.743383125652173},
 {'date': '2020-08-25', 'value': 30.3873882826087},
 {'date': '2020-08-26', 'value': 37.20314732043479},
 {'date': '2020-08-27', 'value': 35.837749225},
 {'date': '2020-08-28', 'value': 41.44585593956522},
 {'date': '2020-08-29', 'value': 27.55850812086957},
 {'date': '2020-08-30', 'value': 27.676306809130427},
 {'date': '2020-08-31', 'value': 40.53823848608696},
 {'date': '2020-09-01', 'value': 40.88380426263158},
 {'date': '2020-09-02', 'value': 47.799207712727274},
 {'date': '2020-09-03', 'value': 36.08572663521739},
 {'date': '2020-09-04', 'value': 20.294995143333335},
 {'date': '2020-09-05', 'value': 24.985647181578944},
 {'date': '2020-09-06', 'value': 28.663589718000004},
 {'date': '2020-09-07', 'value': 40.20485179772727},
 {'date': '2020-09-08', 'value': 33.45631674521739},
 {'date': '2020-09-09', 'value': 39.9091188725},
 {'date': '2020-09-10', 'value': 31.754899600869557},
 {'date': '2020-09-11', 'value': 36.08245184739131},
 {'date': '2020-09-12', 'value': 27.312957868260863},
 {'date': '2020-09-13', 'value': 34.74746134956522},
 {'date': '2020-09-14', 'value': 38.9558834125},
 {'date': '2020-09-15', 'value': 40.056751981304345},
 {'date': '2020-09-16', 'value': 44.17411064238096},
 {'date': '2020-09-17', 'value': 49.52531692},
 {'date': '2020-09-18', 'value': 38.780646556956526},
 {'date': '2020-09-19', 'value': 31.482497650952382},
 {'date': '2020-09-20', 'value': 29.981318628260873},
 {'date': '2020-09-21', 'value': 43.28201742695652},
 {'date': '2020-09-22', 'value': 43.48129156434783},
 {'date': '2020-09-23', 'value': 34.8828796},
 {'date': '2020-09-24', 'value': 46.56311188650001},
 {'date': '2020-09-25', 'value': 41.00142825217392},
 {'date': '2020-09-26', 'value': 28.416397985217394},
 {'date': '2020-09-27', 'value': 24.570485617826083},
 {'date': '2020-09-28', 'value': 30.791200476086964},
 {'date': '2020-09-29', 'value': 31.21884723173913},
 {'date': '2020-09-30', 'value': 40.26287899608695},
 {'date': '2020-10-01', 'value': 36.55239485826087},
 {'date': '2020-10-02', 'value': 41.42422492869565},
 {'date': '2020-10-03', 'value': 31.987773589130438},
 {'date': '2020-10-04', 'value': 16.490043126666666},
 {'date': '2020-10-05', 'value': 25.048156898461535},
 {'date': '2020-10-06', 'value': 35.63858957625},
 {'date': '2020-10-07', 'value': 35.10389754347827},
 {'date': '2020-10-08', 'value': 34.39431697260869},
 {'date': '2020-10-09', 'value': 43.04686013550001},
 {'date': '2020-10-10', 'value': 34.348600504347836},
 {'date': '2020-10-11', 'value': 29.553519462631577},
 {'date': '2020-10-12', 'value': 29.680727818},
 {'date': '2020-10-13', 'value': 16.230513785},
 {'date': '2020-10-14', 'value': 28.013885155263164},
 {'date': '2020-10-15', 'value': 37.41714731681819},
 {'date': '2020-10-16', 'value': 42.28403472749999},
 {'date': '2020-10-17', 'value': 24.903556933333334},
 {'date': '2020-10-18', 'value': 17.15343472083333},
 {'date': '2020-10-19', 'value': 31.23219501541666},
 {'date': '2020-10-20', 'value': 39.61017271173913},
 {'date': '2020-10-21', 'value': 35.37603820875},
 {'date': '2020-10-22', 'value': 40.74997197833333},
 {'date': '2020-10-23', 'value': 43.42070646791666},
 {'date': '2020-10-24', 'value': 44.80437676666668},
 {'date': '2020-10-25', 'value': 21.543422723200003},
 {'date': '2020-10-26', 'value': 29.404702198999995},
 {'date': '2020-10-27', 'value': 30.672037242},
 {'date': '2020-10-28', 'value': 30.733728701666664},
 {'date': '2020-10-29', 'value': 33.53087713391304},
 {'date': '2020-10-30', 'value': 40.25776803},
 {'date': '2020-10-31', 'value': 32.505295825},
 {'date': '2020-11-01', 'value': 26.710244464736842},
 {'date': '2020-11-02', 'value': 39.199267232083336},
 {'date': '2020-11-03', 'value': 28.50956522},
 {'date': '2020-11-04', 'value': 29.877119496363637},
 {'date': '2020-11-05', 'value': 31.909436609166665},
 {'date': '2020-11-06', 'value': 28.181023850000003},
 {'date': '2020-11-07', 'value': 23.585314000666667},
 {'date': '2020-11-08', 'value': 20.714208669523813},
 {'date': '2020-11-09', 'value': 20.87757535705882},
 {'date': '2020-11-10', 'value': 19.59348039541667},
 {'date': '2020-11-11', 'value': 11.811138327916668},
 {'date': '2020-11-12', 'value': 19.6045779275},
 {'date': '2020-11-13', 'value': 12.64683888333333},
 {'date': '2020-11-14', 'value': 6.58274724857143},
 {'date': '2020-11-15', 'value': 10.274003105416668},
 {'date': '2020-11-16', 'value': 35.48387715826087},
 {'date': '2020-11-17', 'value': 38.049602255909086},
 {'date': '2020-11-18', 'value': 27.386079357083343},
 {'date': '2020-11-19', 'value': 23.83079660125},
 {'date': '2020-11-20', 'value': 22.066362126666665},
 {'date': '2020-11-21', 'value': 19.97425516826087},
 {'date': '2020-11-22', 'value': 10.993139552},
 {'date': '2020-11-23', 'value': 45.02727085291667},
 {'date': '2020-11-24', 'value': 34.533906210000005},
 {'date': '2020-11-25', 'value': 35.481863795555554},
 {'date': '2020-11-26', 'value': 47.96105967357143},
 {'date': '2020-11-27', 'value': 39.372210329999994},
 {'date': '2020-11-28', 'value': 22.966150930416664},
 {'date': '2020-11-29', 'value': 23.17209696875},
 {'date': '2020-11-30', 'value': 20.795359434583336},
 {'date': '2020-12-01', 'value': 22.97194061875},
 {'date': '2020-12-02', 'value': 25.213006470000003},
 {'date': '2020-12-03', 'value': 12.468284019999999},
 {'date': '2020-12-04', 'value': 28.517129075454548},
 {'date': '2020-12-05', 'value': 25.910215410769226},
 {'date': '2020-12-06', 'value': 21.477680771666666},
 {'date': '2020-12-07', 'value': 14.459396420833334},
 {'date': '2020-12-08', 'value': 23.524024649999998},
 {'date': '2020-12-09', 'value': 26.719852792916665},
 {'date': '2020-12-10', 'value': 22.900293726666664},
 {'date': '2020-12-11', 'value': 27.005170167857138},
 {'date': '2020-12-13', 'value': 13.782797},
 {'date': '2020-12-14', 'value': 27.598466365833332},
 {'date': '2020-12-15', 'value': 27.271774710416665},
 {'date': '2020-12-16', 'value': 24.98627554000001},
 {'date': '2020-12-17', 'value': 23.199586926956524},
 {'date': '2020-12-18', 'value': 26.18588275166667},
 {'date': '2020-12-19', 'value': 22.205644475833335},
 {'date': '2020-12-20', 'value': 24.498626656666662},
 {'date': '2020-12-21', 'value': 24.888459252500002},
 {'date': '2020-12-22', 'value': 37.64171460071428},
 {'date': '2020-12-23', 'value': 26.596499500000004},
 {'date': '2020-12-24', 'value': 40.95115370956521},
 {'date': '2020-12-25', 'value': 30.63356572826087},
 {'date': '2020-12-26', 'value': 22.80988866826087},
 {'date': '2020-12-27', 'value': 12.72692215},
 {'date': '2020-12-29', 'value': 72.90359875200001},
 {'date': '2020-12-30', 'value': 68.51185393681818},
 {'date': '2020-12-31', 'value': 64.95507055384616},
 {'date': '2021-01-01', 'value': 21.945089693750003},
 {'date': '2021-01-02', 'value': 27.55045738},
 {'date': '2021-01-03', 'value': 32.71800062454545},
 {'date': '2021-01-04', 'value': 35.836561089565215},
 {'date': '2021-01-05', 'value': 32.5473003765},
 {'date': '2021-01-06', 'value': 57.921421652173905},
 {'date': '2021-01-07', 'value': 43.57923777782609},
 {'date': '2021-01-08', 'value': 34.167437189999994},
 {'date': '2021-01-09', 'value': 33.55821236521739},
 {'date': '2021-01-10', 'value': 27.28335256833333},
 {'date': '2021-01-11', 'value': 20.044051805652174},
 {'date': '2021-01-12', 'value': 25.386380978500004},
 {'date': '2021-01-13', 'value': 39.20103137521739},
 {'date': '2021-01-14', 'value': 55.964642759499995},
 {'date': '2021-01-15', 'value': 65.85399177652174},
 {'date': '2021-01-16', 'value': 32.231790356521735},
 {'date': '2021-01-17', 'value': 39.629337365217395},
 {'date': '2021-01-18', 'value': 61.16142579444444},
 {'date': '2021-01-19', 'value': 51.18848659478261},
 {'date': '2021-01-20', 'value': 63.887184605},
 {'date': '2021-01-21', 'value': 56.68912784578947},
 {'date': '2021-01-22', 'value': 48.5189135275},
 {'date': '2021-01-26', 'value': 38.23819293333333},
 {'date': '2021-01-27', 'value': 41.38744488086957},
 {'date': '2021-01-28', 'value': 39.51759379130435},
 {'date': '2021-01-29', 'value': 40.86133740695652},
 {'date': '2021-01-30', 'value': 39.52790204916666},
 {'date': '2021-01-31', 'value': 28.665966595833336},
 {'date': '2021-02-01', 'value': 22.10244194},
 {'date': '2021-02-02', 'value': 33.41888122545454},
 {'date': '2021-02-03', 'value': 25.846910711304353},
 {'date': '2021-02-04', 'value': 28.78363172434782},
 {'date': '2021-02-05', 'value': 43.53938631043478},
 {'date': '2021-02-06', 'value': 29.56622274826087},
 {'date': '2021-02-07', 'value': 26.09592023782609},
 {'date': '2021-02-08', 'value': 37.272198034347824},
 {'date': '2021-02-09', 'value': 37.452676196521736},
 {'date': '2021-02-10', 'value': 37.16398832565218},
 {'date': '2021-02-11', 'value': 42.17155918565218},
 {'date': '2021-02-12', 'value': 28.536576909999997},
 {'date': '2021-02-13', 'value': 27.563391470434784},
 {'date': '2021-02-14', 'value': 18.438127643913045},
 {'date': '2021-02-15', 'value': 27.105950964999998},
 {'date': '2021-02-16', 'value': 35.86740561142857},
 {'date': '2021-02-17', 'value': 35.206518627826085},
 {'date': '2021-02-18', 'value': 42.19102907863636},
 {'date': '2021-02-19', 'value': 28.979139661538458},
 {'date': '2021-02-20', 'value': 51.110291},
 {'date': '2021-02-21', 'value': 30.789888751904765},
 {'date': '2021-02-22', 'value': 42.59665745565217},
 {'date': '2021-02-23', 'value': 60.16765473695652},
 {'date': '2021-02-24', 'value': 54.94759642956521},
 {'date': '2021-02-25', 'value': 58.54722902130435},
 {'date': '2021-02-26', 'value': 52.86637253818182},
 {'date': '2021-02-27', 'value': 39.99349501333333},
 {'date': '2021-03-01', 'value': 51.2056139247619},
 {'date': '2021-03-02', 'value': 45.50231665478261},
 {'date': '2021-03-03', 'value': 59.42038449499999},
 {'date': '2021-03-04', 'value': 51.05033013380952},
 {'date': '2021-03-05', 'value': 47.5394431878261},
 {'date': '2021-03-06', 'value': 42.60189592391304},
 {'date': '2021-03-07', 'value': 35.11769420956521},
 {'date': '2021-03-08', 'value': 51.29551303608696},
 {'date': '2021-03-09', 'value': 36.87481510562499},
 {'date': '2021-03-10', 'value': 30.206569835000003},
 {'date': '2021-03-11', 'value': 39.555173359375},
 {'date': '2021-03-12', 'value': 56.1427934935294},
 {'date': '2021-03-13', 'value': 56.11207760913043},
 {'date': '2021-03-14', 'value': 40.779619265652165},
 {'date': '2021-03-15', 'value': 41.439991407826085},
 {'date': '2021-03-16', 'value': 21.63197937625},
 {'date': '2021-03-17', 'value': 39.25946516315789},
 {'date': '2021-03-18', 'value': 34.37537248391304},
 {'date': '2021-03-19', 'value': 36.48758498565217},
 {'date': '2021-03-20', 'value': 37.699423427391295},
 {'date': '2021-03-21', 'value': 29.19250038869565},
 {'date': '2021-03-22', 'value': 44.32493740999999},
 {'date': '2021-03-23', 'value': 33.95886158782608},
 {'date': '2021-03-24', 'value': 39.28412189117647},
 {'date': '2021-03-25', 'value': 51.39532153086957},
 {'date': '2021-03-26', 'value': 57.77379423652174},
 {'date': '2021-03-27', 'value': 40.21048129318182},
 {'date': '2021-03-28', 'value': 22.039478210769232},
 {'date': '2021-03-29', 'value': 31.060867365333333},
 {'date': '2021-03-30', 'value': 47.243736919999996},
 {'date': '2021-03-31', 'value': 42.92835622136364},
 {'date': '2021-04-01', 'value': 40.728543028333334},
 {'date': '2021-04-02', 'value': 23.4422927},
 {'date': '2021-04-03', 'value': 25.324058853076924},
 {'date': '2021-04-04', 'value': 21.900922195000003},
 {'date': '2021-04-05', 'value': 31.878945706666666},
 {'date': '2021-04-06', 'value': 37.8939486075},
 {'date': '2021-04-07', 'value': 42.60846610782608},
 {'date': '2021-04-08', 'value': 50.44354183217392},
 {'date': '2021-04-09', 'value': 45.73789975090909},
 {'date': '2021-04-10', 'value': 39.84452897782609},
 {'date': '2021-04-11', 'value': 30.160578625333336},
 {'date': '2021-04-12', 'value': 46.83989660809524},
 {'date': '2021-04-13', 'value': 45.251787639999996},
 {'date': '2021-04-14', 'value': 35.092247467777774},
 {'date': '2021-04-15', 'value': 29.73546643913043},
 {'date': '2021-04-16', 'value': 31.677535289230768},
 {'date': '2021-04-17', 'value': 32.79916247909091},
 {'date': '2021-04-18', 'value': 23.05836060565218},
 {'date': '2021-04-19', 'value': 36.50067110391304},
 {'date': '2021-04-20', 'value': 35.30438862565218},
 {'date': '2021-04-21', 'value': 54.20587700125},
 {'date': '2021-04-22', 'value': 42.66325446045455},
 {'date': '2021-04-23', 'value': 39.99902956739131},
 {'date': '2021-04-24', 'value': 29.606058849999997},
 {'date': '2021-04-27', 'value': 37.163732859999996},
 {'date': '2021-04-28', 'value': 29.02130829956522},
 {'date': '2021-04-29', 'value': 32.94873291722222},
 {'date': '2021-04-30', 'value': 32.52836539470587},
 {'date': '2021-05-01', 'value': 29.180933316666668},
 {'date': '2021-05-03', 'value': 19.373863092999994},
 {'date': '2021-05-04', 'value': 55.89851221285714},
 {'date': '2021-05-05', 'value': 44.798982979047615},
 {'date': '2021-05-06', 'value': 30.03218247217392},
 {'date': '2021-05-07', 'value': 33.08515508428571},
 {'date': '2021-05-08', 'value': 24.782172349090903},
 {'date': '2021-05-09', 'value': 20.167648643333333},
 {'date': '2021-05-10', 'value': 33.348408649999996},
 {'date': '2021-05-11', 'value': 40.803690922857136},
 {'date': '2021-05-12', 'value': 35.20428385941176},
 {'date': '2021-05-13', 'value': 30.79192570833333},
 {'date': '2021-05-14', 'value': 42.05027473857143},
 {'date': '2021-05-15', 'value': 33.0972845626087},
 {'date': '2021-05-16', 'value': 26.554033075652175},
 {'date': '2021-05-17', 'value': 31.950286137619052},
 {'date': '2021-05-18', 'value': 25.983554237222226},
 {'date': '2021-05-19', 'value': 29.73345307909091},

In [ ]:
df_results = pd.DataFrame(all_daily_values)

df_results['date'] = pd.to_datetime(df_results['date'])

romania_daily = (
    df_results.groupby("date")
              .agg(romania_no2_mean=("value", "mean"))
              .reset_index()
              .sort_values("date")
)

romania_daily

           date  france_no2_mean
0    2020-04-19        15.470792
1    2020-04-20        12.541979
2    2020-04-21        11.645143
3    2020-04-22        14.698343
4    2020-04-23        17.038843
...         ...              ...
2024 2026-02-24        25.339471
2025 2026-02-25        21.874344
2026 2026-02-26        21.300665
2027 2026-02-27        26.274187
2028 2026-02-28        21.542194

[2029 rows x 2 columns]

In [ ]:
romania_daily[["date", "romania_no2_mean"]].to_csv(
    "daily_avg_romania_NO2.csv",
    index=False
)