In [1]:
#import sys
#!{sys.executable} -m pip install plotly      #falls man noch was installieren muss, geht das hiermit recht leicht

In [67]:
import requests
import urllib.parse as up
import pandas
from pandas import json_normalize
import json
base = "https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v4/jobs"
query = {
    "angebotsart": "1",
    "wo": "Schleswig-Holstein",
    #"umkreis": "200",
    #"arbeitszeit": "ho;mj",  # Semikolon bleibt bewusst erhalten
    #"page": "5",
    "size": "250",
    #"pav": "false",
}
# safe=';' sorgt dafür, dass das Semikolon nicht encodiert wird, falls die API es so erwartet
url = f"{base}?{up.urlencode(query, safe=';')}"

headers = {
    "X-API-Key": "jobboerse-jobsuche",
    #"Accept": "application/json",
    #"User-Agent": "Mozilla/5.0",
}

r = requests.get(url, headers=headers, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data= r.json()

URL: https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v4/jobs?angebotsart=1&wo=Schleswig-Holstein&size=250
Status: 200 OK
CT: application/json;charset=UTF-8

In [68]:
print(data.keys())

dict_keys(['stellenangebote', 'maxErgebnisse', 'page', 'size', 'woOutput', 'facetten'])

In [69]:
facetten=data["facetten"] #alle möglichen Eigenschaften inklusive der dort vorhanden Daten denke ich mal für Angebotsart 1
#facetten                  #aus manchen Eigenschaften werde ich aber noch nicht so richtig schlau, da keine Einheiten gegeben sind

In [70]:
#print(data.get("stellenangebote"))

In [71]:
jobs=data["stellenangebote"]
#jobs

In [72]:
df_job_SH = json_normalize(jobs)
#df_job_SH

In [73]:
df_job_SH = df_job_SH[["beruf",	"titel",	"refnr",	"arbeitgeber",	"aktuelleVeroeffentlichungsdatum",	"modifikationsTimestamp",	"eintrittsdatum",	"arbeitsort.plz",	"arbeitsort.ort",	"arbeitsort.strasse",	"arbeitsort.region",	"arbeitsort.land",	"arbeitsort.koordinaten.lat",	"arbeitsort.koordinaten.lon",	"arbeitsort.ortsteil",	"externeUrl"]]
#df_job_SH

In [75]:
all_jobs = []

for page in range(1, 3):  # immer Seite 1 als Minimum haben - geht aber auch Seite 41 bis 81
    query["page"] = page   #oben habe ich size 250 gesetzt, daher kriegt man 250 x Seitenanzahl an Ergebnissen
    url = f"{base}?{up.urlencode(query, safe=';')}"  #250 x 40 = 10000
    
    r = requests.get(url, headers=headers, timeout=30)
    data = r.json()
    
    all_jobs.extend(data["stellenangebote"])

df_job_SH = json_normalize(all_jobs) #erzeugt die Spaltenform die man unten sehen kann
df_job_SH = df_job_SH[["beruf",	#alle Spalten die man in der Rückgabe haben will - habe zB die Hashs der spezifischen Personen 
         "titel",	#mal rausgenommen, da wir damit denke eh nichts machen werden
         #"refnr",	
         #"arbeitgeber",	
         #"aktuelleVeroeffentlichungsdatum",	
         #"modifikationsTimestamp",	
         #"eintrittsdatum",	
         #"arbeitsort.plz",	
         #"arbeitsort.ort",	
         #"arbeitsort.strasse",	
         #"arbeitsort.region",	
         #"arbeitsort.land",	
         #"arbeitsort.koordinaten.lat",	
         #"arbeitsort.koordinaten.lon",	
         #"arbeitsort.ortsteil",	
         #"externeUrl"
        ]]
df_job_SH

,beruf,titel
0,Leiter/in - Maschinenanlagen,Seefahrender Ingenieur Führungs- und Waffenein...
1,Industriemechaniker/in - Maschinen- und System...,Industriemechaniker Maschinen- und Systemtechn...
2,Ingenieur/in - Elektrotechnik,PLC Development and Support Engineer (f/m/d)
3,Fachberater/in - Vertrieb,"Vertrieb Fachbereich Bauelemente (m/w/d), Lübeck"
4,Projektleiter/in,Projektleiter (m/w/d) Photovoltaik
...,...,...
495,Reifenmonteur/in,Lagermitarbeiter im Wareneingang (m/w/d) ab 14...
496,Konstruktionsmechaniker/in - Feinblechbautechnik,Konstruktionsmechaniker - Feinblechbautechnik ...
497,Lager- und Transportarbeiter/in,"Lagermitarbeiter (m/w/d) ab 14,96€ Stundenlohn"
498,Helfer/in - Metallbau,"Helfer - Metallbau (m/w/d) ab 15,29€ pro Stunde"
499,"Helfer/in - Malerei, Lackiererei","Helfer - Malerei, Lackiererei (m/w/d) Vollzeit..."

In [76]:
df_job_SH.to_csv("jobs_SH_500.csv", index=False)

In [77]:
base = "https://rest.arbeitsagentur.de/jobboerse/bewerbersuche-service/pc/v1/bewerber"
query = {
    #"angebotsart": "",
    #"was": "",
    #"ausbildungsart": "",
    "wo": "Schleswig-Holstein",  
    #"umkreis": "",
    #"angebotsart": "",
    #"arbeitszeit": "",
    #"berufserfahrung": "",
    #"vertragsart": "",
    #"page": "",  #Seiten beginnen bei 0
    "size": "250",
    
}
# safe=';' sorgt dafür, dass das Semikolon nicht encodiert wird, falls die API es so erwartet
url = f"{base}?{up.urlencode(query, safe=';')}"

headers = {
    "X-API-Key": "jobboerse-bewerbersuche-ui",
    #"Accept": "application/json",
    #"User-Agent": "Mozilla/5.0",
}

r = requests.get(url, headers=headers, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data= r.json()

URL: https://rest.arbeitsagentur.de/jobboerse/bewerbersuche-service/pc/v1/bewerber?wo=Schleswig-Holstein&size=250
Status: 200 OK
CT: application/json

In [78]:
print(data.keys())

dict_keys(['bewerber', 'maxErgebnisse', 'page', 'size', 'woOutput', 'facetten'])

In [79]:
bewerber=data["bewerber"]
bewerber

[{'refnr': '10005-135012005101862978-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T06:33:30.934',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Pförtner/in'],
  'erfahrung': {'gesamterfahrung': 'P13Y9M13D'},
  'letzteTaetigkeit': {'jahr': '2019',
   'bezeichnung': 'Helfer/in - Reinigung',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Eutin',
   'plz': '23701',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10005-115171997032452442-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T15:40:36.544',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Helfer/in - Büro, Verwaltung',
   'Kaufmann/-frau - Groß- und Außenhandel (Außenhandel)'],
  'ausbildungen': [{'jahr': 1990,
    'art': 'Kaufmann/-frau - Groß- und Außenhandel (Außenhandel)'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Handel',
     'erfahrung': 'P1Y'}],
   'gesamterfahrung': 'P8Y6M24D'},
  'letzteTaetigkeit': {'jahr': '2015',
   'bezeichnung': 'Helfer/in - Küche',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Pinneberg',
   'plz': '25421',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': True},
 {'refnr': '10005-115151997020788885-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T10:32:20.314',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT',
   'TEILZEIT',
   'SCHICHT_NACHTARBEIT_WOCHENENDE'],
  'berufe': ['Helfer/in - Metallbearbeitung'],
  'ausbildungen': [{'jahr': 1997, 'art': 'Industriemechaniker/in'}],
  'erfahrung': {'gesamterfahrung': 'P5Y3M17D'},
  'letzteTaetigkeit': {'jahr': '2013',
   'bezeichnung': 'Industriemechaniker/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': False,
  'lokation': {'ort': 'Hemdingen',
   'plz': '25485',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10005-115011999100170814-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T10:22:01.458',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT',
   'TEILZEIT',
   'SCHICHT_NACHTARBEIT_WOCHENENDE'],
  'berufe': ['Gabelstaplerfahrer/in',
   'Helfer/in - Verkauf',
   'Tontechniker/in'],
  'expertenKenntnisse': ['Beladen, Entladen'],
  'ausbildungen': [{'jahr': 2001, 'art': 'Tischler/in'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Verkauf (ohne Produktspezialisierung)',
     'erfahrung': 'P6M'}],
   'gesamterfahrung': 'P1Y11M2D'},
  'letzteTaetigkeit': {'jahr': '2013',
   'bezeichnung': 'Helfer/in - Holz, Flechtwaren',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': False,
  'lokation': {'ort': 'Elmshorn',
   'plz': '25337',
   'umkreis': '25',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205658345-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T17:14:34.489',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Helfer/in - Lagerwirtschaft, Transport',
   'Gabelstaplerfahrer/in'],
  'erfahrung': {'gesamterfahrung': 'P9Y7M'},
  'letzteTaetigkeit': {'jahr': '2016',
   'bezeichnung': 'Helfer/in - Tiefbau',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24109',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205658099-B',
  'verfuegbarkeitVon': '2026-06-01',
  'aktualisierungsdatum': '2026-02-27T15:22:56.168',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['ERP-Berater/in - ERP-Consultant'],
  'ausbildungen': [{'jahr': 2009, 'art': 'Diplom-Kaufmann/-frau'},
   {'jahr': 2003, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'gesamterfahrung': 'P8Y11M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Produktmanager/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': True,
  'lokation': {'ort': 'Flensburg',
   'plz': '24943',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205657581-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T13:42:17.134',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT',
   'TEILZEIT',
   'SCHICHT_NACHTARBEIT_WOCHENENDE'],
  'berufe': ['Textilreiniger/in'],
  'ausbildungen': [{'jahr': 2014,
    'art': 'Bachelor of Arts - Rechtswissenschaft'},
   {'jahr': 2010, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'gesamterfahrung': 'P5Y'},
  'letzteTaetigkeit': {'jahr': '2019',
   'bezeichnung': 'Polizeivollzugsbeamter/-beamtin (höherer Dienst)',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24109',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205656874-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T12:35:33.574',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Verkäufer/in'],
  'ausbildungen': [{'jahr': 2020, 'art': 'Fachkraft - Gastronomie'},
   {'jahr': 2018, 'art': 'Hauptschulabschluss'}],
  'erfahrung': {'gesamterfahrung': 'P3Y5M26D'},
  'letzteTaetigkeit': {'bezeichnung': 'Verkäufer/in', 'aktuell': True},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Neumünster, Holstein',
   'plz': '24536',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205656122-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:59:23.478',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Vorarbeiter/in - Reinigung', 'Disponent/in - Güterverkehr'],
  'ausbildungen': [{'jahr': 1999, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Reinigung',
     'erfahrung': 'P2Y1M26D'},
    {'berufsfeld': 'Kaufleute - Verkehr und Logistik', 'erfahrung': 'P12Y'}],
   'gesamterfahrung': 'P14Y1M26D'},
  'letzteTaetigkeit': {'bezeichnung': 'Kaufmann/-frau - Einzelhandel (Kraftfahrzeuge, Teile und Zubehör)',
   'aktuell': True},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Reinfeld (Holstein)',
   'plz': '23858',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655919-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T12:20:56.804',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Montierer/in'],
  'expertenKenntnisse': ['Kassieren'],
  'ausbildungen': [{'jahr': 1993, 'art': 'Friseur/in'},
   {'jahr': 1990, 'art': 'Hauptschulabschluss'}],
  'erfahrung': {'gesamterfahrung': 'P32Y6M'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Helfer/in - Metallbau',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23556',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655851-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T12:04:17.723',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Bankkaufmann/-frau',
   'Rechtsanwalts- und Notarfachangestellte/r',
   'Kaufmännische Fachkraft'],
  'ausbildungen': [{'jahr': 1986,
    'art': 'Rechtsanwalts- und Notarfachangestellte/r'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Rechtsberatung, -sprechung und -ordnung',
     'erfahrung': 'P4Y9M'},
    {'berufsfeld': 'Versicherungs- und Finanzdienstleistungen',
     'erfahrung': 'P34Y10M26D'}],
   'gesamterfahrung': 'P39Y7M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Bankkaufmann/-frau',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Oststeinbek',
   'plz': '22113',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655846-B',
  'verfuegbarkeitVon': '2026-02-28',
  'aktualisierungsdatum': '2026-02-27T12:05:29.05',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Sozialpädagogische/r Assistent/in / Kinderpfleger/in'],
  'ausbildungen': [{'jahr': 2025,
    'art': 'Sozialpädagogische/r Assistent/in / Kinderpfleger/in'},
   {'jahr': 2022, 'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Erziehung, Sozialarbeit, Heilerziehungspflege',
     'erfahrung': 'P5M'}],
   'gesamterfahrung': 'P5M'},
  'letzteTaetigkeit': {'jahr': '2025',
   'bezeichnung': 'Sozialpädagogische/r Assistent/in / Kinderpfleger/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23570',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655831-B',
  'verfuegbarkeitVon': '2026-03-07',
  'aktualisierungsdatum': '2026-02-27T12:01:53.533',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Vertriebsassistent/in'],
  'expertenKenntnisse': ['E-Mail-Programm Outlook (MS Office)',
   'Textverarbeitung Word (MS Office)',
   'Korrespondenz',
   'Büromaterialverwaltung',
   'Postbearbeitung'],
  'ausbildungen': [{'jahr': 2018, 'art': 'Fachhochschulreife'}],
  'erfahrung': {'gesamterfahrung': 'P3Y2M24D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Studiengangkoordinator/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': True,
  'lokation': {'ort': 'Hochdonn',
   'plz': '25712',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655798-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:48:59.539',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Museumsaufseher/in'],
  'erfahrung': {'gesamterfahrung': 'P34Y1M19D'},
  'letzteTaetigkeit': {'jahr': '2025',
   'bezeichnung': 'Versicherungskaufmann/-frau',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Geesthacht',
   'plz': '21502',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655583-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:44:51.227',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT', 'MINIJOB'],
  'berufe': ['Pförtner/in'],
  'expertenKenntnisse': ['Erziehung',
   'Kinder (Betreuung etc.)',
   'Elternarbeit',
   'Freizeitgestaltung',
   'Sozialpädagogik'],
  'ausbildungen': [{'jahr': 1989, 'art': 'Erzieher/in'},
   {'jahr': 1984, 'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'gesamterfahrung': 'P20Y7M'},
  'letzteTaetigkeit': {'jahr': '2023',
   'bezeichnung': 'Sozialarbeiter/in / Sozialpädagoge/-pädagogin',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Olderup',
   'plz': '25860',
   'umkreis': '15',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655527-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:55:36.649',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Helfer/in - Verkauf'],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Verkauf (ohne Produktspezialisierung)',
     'erfahrung': 'P1Y4M26D'}],
   'gesamterfahrung': 'P1Y4M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Helfer/in - Verkauf',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23556',
   'umkreis': '10',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205655350-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:37:23.52',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT',
   'TEILZEIT',
   'SCHICHT_NACHTARBEIT_WOCHENENDE'],
  'berufe': ['Helfer/in - Reinigung'],
  'ausbildungen': [{'jahr': 2001,
    'art': 'Bachelor of Arts - Musik (Dirigieren)'},
   {'jahr': 1996, 'art': 'Bachelor of Arts - Musik'},
   {'jahr': 1991, 'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Reinigung',
     'erfahrung': 'P8M2D'}],
   'gesamterfahrung': 'P27Y1M21D'},
  'letzteTaetigkeit': {'bezeichnung': 'Musiklehrer/in', 'aktuell': True},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23569',
   'umkreis': '25',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205654642-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T12:03:39.124',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT',
   'SCHICHT_NACHTARBEIT_WOCHENENDE',
   'MINIJOB'],
  'berufe': ['Helfer/in - Verkauf',
   'Servicekraft - Gastronomie und Gastgewerbe',
   'Helfer/in - Lagerwirtschaft, Transport'],
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Flensburg',
   'plz': '24939',
   'umkreis': '10',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205654430-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:12:55.804',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Pförtner/in'],
  'ausbildungen': [{'jahr': 1990, 'art': 'Werkzeugmacher/in'}],
  'erfahrung': {'gesamterfahrung': 'P7Y1M2D'},
  'letzteTaetigkeit': {'jahr': '2025',
   'bezeichnung': 'Pharmakant/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Oldenburg in Holstein',
   'plz': '23758',
   'umkreis': '15',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205653161-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T10:54:34.766',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Helfer/in - Verkauf'],
  'expertenKenntnisse': ['Kassieren',
   'Warenauszeichnung',
   'Regalauffüllen',
   'Warenpräsentation'],
  'ausbildungen': [{'jahr': 2021, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Verkauf (ohne Produktspezialisierung)',
     'erfahrung': 'P3Y3M26D'}],
   'gesamterfahrung': 'P3Y3M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Verkäufer/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': True,
  'lokation': {'ort': 'Engelbrechtsche Wildnis',
   'plz': '25348',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205652675-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T10:31:12.452',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Helfer/in - Verkauf'],
  'ausbildungen': [{'jahr': 2015, 'art': 'Friseur/in'},
   {'jahr': 2012, 'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Verkauf (ohne Produktspezialisierung)',
     'erfahrung': 'P11M'}],
   'gesamterfahrung': 'P10Y27D'},
  'letzteTaetigkeit': {'jahr': '2025',
   'bezeichnung': 'Helfer/in - Verkauf',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Elmshorn',
   'plz': '25335',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205652413-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T10:27:08.228',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Helfer/in - Lagerwirtschaft, Transport'],
  'erfahrung': {'gesamterfahrung': 'P1Y2M6D'},
  'letzteTaetigkeit': {'jahr': '2024',
   'bezeichnung': 'Pflegeassistent/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23552',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205652295-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T10:19:23.752',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Helfer/in - Verkauf'],
  'ausbildungen': [{'jahr': 2019, 'art': 'Hauptschulabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Verkauf (ohne Produktspezialisierung)',
     'erfahrung': 'P4M16D'}],
   'gesamterfahrung': 'P4M16D'},
  'letzteTaetigkeit': {'jahr': '2020',
   'bezeichnung': 'Helfer/in - Verkauf',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Uetersen',
   'plz': '25436',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205652225-B',
  'verfuegbarkeitVon': '2026-02-27',
  'aktualisierungsdatum': '2026-02-27T11:24:25.02',
  'veroeffentlichungsdatum': '2026-02-27',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Tierphysiotherapeut/in', 'Helfer/in - Büro, Verwaltung'],
  'ausbildungen': [{'jahr': 2024, 'art': 'Tierphysiotherapeut/in'},
   {'jahr': 2020, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Tiermedizin und Tierheilkunde',
     'erfahrung': 'P1Y5M17D'}],
   'gesamterfahrung': 'P1Y9M2D'},
  'letzteTaetigkeit': {'bezeichnung': 'Helfer/in - Verkauf', 'aktuell': True},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23558',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',

In [80]:
df_bew_SH = json_normalize(bewerber)
df_bew_SH

,refnr,verfuegbarkeitVon,aktualisierungsdatum,veroeffentlichungsdatum,stellenart,arbeitszeitModelle,berufe,hatEmail,hatTelefon,hatAdresse,...,letzteTaetigkeit.aktuell,lokation.ort,lokation.plz,lokation.umkreis,lokation.region,lokation.land,ausbildungen,erfahrung.berufsfeldErfahrung,expertenKenntnisse,freierTitelStellengesuch
0,10005-135012005101862978-B,2026-02-27,2026-02-27T06:33:30.934,2026-02-27,ARBEIT,[TEILZEIT],[Pförtner/in],False,False,False,...,False,Eutin,23701,20,Schleswig-Holstein,Deutschland,NaN,NaN,NaN,NaN
1,10005-115171997032452442-B,2026-02-27,2026-02-27T15:40:36.544,2026-02-27,ARBEIT,"[VOLLZEIT, TEILZEIT]","[Helfer/in - Büro, Verwaltung, Kaufmann/-frau ...",False,False,False,...,False,Pinneberg,25421,20,Schleswig-Holstein,Deutschland,"[{'jahr': 1990, 'art': 'Kaufmann/-frau - Groß-...","[{'berufsfeld': 'Handel', 'erfahrung': 'P1Y'}]",NaN,NaN
2,10005-115151997020788885-B,2026-02-27,2026-02-27T10:32:20.314,2026-02-27,ARBEIT,"[VOLLZEIT, TEILZEIT, SCHICHT_NACHTARBEIT_WOCHE...",[Helfer/in - Metallbearbeitung],False,True,False,...,False,Hemdingen,25485,20,Schleswig-Holstein,Deutschland,"[{'jahr': 1997, 'art': 'Industriemechaniker/in'}]",NaN,NaN,NaN
3,10005-115011999100170814-B,2026-02-27,2026-02-27T10:22:01.458,2026-02-27,ARBEIT,"[VOLLZEIT, TEILZEIT, SCHICHT_NACHTARBEIT_WOCHE...","[Gabelstaplerfahrer/in, Helfer/in - Verkauf, T...",False,True,False,...,False,Elmshorn,25337,25,Schleswig-Holstein,Deutschland,"[{'jahr': 2001, 'art': 'Tischler/in'}]",[{'berufsfeld': 'Verkauf (ohne Produktspeziali...,"[Beladen, Entladen]",NaN
4,10000-1205658345-B,2026-02-27,2026-02-27T17:14:34.489,2026-02-27,ARBEIT,[VOLLZEIT],"[Helfer/in - Lagerwirtschaft, Transport, Gabel...",False,False,False,...,False,Kiel,24109,30,Schleswig-Holstein,Deutschland,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,10000-1205627912-B,2026-02-26,2026-02-26T07:03:37.979,2026-02-26,ARBEIT,"[VOLLZEIT, TEILZEIT, SCHICHT_NACHTARBEIT_WOCHE...",[Helfer/in - Reinigung],False,False,False,...,True,Kiel,24143,50,Schleswig-Holstein,Deutschland,NaN,"[{'berufsfeld': 'Reinigung', 'erfahrung': 'P4Y...",NaN,NaN
246,10000-1205626859-B,2026-02-26,2026-02-26T06:21:56.934,2026-02-26,ARBEIT,"[VOLLZEIT, TEILZEIT, SCHICHT_NACHTARBEIT_WOCHE...",[Helfer/in - Verkauf],False,False,False,...,NaN,Oldenburg in Holstein,23758,10,Schleswig-Holstein,Deutschland,NaN,NaN,NaN,NaN
247,10000-1205626102-B,2026-04-01,2026-02-26T09:45:14.137,2026-02-26,ARBEIT,[TEILZEIT],"[Personalreferent/in, Personalsachbearbeiter/in]",False,True,False,...,True,"Neumünster, Holstein",24534,30,Schleswig-Holstein,Deutschland,"[{'jahr': 2018, 'art': 'Bachelor of Arts - BWL...",NaN,"[Einkauf, Beschaffung, Buchführung, Buchhaltun...",NaN
248,10000-1205625863-B,2026-02-26,2026-02-26T06:17:31.364,2026-02-26,ARBEIT,"[VOLLZEIT, TEILZEIT, SCHICHT_NACHTARBEIT_WOCHE...",[Helfer/in - Reinigung],False,False,False,...,True,Bad Oldesloe,23843,50,Schleswig-Holstein,Deutschland,"[{'jahr': 1990, 'art': 'Fachpraktiker/in im Ga...","[{'berufsfeld': 'Reinigung', 'erfahrung': 'P23...",NaN,NaN
249,10000-1205621495-B,2026-04-01,2026-02-26T10:49:16.874,2026-02-26,ARBEIT,[VOLLZEIT],"[Ingenieur/in - Stadt- und Regionalplanung, St...",False,False,False,...,False,Lübeck,23570,50,Schleswig-Holstein,Deutschland,"[{'jahr': 2017, 'art': 'Master of Arts - Städt...","[{'berufsfeld': 'Bauplanung und -überwachung, ...",NaN,NaN

In [82]:
all_bewerber = []

for page in range(1, 3):  # immer Seite 1 als Minimum haben - geht aber auch Seite 41 bis 81
    query["page"] = page   #oben habe ich size 250 gesetzt, daher kriegt man 250 x Seitenanzahl an Ergebnissen
    url = f"{base}?{up.urlencode(query, safe=';')}"  #250 x 40 = 10000
    
    r = requests.get(url, headers=headers, timeout=30)
    data = r.json()
    
    all_bewerber.extend(data["bewerber"])

df_bew_SH = json_normalize(all_bewerber) #erzeugt die Spaltenform die man unten sehen kann
df_bew_SH = df_bew_SH[[
    #"refnr",
    #"verfuegbarkeitVon",
    #"aktualisierungsdatum",
    #"veroeffentlichungsdatum",
    "stellenart",
    #"arbeitszeitModelle",
    "berufe",
    #"hatEmail",
    #"hatTelefon",
    #"hatAdresse",
    #"mehrereArbeitsorte",
    #"erfahrung.gesamterfahrung",
    "letzteTaetigkeit.jahr",
    "letzteTaetigkeit.bezeichnung",
    #"letzteTaetigkeit.aktuell",
    #"lokation.ort",
    #"lokation.plz",
    #"lokation.umkreis",
    #"lokation.region",
    #"lokation.land",
    #"ausbildungen",
    #"erfahrung.berufsfeldErfahrung",
    #"expertenKenntnisse",
    #"freierTitelStellengesuch"
    ]]
df_bew_SH

,stellenart,berufe,letzteTaetigkeit.jahr,letzteTaetigkeit.bezeichnung
0,ARBEIT,[Pförtner/in],2019,Helfer/in - Reinigung
1,ARBEIT,"[Helfer/in - Büro, Verwaltung, Kaufmann/-frau ...",2015,Helfer/in - Küche
2,ARBEIT,[Helfer/in - Metallbearbeitung],2013,Industriemechaniker/in
3,ARBEIT,"[Gabelstaplerfahrer/in, Helfer/in - Verkauf, T...",2013,"Helfer/in - Holz, Flechtwaren"
4,ARBEIT,"[Helfer/in - Lagerwirtschaft, Transport, Gabel...",2016,Helfer/in - Tiefbau
...,...,...,...,...
495,ARBEIT,"[Bodensteward/-stewardess, Marketingfachkraft/...",NaN,NaN
496,ARBEIT,[Helfer/in - Küche],2025,Helfer/in - Küche
497,ARBEIT,"[Handelsvertreter/in, Digital-Event-Manager/in]",2026,Handelsvertreter/in
498,ARBEIT,[Helfer/in - Altenpflege/Persönliche Assistenz],2026,Friseur/in
499,ARBEIT,[Gemeindearbeiter/in],2026,Hausmeister/in

In [83]:
df_bew_SH.to_csv("bewerber_SH_500.csv", index=False)