In [1]:
#import sys
#!{sys.executable} -m pip install plotly      #falls man noch was installieren muss, geht das hiermit recht leicht

In [2]:
import requests
import urllib.parse as up
import pandas
from pandas import json_normalize
import json
base = "https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v4/jobs"
query = {
    "angebotsart": "1",
    "wo": "Schleswig-Holstein",
    #"umkreis": "200",
    #"arbeitszeit": "ho;mj",  # Semikolon bleibt bewusst erhalten
    #"page": "5",
    "size": "250",
    #"pav": "false",
}
# safe=';' sorgt dafür, dass das Semikolon nicht encodiert wird, falls die API es so erwartet
url = f"{base}?{up.urlencode(query, safe=';')}"

headers = {
    "X-API-Key": "jobboerse-jobsuche",
    #"Accept": "application/json",
    #"User-Agent": "Mozilla/5.0",
}

r = requests.get(url, headers=headers, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data= r.json()

URL: https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v4/jobs?angebotsart=1&wo=Schleswig-Holstein&size=250
Status: 200 OK
CT: application/json;charset=UTF-8

In [3]:
print(data.keys())

dict_keys(['stellenangebote', 'maxErgebnisse', 'page', 'size', 'woOutput', 'facetten'])

In [4]:
facetten=data["facetten"] #alle möglichen Eigenschaften inklusive der dort vorhanden Daten denke ich mal für Angebotsart 1
#facetten                  #aus manchen Eigenschaften werde ich aber noch nicht so richtig schlau, da keine Einheiten gegeben sind

In [5]:
#print(data.get("stellenangebote"))

In [6]:
jobs=data["stellenangebote"]
#jobs

In [7]:
df_job_SH = json_normalize(jobs)
#df_job_SH

In [8]:
df_job_SH = df_job_SH[["beruf",	"titel",	"refnr",	"arbeitgeber",	"aktuelleVeroeffentlichungsdatum",	"modifikationsTimestamp",	"eintrittsdatum",	"arbeitsort.plz",	"arbeitsort.ort",	"arbeitsort.strasse",	"arbeitsort.region",	"arbeitsort.land",	"arbeitsort.koordinaten.lat",	"arbeitsort.koordinaten.lon",	"arbeitsort.ortsteil",	"externeUrl"]]
#df_job_SH

KeyError: "['arbeitsort.ortsteil'] not in index"

In [ ]:
all_jobs = []

for page in range(1, 3):  # immer Seite 1 als Minimum haben - geht aber auch Seite 41 bis 81
    query["page"] = page   #oben habe ich size 250 gesetzt, daher kriegt man 250 x Seitenanzahl an Ergebnissen
    url = f"{base}?{up.urlencode(query, safe=';')}"  #250 x 40 = 10000
    
    r = requests.get(url, headers=headers, timeout=30)
    data = r.json()
    
    all_jobs.extend(data["stellenangebote"])

df_job_SH = json_normalize(all_jobs) #erzeugt die Spaltenform die man unten sehen kann
df_job_SH = df_job_SH[["beruf",	#alle Spalten die man in der Rückgabe haben will - habe zB die Hashs der spezifischen Personen 
         "titel",	#mal rausgenommen, da wir damit denke eh nichts machen werden
         #"refnr",	
         #"arbeitgeber",	
         #"aktuelleVeroeffentlichungsdatum",	
         #"modifikationsTimestamp",	
         #"eintrittsdatum",	
         #"arbeitsort.plz",	
         #"arbeitsort.ort",	
         #"arbeitsort.strasse",	
         #"arbeitsort.region",	
         #"arbeitsort.land",	
         #"arbeitsort.koordinaten.lat",	
         #"arbeitsort.koordinaten.lon",	
         #"arbeitsort.ortsteil",	
         #"externeUrl"
        ]]
df_job_SH

In [9]:
df_job_SH.to_csv("jobs_SH_500.csv", index=False)

In [16]:
base = "https://rest.arbeitsagentur.de/jobboerse/bewerbersuche-service/pc/v1/bewerber"
query = {
    #"angebotsart": "",
    #"was": "",
    #"ausbildungsart": "",
    "wo": "Schleswig-Holstein",  
    #"umkreis": "",
    #"angebotsart": "",
    #"arbeitszeit": "",
    #"berufserfahrung": "",
    #"vertragsart": "",
    #"page": "",  #Seiten beginnen bei 0
    "size": "250",
    
}
# safe=';' sorgt dafür, dass das Semikolon nicht encodiert wird, falls die API es so erwartet
url = f"{base}?{up.urlencode(query, safe=';')}"

headers = {
    "X-API-Key": "jobboerse-bewerbersuche-ui",
    #"Accept": "application/json",
    #"User-Agent": "Mozilla/5.0",
}

r = requests.get(url, headers=headers, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data= r.json()

URL: https://rest.arbeitsagentur.de/jobboerse/bewerbersuche-service/pc/v1/bewerber?wo=Schleswig-Holstein&size=250
Status: 200 OK
CT: application/json

In [11]:
print(data.keys())

dict_keys(['bewerber', 'maxErgebnisse', 'page', 'size', 'woOutput', 'facetten'])

In [12]:
bewerber=data["bewerber"]
bewerber

[{'refnr': '10000-1205658640-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-03-01T11:38:55.881',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Helfer/in - Lagerwirtschaft, Transport',
   'Helfer/in - Fahrzeugbau und -instandhaltung'],
  'erfahrung': {'gesamterfahrung': 'P10M'},
  'letzteTaetigkeit': {'bezeichnung': 'Servicekraft - Gastronomie und Gastgewerbe',
   'aktuell': True},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Schleswig',
   'plz': '24837',
   'umkreis': '15',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205476807-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-27T12:01:55.948',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Managementassistent/in', 'Assistent/in - Hotelmanagement'],
  'expertenKenntnisse': ['Textverarbeitung Word (MS Office)',
   'Korrespondenz',
   'Vertrieb'],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Büro und Sekretariat',
     'erfahrung': 'P3Y1M26D'}],
   'gesamterfahrung': 'P7Y1M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Managementassistent/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Schenefeld, Bz Hamburg',
   'plz': '22869',
   'umkreis': '25',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205377303-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-23T10:02:38.707',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Onlinemarketing-Manager/in', 'Werbekaufmann/-frau'],
  'ausbildungen': [{'jahr': 2008, 'art': 'Werbekaufmann/-frau'},
   {'jahr': 2004, 'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Werbung und Marketing',
     'erfahrung': 'P3Y4M10D'}],
   'gesamterfahrung': 'P3Y4M10D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Onlinemarketing-Manager/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Schellhorn bei Preetz, Holstein',
   'plz': '24211',
   'umkreis': '25',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205376122-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-24T13:56:10.937',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'HEIM_TELEARBEIT'],
  'berufe': ['Controller/in',
   'Produktmanager/in',
   'Betriebswirt/in (Fachschule) - Projektmanagement'],
  'ausbildungen': [{'jahr': 2018,
    'art': 'Bachelor of Arts - Betriebswirtschaft (Internationales Management)'},
   {'jahr': 2013, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Rechnungswesen, Controlling und Revision',
     'erfahrung': 'P3Y5M26D'}],
   'gesamterfahrung': 'P3Y5M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Controller/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24116',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205372394-B',
  'verfuegbarkeitVon': '2026-02-04',
  'aktualisierungsdatum': '2026-02-04T09:22:47.436',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Schulbegleiter/in'],
  'ausbildungen': [{'jahr': 2019,
    'art': 'Fachlehrer/in - allgemeinbildenden Schulen'}],
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Elmshorn',
   'plz': '25336',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205280392-B',
  'verfuegbarkeitVon': '2026-07-01',
  'aktualisierungsdatum': '2026-02-23T13:19:25.928',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Geschäftsführer/in'],
  'ausbildungen': [{'jahr': 1989,
    'art': 'Master of Science - Volkswirtschaftslehre'},
   {'jahr': 1983, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'gesamterfahrung': 'P3Y9M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Prorektor/in / Vizepräsident/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': True,
  'lokation': {'ort': 'Rellingen',
   'plz': '25462',
   'umkreis': '200',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205275099-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-17T09:35:25.14',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Automobilkaufmann/-frau'],
  'expertenKenntnisse': ['Kundenberatung, -betreuung',
   'E-Mail-Programm Outlook (MS Office)'],
  'ausbildungen': [{'jahr': 2013, 'art': 'Automobilkaufmann/-frau'},
   {'jahr': 2010, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'gesamterfahrung': 'P5Y7M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Projektleiter/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Schinkel bei Gettorf',
   'plz': '24214',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205242895-B',
  'verfuegbarkeitVon': '2026-03-24',
  'aktualisierungsdatum': '2026-01-26T10:54:47.322',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT',
   'SCHICHT_NACHTARBEIT_WOCHENENDE',
   'TEILZEIT'],
  'berufe': ['Helfer/in - Verkauf',
   'Helfer/in - Reinigung',
   'Servicekraft - Gastronomie und Gastgewerbe'],
  'ausbildungen': [{'jahr': 2012,
    'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Reinigung',
     'erfahrung': 'P6Y5M29D'}],
   'gesamterfahrung': 'P10Y10M25D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Busfahrer/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lägerdorf',
   'plz': '25566',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1205110031-B',
  'verfuegbarkeitVon': '2026-01-14',
  'aktualisierungsdatum': '2026-01-14T10:43:07.604',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Helfer/in - Lebensmittelherstellung'],
  'ausbildungen': [{'jahr': 2022, 'art': 'Schulabschluss der Förderschule'}],
  'erfahrung': {'gesamterfahrung': 'P4Y11M26D'},
  'letzteTaetigkeit': {'bezeichnung': 'Helfer/in - Gartenbau',
   'aktuell': True},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': False,
  'lokation': {'ort': 'Bad Schwartau',
   'plz': '23611',
   'umkreis': '15',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204954693-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-25T15:12:50.51',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'SCHICHT_NACHTARBEIT_WOCHENENDE'],
  'berufe': ['Sozialarbeiter/in / Sozialpädagoge/-pädagogin'],
  'ausbildungen': [{'jahr': 2025, 'art': 'Bachelor of Arts - Soziale Arbeit'},
   {'jahr': 2020, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Erziehung, Sozialarbeit, Heilerziehungspflege',
     'erfahrung': 'P11M26D'}],
   'gesamterfahrung': 'P11M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Sozialarbeiter/in / Sozialpädagoge/-pädagogin',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Seeth-Ekholt',
   'plz': '25337',
   'umkreis': '25',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204948452-B',
  'verfuegbarkeitVon': '2026-04-01',
  'aktualisierungsdatum': '2026-01-12T12:34:38.707',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'HEIM_TELEARBEIT'],
  'berufe': ['Arbeitsplatz-Auditor/in'],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Objekt-, Personen-, Brandschutz, Arbeitssicherheit',
     'erfahrung': 'P3Y26D'}],
   'gesamterfahrung': 'P3Y26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Arbeitsplatz-Auditor/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23568',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': True},
 {'refnr': '10000-1204672583-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2025-12-15T14:42:37.843',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Erzieher/in'],
  'expertenKenntnisse': ['Erziehung'],
  'ausbildungen': [{'jahr': 2014, 'art': 'Erzieher/in'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Erziehung, Sozialarbeit, Heilerziehungspflege',
     'erfahrung': 'P8Y3M26D'}],
   'gesamterfahrung': 'P8Y3M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Erzieher/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23552',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204654329-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-24T11:52:48.606',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Versicherungskaufmann/-frau'],
  'expertenKenntnisse': ['Kundenberatung, -betreuung'],
  'ausbildungen': [{'jahr': 2001, 'art': 'Versicherungskaufmann/-frau'},
   {'jahr': 1997, 'art': 'Fachhochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Versicherungs- und Finanzdienstleistungen',
     'erfahrung': 'P24Y11M26D'}],
   'gesamterfahrung': 'P24Y11M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Versicherungskaufmann/-frau',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': True,
  'lokation': {'ort': 'Felm',
   'plz': '24244',
   'umkreis': '15',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204637000-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-02-19T15:47:42.995',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Leiter/in - Vertrieb'],
  'ausbildungen': [{'jahr': 1990, 'art': 'Industriekaufmann/-frau'},
   {'jahr': 1986, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Einkauf und Vertrieb',
     'erfahrung': 'P10Y7M21D'}],
   'gesamterfahrung': 'P32Y1M19D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Leiter/in - Vertrieb',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kalübbe, Holstein',
   'plz': '24326',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204616426-B',
  'verfuegbarkeitVon': '2026-07-01',
  'aktualisierungsdatum': '2025-12-29T13:39:46.446',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Konstrukteur/in', 'Konstruktionstechniker/in'],
  'ausbildungen': [{'jahr': 2026, 'art': 'Fachhochschulreife'},
   {'jahr': 2023, 'art': 'Fachkraft - Metalltechnik - Konstruktionstechnik'}],
  'erfahrung': {'gesamterfahrung': 'P4M15D'},
  'letzteTaetigkeit': {'jahr': '2024',
   'bezeichnung': 'Metallbauer/in - Konstruktionstechnik',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': True,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24103',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204439988-B',
  'verfuegbarkeitVon': '2026-01-08',
  'aktualisierungsdatum': '2026-02-20T11:25:25.364',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Helfer/in - Reinigung', 'Helfer/in - Küche'],
  'erfahrung': {'gesamterfahrung': 'P7Y'},
  'letzteTaetigkeit': {'jahr': '2021',
   'bezeichnung': 'Helfer/in - Verkauf',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Pahlen',
   'plz': '25794',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204340475-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2025-11-03T14:48:03.463',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Helfer/in - Fahrzeugbau und -instandhaltung'],
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24109',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1204058150-B',
  'verfuegbarkeitVon': '2026-02-03',
  'aktualisierungsdatum': '2026-02-03T09:46:48.781',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Bürokaufmann/-frau'],
  'expertenKenntnisse': ['Büro- und Verwaltungsarbeiten'],
  'ausbildungen': [{'jahr': 2020, 'art': 'Kaufmann/-frau - Büromanagement'},
   {'jahr': 2014, 'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'}],
  'erfahrung': {'gesamterfahrung': 'P1Y3M'},
  'letzteTaetigkeit': {'jahr': '2023',
   'bezeichnung': 'Helfer/in - Reinigung',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Windbergen',
   'plz': '25729',
   'umkreis': '30',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1203980285-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2025-10-02T09:40:22.817',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Helfer/in - Reinigung', 'Helfer/in - Verkauf'],
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24109',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1203919614-B',
  'freierTitelStellengesuch': 'Helger',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2026-01-09T13:32:49.243',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['TEILZEIT'],
  'berufe': ['Helfer/in - Verkauf'],
  'ausbildungen': [{'jahr': 2022,
    'art': 'Mittlere Reife / Mittlerer Bildungsabschluss'},
   {'jahr': 2014, 'art': 'Hauptschulabschluss'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Verkauf (ohne Produktspezialisierung)',
     'erfahrung': 'P11M16D'}],
   'gesamterfahrung': 'P11M16D'},
  'letzteTaetigkeit': {'jahr': '2024',
   'bezeichnung': 'Helfer/in - Verkauf',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24113',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1203918084-B',
  'verfuegbarkeitVon': '2026-02-26',
  'aktualisierungsdatum': '2026-02-26T19:37:21.079',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Schulbegleiter/in',
   'Kartenverkäufer/in',
   'Betreuungskraft / Alltagsbegleiter/in'],
  'ausbildungen': [{'jahr': 1986, 'art': 'Schauwerbegestalter/in'},
   {'jahr': 1984, 'art': 'Fachverkäufer/in'}],
  'erfahrung': {'gesamterfahrung': 'P22Y6M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Schauwerbegestalter/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Lübeck',
   'plz': '23562',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1203629264-B',
  'verfuegbarkeitVon': '2026-03-01',
  'aktualisierungsdatum': '2025-12-30T17:52:32.586',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT'],
  'berufe': ['Leiter/in - betriebliche Aus- und Weiterbildung',
   'Personalreferent/in'],
  'ausbildungen': [{'jahr': 1987,
    'art': 'Master of Science - Volkswirtschaftslehre'},
   {'jahr': 1982, 'art': 'Allgemeine Hochschulreife'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Personalwesen und -dienstleistung',
     'erfahrung': 'P15Y10M26D'}],
   'gesamterfahrung': 'P15Y10M26D'},
  'letzteTaetigkeit': {'jahr': '2026',
   'bezeichnung': 'Leiter/in - betriebliche Aus- und Weiterbildung',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24107',
   'umkreis': '100',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1203567451-B',
  'verfuegbarkeitVon': '2026-02-06',
  'aktualisierungsdatum': '2026-02-06T10:20:43.592',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Nageldesigner/in', 'Helfer/in - Reinigung'],
  'ausbildungen': [{'jahr': 2010, 'art': 'Nageldesigner/in'}],
  'erfahrung': {'berufsfeldErfahrung': [{'berufsfeld': 'Körperpflege',
     'erfahrung': 'P14Y9M15D'}],
   'gesamterfahrung': 'P14Y9M15D'},
  'letzteTaetigkeit': {'jahr': '2025',
   'bezeichnung': 'Nageldesigner/in',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Eutin',
   'plz': '23701',
   'umkreis': '20',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1203458375-B',
  'verfuegbarkeitVon': '2026-01-01',
  'aktualisierungsdatum': '2025-08-18T09:08:25.532',
  'veroeffentlichungsdatum': '2026-03-01',
  'stellenart': 'ARBEIT',
  'arbeitszeitModelle': ['VOLLZEIT', 'TEILZEIT'],
  'berufe': ['Sprechstunden-/Praxishelfer/in'],
  'ausbildungen': [{'jahr': 2023, 'art': 'Krankenschwester/-pfleger'}],
  'erfahrung': {'gesamterfahrung': 'P1Y8M29D'},
  'letzteTaetigkeit': {'jahr': '2025',
   'bezeichnung': 'Krankenschwester/-pfleger',
   'aktuell': False},
  'hatEmail': False,
  'hatTelefon': False,
  'hatAdresse': False,
  'lokation': {'ort': 'Kiel',
   'plz': '24106',
   'umkreis': '50',
   'region': 'Schleswig-Holstein',
   'land': 'Deutschland'},
  'mehrereArbeitsorte': False},
 {'refnr': '10000-1202070002-B',
  'verfuegbarkeitVon': '2025-03-31',
  'aktualisierungsdatum': '2026-02-19T10:20:24.477',

In [13]:
df_bew_SH = json_normalize(bewerber)
df_bew_SH

,refnr,verfuegbarkeitVon,aktualisierungsdatum,veroeffentlichungsdatum,stellenart,arbeitszeitModelle,berufe,hatEmail,hatTelefon,hatAdresse,...,lokation.ort,lokation.plz,lokation.umkreis,lokation.region,lokation.land,expertenKenntnisse,erfahrung.berufsfeldErfahrung,letzteTaetigkeit.jahr,ausbildungen,freierTitelStellengesuch
0,10000-1205658640-B,2026-03-01,2026-03-01T11:38:55.881,2026-03-01,ARBEIT,"[VOLLZEIT, TEILZEIT]","[Helfer/in - Lagerwirtschaft, Transport, Helfe...",False,False,False,...,Schleswig,24837,15,Schleswig-Holstein,Deutschland,NaN,NaN,NaN,NaN,NaN
1,10000-1205476807-B,2026-03-01,2026-02-27T12:01:55.948,2026-03-01,ARBEIT,[VOLLZEIT],"[Managementassistent/in, Assistent/in - Hotelm...",False,False,False,...,"Schenefeld, Bz Hamburg",22869,25,Schleswig-Holstein,Deutschland,"[Textverarbeitung Word (MS Office), Korrespond...","[{'berufsfeld': 'Büro und Sekretariat', 'erfah...",2026,NaN,NaN
2,10000-1205377303-B,2026-03-01,2026-02-23T10:02:38.707,2026-03-01,ARBEIT,[TEILZEIT],"[Onlinemarketing-Manager/in, Werbekaufmann/-frau]",False,False,False,...,"Schellhorn bei Preetz, Holstein",24211,25,Schleswig-Holstein,Deutschland,NaN,"[{'berufsfeld': 'Werbung und Marketing', 'erfa...",2026,"[{'jahr': 2008, 'art': 'Werbekaufmann/-frau'},...",NaN
3,10000-1205376122-B,2026-03-01,2026-02-24T13:56:10.937,2026-03-01,ARBEIT,"[VOLLZEIT, HEIM_TELEARBEIT]","[Controller/in, Produktmanager/in, Betriebswir...",False,False,False,...,Kiel,24116,50,Schleswig-Holstein,Deutschland,NaN,"[{'berufsfeld': 'Rechnungswesen, Controlling u...",2026,"[{'jahr': 2018, 'art': 'Bachelor of Arts - Bet...",NaN
4,10000-1205372394-B,2026-02-04,2026-02-04T09:22:47.436,2026-03-01,ARBEIT,[TEILZEIT],[Schulbegleiter/in],False,False,False,...,Elmshorn,25336,20,Schleswig-Holstein,Deutschland,NaN,NaN,NaN,"[{'jahr': 2019, 'art': 'Fachlehrer/in - allgem...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,10000-1205642322-B,2026-04-01,2026-02-26T15:34:13.08,2026-02-26,ARBEIT,[VOLLZEIT],"[Bautischler/in, Hausmeister/in]",False,True,False,...,Hamweddel,24816,50,Schleswig-Holstein,Deutschland,NaN,"[{'berufsfeld': 'Aus- und Trockenbau, Isolieru...",2026,"[{'jahr': 1989, 'art': 'Tischler/in - Bau- und...",NaN
246,10000-1205642273-B,2026-02-26,2026-02-26T15:24:21.325,2026-02-26,ARBEIT,"[VOLLZEIT, TEILZEIT]","[Helfer/in - Lagerwirtschaft, Transport]",False,False,False,...,Trittau,22946,30,Schleswig-Holstein,Deutschland,NaN,NaN,NaN,NaN,NaN
247,10000-1205641270-B,2026-02-26,2026-02-26T16:29:41.815,2026-02-26,ARBEIT,[VOLLZEIT],[Fahrradmonteur/in],False,False,True,...,Stockelsdorf,23617,20,Schleswig-Holstein,Deutschland,NaN,"[{'berufsfeld': 'Fahrzeug-, Luft-, Raumfahrt- ...",2026,"[{'jahr': 2022, 'art': 'Fahrradmonteur/in'}]",NaN
248,10000-1205641067-B,2026-02-26,2026-02-26T14:41:03.382,2026-02-26,ARBEIT,[VOLLZEIT],"[Maler/in und Lackierer/in - Maler/in, Maler/i...",False,False,False,...,Wentorf bei Sandesneben,23898,50,Schleswig-Holstein,Deutschland,"[Kundenberatung, -betreuung, Arbeitsvorbereitung]","[{'berufsfeld': 'Maler, Stuckateure, Bautensch...",2026,"[{'jahr': 2008, 'art': 'Raumausstatter/in'}]",NaN
249,10000-1205640882-B,2026-07-01,2026-02-26T15:01:57.636,2026-02-26,ARBEIT,[VOLLZEIT],"[Leiter/in - Produktion/Fertigung, Ingenieur/i...",False,False,False,...,"Friedrichskoog, Dithmarschen",25718,25,Schleswig-Holstein,Deutschland,"[Kundenberatung, -betreuung, Arbeitsvorbereitu...",[{'berufsfeld': 'Technische Produktionsplanung...,2026,NaN,NaN

In [18]:
all_bewerber = []

for page in range(1, 3):  # immer Seite 1 als Minimum haben - geht aber auch Seite 41 bis 81
    query["page"] = page   #oben habe ich size 250 gesetzt, daher kriegt man 250 x Seitenanzahl an Ergebnissen
    url = f"{base}?{up.urlencode(query, safe=';')}"  #250 x 40 = 10000
    
    r = requests.get(url, headers=headers, timeout=30)
    data = r.json()
    
    all_bewerber.extend(data["bewerber"])

df_bew_SH = json_normalize(all_bewerber) #erzeugt die Spaltenform die man unten sehen kann
df_bew_SH = df_bew_SH[[
    #"refnr",
    #"verfuegbarkeitVon",
    #"aktualisierungsdatum",
    "veroeffentlichungsdatum",
    "stellenart",
    #"arbeitszeitModelle",
    "berufe",
    #"hatEmail",
    #"hatTelefon",
    #"hatAdresse",
    #"mehrereArbeitsorte",
    #"erfahrung.gesamterfahrung",
    "letzteTaetigkeit.jahr",
    "letzteTaetigkeit.bezeichnung",
    #"letzteTaetigkeit.aktuell",
    #"lokation.ort",
    #"lokation.plz",
    #"lokation.umkreis",
    #"lokation.region",
    #"lokation.land",
    #"ausbildungen",
    #"erfahrung.berufsfeldErfahrung",
    #"expertenKenntnisse",
    #"freierTitelStellengesuch"
    ]]
df_bew_SH

,veroeffentlichungsdatum,stellenart,berufe,letzteTaetigkeit.jahr,letzteTaetigkeit.bezeichnung
0,2026-03-01,ARBEIT,"[Helfer/in - Lagerwirtschaft, Transport, Helfe...",NaN,Servicekraft - Gastronomie und Gastgewerbe
1,2026-03-01,ARBEIT,"[Managementassistent/in, Assistent/in - Hotelm...",2026,Managementassistent/in
2,2026-03-01,ARBEIT,"[Onlinemarketing-Manager/in, Werbekaufmann/-frau]",2026,Onlinemarketing-Manager/in
3,2026-03-01,ARBEIT,"[Controller/in, Produktmanager/in, Betriebswir...",2026,Controller/in
4,2026-03-01,ARBEIT,[Schulbegleiter/in],NaN,NaN
...,...,...,...,...,...
495,2026-02-26,ARBEIT,"[Helfer/in - Lagerwirtschaft, Transport, Helfe...",2026,Helfer/in - Reinigung
496,2026-02-26,ARBEIT,"[Helfer/in - Reinigung, Helfer/in - Gartenbau,...",2020,Helfer/in - Reinigung
497,2026-02-26,ARBEIT,"[Helfer/in - Büro, Verwaltung]",2017,Gärtner/in - Garten- und Landschaftsbau
498,2026-02-26,ARBEIT,[Helfer/in - Verkauf],2026,Helfer/in - Verkauf
499,2026-02-26,ARBEIT,"[Berufskraftfahrer/in, Auslieferungsfahrer/in ...",2023,Berufskraftfahrer/in

In [15]:
#df_bew_SH.to_csv("bewerber_SH_500.csv", index=False)

In [16]:
base = "https://rest.arbeitsagentur.de/infosysbub/absuche/pc/v1/ausbildungsangebot"
query = {
    #"sty": "",
    #"ids": "",
    #"orte": "",
    #"page": "",  
    "size": "250",
    #"uk": "",
    "re": "SLH",
    #"bt": "",
    #"bart": "",
    #"ityp": "",  
    #"ban": "",
    #"bg": ""
    
}
# safe=';' sorgt dafür, dass das Semikolon nicht encodiert wird, falls die API es so erwartet
url = f"{base}?{up.urlencode(query, safe=';')}"

headers = {
    "X-API-Key": "infosysbub-absuche",
    #"Accept": "application/json",
    #"User-Agent": "Mozilla/5.0",
}

r = requests.get(url, headers=headers, timeout=30)
print("URL:", r.url)
print("Status:", r.status_code, r.reason)
print("CT:", r.headers.get("content-type"))
data= r.json()

URL: https://rest.arbeitsagentur.de/infosysbub/absuche/pc/v1/ausbildungsangebot?size=250&re=SLH
Status: 200 OK
CT: application/hal+json

In [17]:
print(data.keys())

dict_keys(['_embedded', '_links', 'page'])

In [18]:
ausbildung=data["_embedded"]
ausbildung

{'termine': [{'id': 369359028,
   'unterrichtsform': {'id': 105,
    'bezeichnung': 'Sonstige Präsenzveranstaltung'},
   'dauer': {'id': 6, 'bezeichnung': 'mehr als 6 Monate bis 1 Jahr'},
   'anbieterbewertung': None,
   'angebot': {'id': 16367897,
    'titel': 'Vorbereitungskurs auf eine Umschulung zum Fachinformatiker inkl. CompTIA A+ Zertifizierung und Stressmanagement',
    'inhalt': '<p>Die IT-Branche wächst rasant und verlangt nach zertifizierten Fachkräften mit belastbarer Kompetenz. Der Vorbereitungskurs auf die Umschulung zum Fachinformatiker vermittelt fundiertes Wissen, integriert die CompTIA A+ Zertifizierung und stärkt mit Skills im Bereich Stressmanagement die persönliche Widerstandskraft.<br/></p><h4>Basics: Selbstorganisation und Teamwork am Arbeitsplatz</h4><p> (Dauer: ca. 4 Wochen)<br/></p><ul><li> Arbeits-/Selbstorganisation</li><li> Lern-/Arbeitstechniken</li><li> Kommunikation/Konflikte im Team</li><li> Zeit-/Stressmanagement</li></ul><h4>First & Second-Level-Support inkl. CompTIA A+ Zertifizierung</h4><p> (Dauer: ca. 4 Wochen)<br/></p><ul><li> IT-Hardware verstehen, installieren und warten</li><li> Netzwerke aufbauen, konfigurieren und Fehler beheben</li><li> Virtuelle Maschinen und Cloud-Dienste gezielt nutzen</li><li> Systeme sicher betreiben und gegen Bedrohungen schützen</li><li> IT-Systeme laufend pflegen und softwareseitig warten</li></ul><h4>Vorbereitungslehrgang auf eine medien-/ informationstechnische Umschulung oder Weiterbildung</h4><p> (Dauer: ca. 8 Wochen)<br/></p><ul><li> Arbeits-/Lerntechniken</li><li> Kommunikation/Fachsprache</li><li> Wirtschafts-/Sozialkunde</li><li> IT-/Multimedia-Anwendungen</li></ul>',
    'abschlussart': '<p>Trägerzertifikat</p>',
    'abschlussbezeichnung': '<p>Vorbereitungskurs auf eine Umschulung zum Fachinformatiker inkl. CompTIA A+ Zertifizierung und Stressmanagement</p>',
    'foerderung': '<p>Die Maßnahme ist nach AZAV durch die Cert-IT als fachkundige Stelle zugelassen. Bei Vorliegen der persönlichen Voraussetzungen besteht die Möglichkeit einer Förderung über einen Bildungsgutschein durch die Agentur für Arbeit (SGB III) bzw. JobCenter (SGB II), durch Rentenversicherungsträger, durch den ESF (Europäischen Sozialfonds) oder nach dem Soldatenversorgungsgesetz von bis zu 100 %. Nähere Auskünfte hierzu erteilen die lokalen Agenturen für Arbeit bzw. JobCenter, die Rentenversicherungsträger oder die Berufsförderungsdienste.</p>',
    'zugang': '<ul><li> Abgeschlossene Ausbildung im relevanten Bereich oder ein Studium bzw. ein abgebrochenes Hochschulstudium oder ausreichende Berufserfahrung</li><li> Deutsch in Wort und Schrift</li><li> Gute EDV-Kenntnisse</li><li> Grundlegende Englischkenntnisse wünschenswert, aber nicht zwingend erforderlich</li><li> Ein internes Auswahlverfahren im Rahmen eines Fachgespräches ist mit "gut geeignet" zu bestehen</li></ul><p>Des Weiteren gelten die Zugangsvoraussetzungen des Kostenträgers, Ausnahmen sind in Absprache mit dem COMCAVE.COLLEGE® und dem Kostenträger möglich.<br/>Die beruflichen und schulischen Zugangsvoraussetzungen werden anhand von Lebenslauf, Zeugnissen und Zertifikaten, bzw. einer Eignungsfeststellung im Rahmen eines ausführlichen persönlichen Fachgespräches geprüft.</p>',
    'zielgruppe': '<p>Diese Weiterbildung richtet sich an Interessenten (m/w/d), die den beruflichen Ein- oder Aufstieg planen und ihre beruflichen Perspektiven verbessern möchten.</p>',
    'anrechnung': None,
    'berechtigungen': None,
    'zusatzqualifikationen': None,
    'link': 'https://www.comcave.de/weiterbildung/bewerbungstraining-vorbereitung/vorbereitungskurse/vorbereitung-umschulung-fachinformatiker-comptia-aplus-stressmanagement/?utm_campaign=weiterbildung&utm_source=kursnet',
    'bildungsanbieter': {'id': 299149,
     'name': 'COMCAVE.COLLEGE GmbH',
     'telefonVorwahl': '0800',
     'telefonDurchwahl': '4443343',
     'mobilVorwahl': None,
     'mobilDurchwahl': None,
     'faxVorwahl': '0231',
     'faxDurchwahl': '7252622',
     'homepage': 'https://www.comcave.de',
     'email': 'anfrage@comcave.com',
     'adresse': {'id': 4275615,
      'bezeichnung': None,
      'strasse': 'Hauert 1',
      'ortStrasse': {'id': 21779,
       'plz': '44227',
       'name': 'Dortmund',
       'laengengrad': 7.4642,
       'breitengrad': 51.5142,
       'laengengradPlz': 7.426859,
       'breitengradPlz': 51.466757,
       'koordinaten': {'lat': 51.5142, 'lon': 7.4642},
       'koordinatenPlz': {'lat': 51.466757, 'lon': 7.426859},
       'land': {'id': 10,
        'name': 'Nordrhein-Westfalen',
        'laenderCode': 'D',
        'bundeslandCode': 'iD',
        'code': 'NRW'}},
      'postfach': None,
      'ortPostfach': None,
      'dienstleistungen': None,
      'ortsteil': None,
      'hinweise': None},
     'logo': {'id': 77390,
      'url': 'https://rest.arbeitsagentur.de/infosysbub/kursnet-rest/ct/v1/bildungsanbieter/299149/logos/77390'}},
    'bildungsart': {'id': 101, 'bezeichnung': 'Berufliche Grundqualifikation'},
    'systematiken': [{'dkzId': 59768,
      'codeNr': 'A 9.22',
      'kurzbezeichnung': None,
      'suchworte': [{'suchwort': 'Vorbereitung auf berufliche Weiterbildungslehrgänge'},
       {'suchwort': 'Weiterbildungsvorbereitung'}]}],
    'schulart': {'id': 105,
     'bezeichnung': 'Einrichtung der beruflichen Weiterbildung'},
    'behinderungen': [],
    'zertifizierer': [{'id': 24, 'name': 'Cert-IT GmbH'}],
    'traeger': None,
    'suchworte': [{'suchwort': 'Stressmanagement'},
     {'suchwort': 'Umschulung'},
     {'suchwort': 'programmieren'},
     {'suchwort': 'EDV'},
     {'suchwort': 'Vorbereitungslehrgang'},
     {'suchwort': 'Grundlagen Informationstechnik'},
     {'suchwort': 'Netzwerktechnologien'},
     {'suchwort': 'Vorbereitungskurs'},
     {'suchwort': 'Vorbereitungskurs auf eine Umschulung zum Fachinformatiker inkl. CompTIA A+ Zertifizierung und Stressmanagement'},
     {'suchwort': 'CompTIA'},
     {'suchwort': 'objektorientiertes programmieren'},
     {'suchwort': 'Systemtechnik'},
     {'suchwort': 'Orientierung'},
     {'suchwort': 'Kommunikation'},
     {'suchwort': 'digitale medien'},
     {'suchwort': 'Zertifizierung'},
     {'suchwort': 'Vorbereitung'},
     {'suchwort': 'Netzwerke'},
     {'suchwort': 'Fachinformatiker'},
     {'suchwort': 'Berufswelt'},
     {'suchwort': 'netzwerktechnik'},
     {'suchwort': 'Programmierung'},
     {'suchwort': 'Informationstechnik'},
     {'suchwort': 'Zeitmanagement'},
     {'suchwort': 'Vorbereitungskurs IT'},
     {'suchwort': 'Netzwerk'},
     {'suchwort': 'Arbeitsvorbereitung'}]},
   'adresse': {'id': 4292956,
    'bezeichnung': 'COMCAVE.COLLEGE GmbH',
    'strasse': 'Großer Wulfhagen 37',
    'ortStrasse': {'id': 14232,
     'plz': '25436',
     'name': 'Uetersen',
     'laengengrad': 9.6625,
     'breitengrad': 53.6842,
     'laengengradPlz': 9.676901,
     'breitengradPlz': 53.687437,
     'koordinaten': {'lat': 53.6842, 'lon': 9.6625},
     'koordinatenPlz': {'lat': 53.687437, 'lon': 9.676901},
     'land': {'id': 15,
      'name': 'Schleswig-Holstein',
      'laenderCode': 'D',
      'bundeslandCode': 'iD',
      'code': 'SLH'}},
    'postfach': None,
    'ortPostfach': None,
    'dienstleistungen': None,
    'ortsteil': None,
    'hinweise': '<p>Vom Hauptbahnhof können Sie die öffentlichen Verkehrsmittel nehmen, um uns innerhalb weniger Minuten zu erreichen. Sofern Sie mit dem PKW kommen, finden Sie in unmittelbarer Nähe zahlreiche Parkmöglichkeiten.</p>'},
   'unterrichtszeiten': '<p>Mo.-Fr. 08:45 bis 13:00 Uhr</p>',
   'kostenWert': None,
   'kostenWaehrung': 'EUR',
   'kostenBemerkung': '<p>Lehrgangsgebühr auf Anfrage</p>',
   'foerderung': True,
   'link': 'https://www.comcave.de/weiterbildung/bewerbungstraining-vorbereitung/vorbereitungskurse/vorbereitung-umschulung-fachinformatiker-comptia-aplus-stressmanagement/?utm_campaign=weiterbildung&utm_source=kursnet?kursmodell=teilzeit',
   'bemerkung': None,
   'beginn': 1780005600000,
   'ende': 1801522800000,
   'individuellerEinstieg': False,
   'anmeldeschluss': None,
   'bemerkungZeit': '<p>Der Unterricht findet dozentengeleitet und nach festgelegtem Stundenplan statt.</p>',
   'pruefendeStelle': 'Lehrgangsträger',
   'eigeneAngebotsnummer': None,
   'teilnehmerMin': 6,
   'teilnehmerMax': 25,
   'aktualisierungsdatum': 1772060400000,
   'veranstaltungsablaeufe': [],
   'unterrichtszeit': {'id': 2, 'bezeichnung': 'Teilzeit'},
   'ansprechpartner': [{'id': 1255171,
     'anrede': 'd',
     'titel': None,
     'nachname': 'Bildungsberatung',
     'vorname': 'Team',
     'telefonVorwahl': '0800',
     'telefonDurchwahl': '4443343',
     'mobilVorwahl': None,
     'mobilDurchwahl': None,
     'faxVorwahl': '0231',
     'faxDurchwahl': '7252622',
     'email': 'anfrage@comcave.de',
     'homepage': 'https://www.comcave.de',
     'rollen': [{'id': 1, 'bezeichnung': 'Ansprechpartner'}]}],
   'abstaende': []},
  {'id': 374077047,
   'unterrichtsform': {'id': 304,
    'bezeichnung': 'Sonstige kombinierte Lernform'},
   'dauer': {'id': 3, 'bezeichnung': 'mehr als 1 Woche bis 1 Monat'},
   'anbieterbewertung': None,
   'angebot': {'id': 16603854,
    'titel': 'Nachprüfungsvorbereitung Teil I der Umschulung Fachinformatiker Anwendungsentwicklung (w/m/d)',
    'inhalt': '<p>Lernziele: gezielte Vorbereitung auf die Nachprüfung einer Umschulung und Aufzeigen von Methoden zur Überwindung möglicher Prüfungsangst<br/></p><ul><li>Ablauf und Organisation der Wiederholungsprüfung</li><li>Umgang mit und Abbau von Prüfungsangst</li><li>Wiederholen und Üben prüfungsrelevanter Inhalte</li><li>Erarbeiten wichtiger Begriffe und Aussagen zu den Themengebieten</li></ul><p>Dieser Kurs findet auch in Teilzeit statt.</p>',
    'abschlussart': '<p>externe Prüfung, trägerinternes Zertifikat der WBS TRAINING AG</p>',
    'abschlussbezeichnung': '<p>IHK-Prüfung</p>',
    'foerderung': '<p>Bildungsgutschein, Rehabilitationsförderung</p>',
    'zugang': '<p>Die Zulassungsvoraussetzungen für die Abschlussprüfung müssen erfüllt sein (z. B. durch Absolvieren des Praktikums und Lerninhalte der AO).</p>',
    'zielgruppe': '<p>Personen, die z.B. mit Prüfungsangst zu kämpfen haben und sich gezielt auf eine weitere Prüfung vorbereiten möchten</p>',
    'anrechnung': None,
    'berechtigungen': None,
    'zusatzqualifikationen': None,
    'link': 'https://www.wbstraining.de/kurse/weiterbildung/vorbereitung-nachpruefung-gestreckte-abschlusspruefung-umschulung-fachinformatiker-anwendungsentwicklung/',
    'bildungsanbieter': {'id': 277507,
     'name': 'WBS TRAINING AG',
     'telefonVorwahl': '0800',
     'telefonDurchwahl': '9270003',
     'mobilVorwahl': None,
     'mobilDurchwahl': None,
     'faxVorwahl': None,
     'faxDurchwahl': None,
     'homepage': 'https://www.wbstraining.de/kn/',
     'email': 'info@wbstraining.de',
     'adresse': {'id': 3885410,
      'bezeichnung': None,
      'strasse': 'Lorenzweg 5',
      'ortStrasse': {'id': 95597,
       'plz': '12099',
       'name': 'Berlin',
       'laengengrad': 13.4056,
       'breitengrad': 52.5178,
       'laengengradPlz': 13.402635,
       'breitengradPlz': 52.460851,
       'koordinaten': {'lat': 52.5178, 'lon': 13.4056},
       'koordinatenPlz': {'lat': 52.460851, 'lon': 13.402635},
       'land': {'id': 3,
        'name': 'Berlin',
        'laenderCode': 'D',
        'bundeslandCode': 'iD',
        'code': 'BER'}},
      'postfach': None,
      'ortPostfach': None,
      'dienstleistungen': None,
      'ortsteil': None,
      'hinweise': '<p>Bitte beachten Sie, dass es sich hierbei um die Anschrift des Bildungsanbieters mit Sitz in Berlin handelt. Die lokale Anschrift des Veranstaltungsortes finden Sie direkt unter dem Angebot.</p>'},
     'logo': {'id': 61207,
      'url': 'https://rest.arbeitsagentur.de/infosysbub/kursnet-rest/ct/v1/bildungsanbieter/277507/logos/61207'}},
    'bildungsart': {'id': 101, 'bezeichnung': 'Berufliche Grundqualifikation'},
    'systematiken': [{'dkzId': 126733,
      'codeNr': 'A 9.34-02',
      'kurzbezeichnung': None,
      'suchworte': [{'suchwort': 'IT-Berufe - Prüfungsvorbereitung'},
       {'suchwort': 'Prüfungsvorbereitung - IT-Berufe'},
       {'suchwort': 'Prüfungsvorbereitung für Berufe der IT-Branche'},
       {'suchwort': 'Prüfungsvorbereitung für IT-Berufe'}]}],
    'schulart': {'id': 105,
     'bezeichnung': 'Einrichtung der beruflichen Weiterbildung'},
    'behinderungen': [],
    'zertifizierer': [{'id': 34,
      'name': 'DQS GmbH Deutsche Gesellschaft zur Zertifizierung von Managementsystemen'}],
    'traeger': None,
    'suchworte': [{'suchwort': 'Anwendungsentwicklung Umschulung Nachprüfung'},
     {'suchwort': 'Vorbereitung Nachprüfung Fachinformatik Anwendungsentwicklung'},
     {'suchwort': 'Vorbereitung einer Nachprüfung'},
     {'suchwort': 'Fachinformatik'},
     {'suchwort': 'Prüfungsangst überwinden'},
     {'suchwort': 'Nachprüfungsvorbereitung Teil I der Umschulung Fachinformatiker Anwendungsentwicklung (w/m/d)'},
     {'suchwort': 'Anwendungsentwicklung'},
     {'suchwort': 'Umschulung Fachinformatik'},
     {'suchwort': 'Vorbereitung Nachprüfung Fachinformatiker Anwendungsentwicklung'},
     {'suchwort': 'Nachprüfung Umschulung Fachinformatikerin Anwendungsentwicklung'},
     {'suchwort': 'Nachprüfung Umschulung vorbereiten'},
     {'suchwort': 'Fachinformatiker Anwendungsentwicklung'},
     {'suchwort': 'Fachinformatiker Umschulung'},
     {'suchwort': 'Nachprüfungsvorbereitung'},
     {'suchwort': 'Umschulung'},
     {'suchwort': 'Vorbereitungskurs Nachprüfung'},
     {'suchwort': 'Nachprüfung Umschulung Anwendungsentwicklung'},
     {'suchwort': 'Umschulung Fachinformatiker Nachprüfung'},
     {'suchwort': 'Nachprüfungsvorbereitung Teil I der Umschulung Fachinformatiker Anwendungsentwicklung'},
     {'suchwort': 'Hilfe bei Prüfungsangst'},
     {'suchwort': 'Umschulung Anwendungsentwicklung'},
     {'suchwort': 'Prüfungsangst überwinden Methoden'},
     {'suchwort': 'Umschulung Fachinformatiker Anwendungsentwicklung'},
     {'suchwort': 'Umschulung Fachinformatikerin Anwendungsentwicklung'},
     {'suchwort': 'Fachinformatiker'},
     {'suchwort': 'Teil'},
     {'suchwort': 'Fachinformatikerin Anwendungsentwicklung'},
     {'suchwort': 'Fachinformatik Anwendungsentwicklung'},
     {'suchwort': 'Fachinformatiker Umschulung Nachprüfung'},
     {'suchwort': 'Prüfungsangst'},
     {'suchwort': 'Nachprüfung vorbereiten'},
     {'suchwort': 'Fachinformatikerin Umschulung'},
     {'suchwort': 'Umschulung Nachprüfung'},
     {'suchwort': 'Nachprüfung Umschulung'},
     {'suchwort': 'Vorbereitung Nachprüfung Fachinformatikerin Anwendungsentwicklung'},
     {'suchwort': 'Nachprüfung Umschulung Fachinformatiker Anwendungsentwicklung'}]},
   'adresse': {'id': 3910443,
    'bezeichnung': 'WBS TRAINING AG',
    'strasse': 'Weberstraße 5',
    'ortStrasse': {'id': 13944,
     'plz': '25336',
     'name': 'Elmshorn',
     'laengengrad': 9.6614,
     'breitengrad': 53.7575,
     'laengengradPlz': 9.653448,
     'breitengradPlz': 53.740313,
     'koordinaten': {'lat': 53.7575, 'lon': 9.6614},
     'koordinatenPlz': {'lat': 53.740313, 'lon': 9.653448},
     'land': {'id': 15,
      'name': 'Schleswig-Holstein',
      'laenderCode': 'D',
      'bundeslandCode': 'iD',
      'code': 'SLH'}},
    'postfach': None,
    'ortPostfach': None,
    'dienstleistungen': None,
    'ortsteil': None,
    'hinweise': '<p>Die WBS TRAINING AG Elmshorn ist nur ca. 110 Meter von der Bushaltestelle Eichstraße entfernt. Parkmöglichkeiten befinden sich in unmittelbarer Nähe unseres Gebäudes. Die Schulungsräume befinden sich im Eckgebäude auf der Empore.</p>'},
   'unterrichtszeiten': '<p>Dieser Kurs findet auch in Teilzeit statt.</p>',
   'kostenWert': None,
   'kostenWaehrung': 'EUR',
   'kostenBemerkung': None,
   'foerderung': True,
   'link': 'https://www.wbstraining.de/kurse/weiterbildung/vorbereitung-nachpruefung-gestreckte-abschlusspruefung-umschulung-fachinformatiker-anwendungsentwicklung/',
   'bemerkung': None,
   'beginn': 1789077600000,
   'ende': 1790287200000,
   'individuellerEinstieg': False,
   'anmeldeschluss': None,
   'bemerkungZeit': '<p>Du folgst dem interaktiven und mediengestützten Unterricht in einer digitalen Lernumgebung am Veranstaltungsort und/oder zu Hause, für dessen Teilnahme du mit einem PC-Arbeitsplatz ausgestattet wirst. Du stehst live im Austausch mit deinen Dozent:innen, die dich und deine Mitlernenden begleiten. Gemeinsam gestaltet ihr den Unterricht, in dem neben Fachwissen und praxisnahen Kompetenzen auch typische Arbeitsplatzsituationen vermittelt und gezielt trainiert werden.</p>',
   'pruefendeStelle': None,
   'eigeneAngebotsnummer': 'K036175',
   'teilnehmerMin': 10,
   'teilnehmerMax': 25,
   'aktualisierungsdatum': 1771887600000,
   'veranstaltungsablaeufe': [],
   'unterrichtszeit': {'id': 1, 'bezeichnung': 'Vollzeit'},
   'ansprechpartner': [{'id': 1276944,
     'anrede': 'm',
     'titel': None,
     'nachname': 'Strätker',
     'vorname': 'Jan',
     'telefonVorwahl': '04121',
     'telefonDurchwahl': '7897948',
     'mobilVorwahl': None,
     'mobilDurchwahl': None,
     'faxVorwahl': None,
     'faxDurchwahl': None,
     'email': 'elmshorn@wbstraining.de',
     'homepage': 'https://www.wbstraining.de/weiterbildung-elmshorn/',
     'rollen': [{'id': 1, 'bezeichnung': 'Ansprechpartner'}]}],
   'abstaende': []},
  {'id': 352609402,
   'unterrichtsform': {'id': 105,
    'bezeichnung': 'Sonstige Präsenzveranstaltung'},
   'dauer': {'id': 4, 'bezeichnung': 'mehr als 1 Monat bis 3 Monate'},
   'anbieterbewertung': None,
   'angebot': {'id': 3706039,
    'titel': 'Eignungsabklärung/Arbeitserprobung',
    'inhalt': '<p>20-60tägige Eignungsabklärung/Arbeitserprobung in verschiedenen Berufsfeldern.<br/>Schwerpunkte: Metall, Holz, Farbe, Hauswirtschaft, Büro, Verkauf, Technisches Produktdesign, Lager/Logistik</p>',
    'abschlussart': None,
    'abschlussbezeichnung': None,
    'foerderung': None,
    'zugang': None,
    'zielgruppe': '<p>Psychisch behinderte junge Menschen und Erwachsene ohne Erstausbildung.</p>',
    'anrechnung': None,
    'berechtigungen': None,
    'zusatzqualifikationen': None,
    'link': None,
    'bildungsanbieter': {'id': 6438,
     'name': 'Berufsbildungswerk Neumünster',
     'telefonVorwahl': '04321',
     'telefonDurchwahl': '90230',
     'mobilVorwahl': None,
     'mobilDurchwahl': None,
     'faxVorwahl': None,
     'faxDurchwahl': None,
     'homepage': 'http://www.bbw-nms.de',
     'email': 'info.bbwnms@ngd.de',
     'adresse': {'id': 166710,
      'bezeichnung': None,
      'strasse': 'Am Hohrkamp 54',
      'ortStrasse': {'id': 16181,
       'plz': '24537',
       'name': 'Neumünster, Holstein',
       'laengengrad': 9.9883,
       'breitengrad': 54.07,
       'laengengradPlz': 9.953443,
       'breitengradPlz': 54.088171,
       'koordinaten': {'lat': 54.07, 'lon': 9.9883},
       'koordinatenPlz': {'lat': 54.088171, 'lon': 9.953443},
       'land': {'id': 15,
        'name': 'Schleswig-Holstein',
        'laenderCode': 'D',
        'bundeslandCode': 'iD',
        'code': 'SLH'}},
      'postfach': None,
      'ortPostfach': None,
      'dienstleistungen': None,
      'ortsteil': None,
      'hinweise': None},
     'logo': None},
    'bildungsart': {'id': 101, 'bezeichnung': 'Berufliche Grundqualifikation'},
    'systematiken': [{'dkzId': 119948,
      'codeNr': 'RV 1-1',
      'kurzbezeichnung': None,
      'suchworte': [{'suchwort': 'Berufliche Eignung'},
       {'suchwort': 'Reha'},
       {'suchwort': 'Rehabilitand'},
       {'suchwort': 'Rehabilitanden'},
       {'suchwort': 'Rehabilitation'}]}],
    'schulart': {'id': 103, 'bezeichnung': 'Berufsbildungswerk (R)'},
    'behinderungen': [{'id': 14, 'bezeichnung': 'Psychische Behinderungen'}],
    'zertifizierer': [],
    'traeger': {'id': 1, 'name': 'Bundesagentur für Arbeit'},
    'suchworte': [{'suchwort': 'Eignungsabklärung'},
     {'suchwort': 'Arbeitserprobung'},

In [19]:
df_aus_SH = json_normalize(ausbildung)
df_aus_SH

                                             termine
0  [{'id': 369359028, 'unterrichtsform': {'id': 1...